import '../../../core/assets/game_asset_profile.dart';
import 'gen4_pokemon_types.dart';
import 'move_type_resolver.dart';

abstract final class PokemonTypeResolver {
  static List<PokemonMoveType> resolve(
    GameAssetProfile profile,
    int pokemonId,
  ) {
    if (profile.game == PokemonAssetGame.diamondPearl ||
        profile.game == PokemonAssetGame.platinum ||
        profile.game == PokemonAssetGame.heartGoldSoulSilver) {
      return gen4PokemonTypes[pokemonId] ?? const <PokemonMoveType>[];
    }
    final overrides = switch (profile.game) {
      PokemonAssetGame.redBlue || PokemonAssetGame.yellow => _gen1Overrides,
      PokemonAssetGame.gold ||
      PokemonAssetGame.silver ||
      PokemonAssetGame.crystal => _gen2Overrides,
      _ => _gen3Overrides,
    };
    return overrides[pokemonId] ??
        _currentTypes[pokemonId] ??
        const <PokemonMoveType>[];
  }

  static const Map<int, List<PokemonMoveType>> _currentTypes =
      <int, List<PokemonMoveType>>{
    1: <PokemonMoveType>[PokemonMoveType.grass, PokemonMoveType.poison],
    2: <PokemonMoveType>[PokemonMoveType.grass, PokemonMoveType.poison],
    3: <PokemonMoveType>[PokemonMoveType.grass, PokemonMoveType.poison],
    4: <PokemonMoveType>[PokemonMoveType.fire],
    5: <PokemonMoveType>[PokemonMoveType.fire],
    6: <PokemonMoveType>[PokemonMoveType.fire, PokemonMoveType.flying],
    7: <PokemonMoveType>[PokemonMoveType.water],
    8: <PokemonMoveType>[PokemonMoveType.water],
    9: <PokemonMoveType>[PokemonMoveType.water],
    10: <PokemonMoveType>[PokemonMoveType.bug],
    11: <PokemonMoveType>[PokemonMoveType.bug],
    12: <PokemonMoveType>[PokemonMoveType.bug, PokemonMoveType.flying],
    13: <PokemonMoveType>[PokemonMoveType.bug, PokemonMoveType.poison],
    14: <PokemonMoveType>[PokemonMoveType.bug, PokemonMoveType.poison],
    15: <PokemonMoveType>[PokemonMoveType.bug, PokemonMoveType.poison],
    16: <PokemonMoveType>[PokemonMoveType.normal, PokemonMoveType.flying],
    17: <PokemonMoveType>[PokemonMoveType.normal, PokemonMoveType.flying],
    18: <PokemonMoveType>[PokemonMoveType.normal, PokemonMoveType.flying],
    19: <PokemonMoveType>[PokemonMoveType.normal],
    20: <PokemonMoveType>[PokemonMoveType.normal],
    21: <PokemonMoveType>[PokemonMoveType.normal, PokemonMoveType.flying],
    22: <PokemonMoveType>[PokemonMoveType.normal, PokemonMoveType.flying],
    23: <PokemonMoveType>[PokemonMoveType.poison],
    24: <PokemonMoveType>[PokemonMoveType.poison],
    25: <PokemonMoveType>[PokemonMoveType.electric],
    26: <PokemonMoveType>[PokemonMoveType.electric],
    27: <PokemonMoveType>[PokemonMoveType.ground],
    28: <PokemonMoveType>[PokemonMoveType.ground],
    29: <PokemonMoveType>[PokemonMoveType.poison],
    30: <PokemonMoveType>[PokemonMoveType.poison],
    31: <PokemonMoveType>[PokemonMoveType.poison, PokemonMoveType.ground],
    32: <PokemonMoveType>[PokemonMoveType.poison],
    33: <PokemonMoveType>[PokemonMoveType.poison],
    34: <PokemonMoveType>[PokemonMoveType.poison, PokemonMoveType.ground],
    35: <PokemonMoveType>[PokemonMoveType.unknown],
    36: <PokemonMoveType>[PokemonMoveType.unknown],
    37: <PokemonMoveType>[PokemonMoveType.fire],
    38: <PokemonMoveType>[PokemonMoveType.fire],
    39: <PokemonMoveType>[PokemonMoveType.normal, PokemonMoveType.unknown],
    40: <PokemonMoveType>[PokemonMoveType.normal, PokemonMoveType.unknown],
    41: <PokemonMoveType>[PokemonMoveType.poison, PokemonMoveType.flying],
    42: <PokemonMoveType>[PokemonMoveType.poison, PokemonMoveType.flying],
    43: <PokemonMoveType>[PokemonMoveType.grass, PokemonMoveType.poison],
    44: <PokemonMoveType>[PokemonMoveType.grass, PokemonMoveType.poison],
    45: <PokemonMoveType>[PokemonMoveType.grass, PokemonMoveType.poison],
    46: <PokemonMoveType>[PokemonMoveType.bug, PokemonMoveType.grass],
    47: <PokemonMoveType>[PokemonMoveType.bug, PokemonMoveType.grass],
    48: <PokemonMoveType>[PokemonMoveType.bug, PokemonMoveType.poison],
    49: <PokemonMoveType>[PokemonMoveType.bug, PokemonMoveType.poison],
    50: <PokemonMoveType>[PokemonMoveType.ground],
    51: <PokemonMoveType>[PokemonMoveType.ground],
    52: <PokemonMoveType>[PokemonMoveType.normal],
    53: <PokemonMoveType>[PokemonMoveType.normal],
    54: <PokemonMoveType>[PokemonMoveType.water],
    55: <PokemonMoveType>[PokemonMoveType.water],
    56: <PokemonMoveType>[PokemonMoveType.fighting],
    57: <PokemonMoveType>[PokemonMoveType.fighting],
    58: <PokemonMoveType>[PokemonMoveType.fire],
    59: <PokemonMoveType>[PokemonMoveType.fire],
    60: <PokemonMoveType>[PokemonMoveType.water],
    61: <PokemonMoveType>[PokemonMoveType.water],
    62: <PokemonMoveType>[PokemonMoveType.water, PokemonMoveType.fighting],
    63: <PokemonMoveType>[PokemonMoveType.psychic],
    64: <PokemonMoveType>[PokemonMoveType.psychic],
    65: <PokemonMoveType>[PokemonMoveType.psychic],
    66: <PokemonMoveType>[PokemonMoveType.fighting],
    67: <PokemonMoveType>[PokemonMoveType.fighting],
    68: <PokemonMoveType>[PokemonMoveType.fighting],
    69: <PokemonMoveType>[PokemonMoveType.grass, PokemonMoveType.poison],
    70: <PokemonMoveType>[PokemonMoveType.grass, PokemonMoveType.poison],
    71: <PokemonMoveType>[PokemonMoveType.grass, PokemonMoveType.poison],
    72: <PokemonMoveType>[PokemonMoveType.water, PokemonMoveType.poison],
    73: <PokemonMoveType>[PokemonMoveType.water, PokemonMoveType.poison],
    74: <PokemonMoveType>[PokemonMoveType.rock, PokemonMoveType.ground],
    75: <PokemonMoveType>[PokemonMoveType.rock, PokemonMoveType.ground],
    76: <PokemonMoveType>[PokemonMoveType.rock, PokemonMoveType.ground],
    77: <PokemonMoveType>[PokemonMoveType.fire],
    78: <PokemonMoveType>[PokemonMoveType.fire],
    79: <PokemonMoveType>[PokemonMoveType.water, PokemonMoveType.psychic],
    80: <PokemonMoveType>[PokemonMoveType.water, PokemonMoveType.psychic],
    81: <PokemonMoveType>[PokemonMoveType.electric, PokemonMoveType.steel],
    82: <PokemonMoveType>[PokemonMoveType.electric, PokemonMoveType.steel],
    83: <PokemonMoveType>[PokemonMoveType.normal, PokemonMoveType.flying],
    84: <PokemonMoveType>[PokemonMoveType.normal, PokemonMoveType.flying],
    85: <PokemonMoveType>[PokemonMoveType.normal, PokemonMoveType.flying],
    86: <PokemonMoveType>[PokemonMoveType.water],
    87: <PokemonMoveType>[PokemonMoveType.water, PokemonMoveType.ice],
    88: <PokemonMoveType>[PokemonMoveType.poison],
    89: <PokemonMoveType>[PokemonMoveType.poison],
    90: <PokemonMoveType>[PokemonMoveType.water],
    91: <PokemonMoveType>[PokemonMoveType.water, PokemonMoveType.ice],
    92: <PokemonMoveType>[PokemonMoveType.ghost, PokemonMoveType.poison],
    93: <PokemonMoveType>[PokemonMoveType.ghost, PokemonMoveType.poison],
    94: <PokemonMoveType>[PokemonMoveType.ghost, PokemonMoveType.poison],
    95: <PokemonMoveType>[PokemonMoveType.rock, PokemonMoveType.ground],
    96: <PokemonMoveType>[PokemonMoveType.psychic],
    97: <PokemonMoveType>[PokemonMoveType.psychic],
    98: <PokemonMoveType>[PokemonMoveType.water],
    99: <PokemonMoveType>[PokemonMoveType.water],
    100: <PokemonMoveType>[PokemonMoveType.electric],
    101: <PokemonMoveType>[PokemonMoveType.electric],
    102: <PokemonMoveType>[PokemonMoveType.grass, PokemonMoveType.psychic],
    103: <PokemonMoveType>[PokemonMoveType.grass, PokemonMoveType.psychic],
    104: <PokemonMoveType>[PokemonMoveType.ground],
    105: <PokemonMoveType>[PokemonMoveType.ground],
    106: <PokemonMoveType>[PokemonMoveType.fighting],
    107: <PokemonMoveType>[PokemonMoveType.fighting],
    108: <PokemonMoveType>[PokemonMoveType.normal],
    109: <PokemonMoveType>[PokemonMoveType.poison],
    110: <PokemonMoveType>[PokemonMoveType.poison],
    111: <PokemonMoveType>[PokemonMoveType.ground, PokemonMoveType.rock],
    112: <PokemonMoveType>[PokemonMoveType.ground, PokemonMoveType.rock],
    113: <PokemonMoveType>[PokemonMoveType.normal],
    114: <PokemonMoveType>[PokemonMoveType.grass],
    115: <PokemonMoveType>[PokemonMoveType.normal],
    116: <PokemonMoveType>[PokemonMoveType.water],
    117: <PokemonMoveType>[PokemonMoveType.water],
    118: <PokemonMoveType>[PokemonMoveType.water],
    119: <PokemonMoveType>[PokemonMoveType.water],
    120: <PokemonMoveType>[PokemonMoveType.water],
    121: <PokemonMoveType>[PokemonMoveType.water, PokemonMoveType.psychic],
    122: <PokemonMoveType>[PokemonMoveType.psychic, PokemonMoveType.unknown],
    123: <PokemonMoveType>[PokemonMoveType.bug, PokemonMoveType.flying],
    124: <PokemonMoveType>[PokemonMoveType.ice, PokemonMoveType.psychic],
    125: <PokemonMoveType>[PokemonMoveType.electric],
    126: <PokemonMoveType>[PokemonMoveType.fire],
    127: <PokemonMoveType>[PokemonMoveType.bug],
    128: <PokemonMoveType>[PokemonMoveType.normal],
    129: <PokemonMoveType>[PokemonMoveType.water],
    130: <PokemonMoveType>[PokemonMoveType.water, PokemonMoveType.flying],
    131: <PokemonMoveType>[PokemonMoveType.water, PokemonMoveType.ice],
    132: <PokemonMoveType>[PokemonMoveType.normal],
    133: <PokemonMoveType>[PokemonMoveType.normal],
    134: <PokemonMoveType>[PokemonMoveType.water],
    135: <PokemonMoveType>[PokemonMoveType.electric],
    136: <PokemonMoveType>[PokemonMoveType.fire],
    137: <PokemonMoveType>[PokemonMoveType.normal],
    138: <PokemonMoveType>[PokemonMoveType.rock, PokemonMoveType.water],
    139: <PokemonMoveType>[PokemonMoveType.rock, PokemonMoveType.water],
    140: <PokemonMoveType>[PokemonMoveType.rock, PokemonMoveType.water],
    141: <PokemonMoveType>[PokemonMoveType.rock, PokemonMoveType.water],
    142: <PokemonMoveType>[PokemonMoveType.rock, PokemonMoveType.flying],
    143: <PokemonMoveType>[PokemonMoveType.normal],
    144: <PokemonMoveType>[PokemonMoveType.ice, PokemonMoveType.flying],
    145: <PokemonMoveType>[PokemonMoveType.electric, PokemonMoveType.flying],
    146: <PokemonMoveType>[PokemonMoveType.fire, PokemonMoveType.flying],
    147: <PokemonMoveType>[PokemonMoveType.dragon],
    148: <PokemonMoveType>[PokemonMoveType.dragon],
    149: <PokemonMoveType>[PokemonMoveType.dragon, PokemonMoveType.flying],
    150: <PokemonMoveType>[PokemonMoveType.psychic],
    151: <PokemonMoveType>[PokemonMoveType.psychic],
    152: <PokemonMoveType>[PokemonMoveType.grass],
    153: <PokemonMoveType>[PokemonMoveType.grass],
    154: <PokemonMoveType>[PokemonMoveType.grass],
    155: <PokemonMoveType>[PokemonMoveType.fire],
    156: <PokemonMoveType>[PokemonMoveType.fire],
    157: <PokemonMoveType>[PokemonMoveType.fire],
    158: <PokemonMoveType>[PokemonMoveType.water],
    159: <PokemonMoveType>[PokemonMoveType.water],
    160: <PokemonMoveType>[PokemonMoveType.water],
    161: <PokemonMoveType>[PokemonMoveType.normal],
    162: <PokemonMoveType>[PokemonMoveType.normal],
    163: <PokemonMoveType>[PokemonMoveType.normal, PokemonMoveType.flying],
    164: <PokemonMoveType>[PokemonMoveType.normal, PokemonMoveType.flying],
    165: <PokemonMoveType>[PokemonMoveType.bug, PokemonMoveType.flying],
    166: <PokemonMoveType>[PokemonMoveType.bug, PokemonMoveType.flying],
    167: <PokemonMoveType>[PokemonMoveType.bug, PokemonMoveType.poison],
    168: <PokemonMoveType>[PokemonMoveType.bug, PokemonMoveType.poison],
    169: <PokemonMoveType>[PokemonMoveType.poison, PokemonMoveType.flying],
    170: <PokemonMoveType>[PokemonMoveType.water, PokemonMoveType.electric],
    171: <PokemonMoveType>[PokemonMoveType.water, PokemonMoveType.electric],
    172: <PokemonMoveType>[PokemonMoveType.electric],
    173: <PokemonMoveType>[PokemonMoveType.unknown],
    174: <PokemonMoveType>[PokemonMoveType.normal, PokemonMoveType.unknown],
    175: <PokemonMoveType>[PokemonMoveType.unknown],
    176: <PokemonMoveType>[PokemonMoveType.unknown, PokemonMoveType.flying],
    177: <PokemonMoveType>[PokemonMoveType.psychic, PokemonMoveType.flying],
    178: <PokemonMoveType>[PokemonMoveType.psychic, PokemonMoveType.flying],
    179: <PokemonMoveType>[PokemonMoveType.electric],
    180: <PokemonMoveType>[PokemonMoveType.electric],
    181: <PokemonMoveType>[PokemonMoveType.electric],
    182: <PokemonMoveType>[PokemonMoveType.grass],
    183: <PokemonMoveType>[PokemonMoveType.water, PokemonMoveType.unknown],
    184: <PokemonMoveType>[PokemonMoveType.water, PokemonMoveType.unknown],
    185: <PokemonMoveType>[PokemonMoveType.rock],
    186: <PokemonMoveType>[PokemonMoveType.water],
    187: <PokemonMoveType>[PokemonMoveType.grass, PokemonMoveType.flying],
    188: <PokemonMoveType>[PokemonMoveType.grass, PokemonMoveType.flying],
    189: <PokemonMoveType>[PokemonMoveType.grass, PokemonMoveType.flying],
    190: <PokemonMoveType>[PokemonMoveType.normal],
    191: <PokemonMoveType>[PokemonMoveType.grass],
    192: <PokemonMoveType>[PokemonMoveType.grass],
    193: <PokemonMoveType>[PokemonMoveType.bug, PokemonMoveType.flying],
    194: <PokemonMoveType>[PokemonMoveType.water, PokemonMoveType.ground],
    195: <PokemonMoveType>[PokemonMoveType.water, PokemonMoveType.ground],
    196: <PokemonMoveType>[PokemonMoveType.psychic],
    197: <PokemonMoveType>[PokemonMoveType.dark],
    198: <PokemonMoveType>[PokemonMoveType.dark, PokemonMoveType.flying],
    199: <PokemonMoveType>[PokemonMoveType.water, PokemonMoveType.psychic],
    200: <PokemonMoveType>[PokemonMoveType.ghost],
    201: <PokemonMoveType>[PokemonMoveType.psychic],
    202: <PokemonMoveType>[PokemonMoveType.psychic],
    203: <PokemonMoveType>[PokemonMoveType.normal, PokemonMoveType.psychic],
    204: <PokemonMoveType>[PokemonMoveType.bug],
    205: <PokemonMoveType>[PokemonMoveType.bug, PokemonMoveType.steel],
    206: <PokemonMoveType>[PokemonMoveType.normal],
    207: <PokemonMoveType>[PokemonMoveType.ground, PokemonMoveType.flying],
    208: <PokemonMoveType>[PokemonMoveType.steel, PokemonMoveType.ground],
    209: <PokemonMoveType>[PokemonMoveType.unknown],
    210: <PokemonMoveType>[PokemonMoveType.unknown],
    211: <PokemonMoveType>[PokemonMoveType.water, PokemonMoveType.poison],
    212: <PokemonMoveType>[PokemonMoveType.bug, PokemonMoveType.steel],
    213: <PokemonMoveType>[PokemonMoveType.bug, PokemonMoveType.rock],
    214: <PokemonMoveType>[PokemonMoveType.bug, PokemonMoveType.fighting],
    215: <PokemonMoveType>[PokemonMoveType.dark, PokemonMoveType.ice],
    216: <PokemonMoveType>[PokemonMoveType.normal],
    217: <PokemonMoveType>[PokemonMoveType.normal],
    218: <PokemonMoveType>[PokemonMoveType.fire],
    219: <PokemonMoveType>[PokemonMoveType.fire, PokemonMoveType.rock],
    220: <PokemonMoveType>[PokemonMoveType.ice, PokemonMoveType.ground],
    221: <PokemonMoveType>[PokemonMoveType.ice, PokemonMoveType.ground],
    222: <PokemonMoveType>[PokemonMoveType.water, PokemonMoveType.rock],
    223: <PokemonMoveType>[PokemonMoveType.water],
    224: <PokemonMoveType>[PokemonMoveType.water],
    225: <PokemonMoveType>[PokemonMoveType.ice, PokemonMoveType.flying],
    226: <PokemonMoveType>[PokemonMoveType.water, PokemonMoveType.flying],
    227: <PokemonMoveType>[PokemonMoveType.steel, PokemonMoveType.flying],
    228: <PokemonMoveType>[PokemonMoveType.dark, PokemonMoveType.fire],
    229: <PokemonMoveType>[PokemonMoveType.dark, PokemonMoveType.fire],
    230: <PokemonMoveType>[PokemonMoveType.water, PokemonMoveType.dragon],
    231: <PokemonMoveType>[PokemonMoveType.ground],
    232: <PokemonMoveType>[PokemonMoveType.ground],
    233: <PokemonMoveType>[PokemonMoveType.normal],
    234: <PokemonMoveType>[PokemonMoveType.normal],
    235: <PokemonMoveType>[PokemonMoveType.normal],
    236: <PokemonMoveType>[PokemonMoveType.fighting],
    237: <PokemonMoveType>[PokemonMoveType.fighting],
    238: <PokemonMoveType>[PokemonMoveType.ice, PokemonMoveType.psychic],
    239: <PokemonMoveType>[PokemonMoveType.electric],
    240: <PokemonMoveType>[PokemonMoveType.fire],
    241: <PokemonMoveType>[PokemonMoveType.normal],
    242: <PokemonMoveType>[PokemonMoveType.normal],
    243: <PokemonMoveType>[PokemonMoveType.electric],
    244: <PokemonMoveType>[PokemonMoveType.fire],
    245: <PokemonMoveType>[PokemonMoveType.water],
    246: <PokemonMoveType>[PokemonMoveType.rock, PokemonMoveType.ground],
    247: <PokemonMoveType>[PokemonMoveType.rock, PokemonMoveType.ground],
    248: <PokemonMoveType>[PokemonMoveType.rock, PokemonMoveType.dark],
    249: <PokemonMoveType>[PokemonMoveType.psychic, PokemonMoveType.flying],
    250: <PokemonMoveType>[PokemonMoveType.fire, PokemonMoveType.flying],
    251: <PokemonMoveType>[PokemonMoveType.psychic, PokemonMoveType.grass],
    252: <PokemonMoveType>[PokemonMoveType.grass],
    253: <PokemonMoveType>[PokemonMoveType.grass],
    254: <PokemonMoveType>[PokemonMoveType.grass],
    255: <PokemonMoveType>[PokemonMoveType.fire],
    256: <PokemonMoveType>[PokemonMoveType.fire, PokemonMoveType.fighting],
    257: <PokemonMoveType>[PokemonMoveType.fire, PokemonMoveType.fighting],
    258: <PokemonMoveType>[PokemonMoveType.water],
    259: <PokemonMoveType>[PokemonMoveType.water, PokemonMoveType.ground],
    260: <PokemonMoveType>[PokemonMoveType.water, PokemonMoveType.ground],
    261: <PokemonMoveType>[PokemonMoveType.dark],
    262: <PokemonMoveType>[PokemonMoveType.dark],
    263: <PokemonMoveType>[PokemonMoveType.normal],
    264: <PokemonMoveType>[PokemonMoveType.normal],
    265: <PokemonMoveType>[PokemonMoveType.bug],
    266: <PokemonMoveType>[PokemonMoveType.bug],
    267: <PokemonMoveType>[PokemonMoveType.bug, PokemonMoveType.flying],
    268: <PokemonMoveType>[PokemonMoveType.bug],
    269: <PokemonMoveType>[PokemonMoveType.bug, PokemonMoveType.poison],
    270: <PokemonMoveType>[PokemonMoveType.water, PokemonMoveType.grass],
    271: <PokemonMoveType>[PokemonMoveType.water, PokemonMoveType.grass],
    272: <PokemonMoveType>[PokemonMoveType.water, PokemonMoveType.grass],
    273: <PokemonMoveType>[PokemonMoveType.grass],
    274: <PokemonMoveType>[PokemonMoveType.grass, PokemonMoveType.dark],
    275: <PokemonMoveType>[PokemonMoveType.grass, PokemonMoveType.dark],
    276: <PokemonMoveType>[PokemonMoveType.normal, PokemonMoveType.flying],
    277: <PokemonMoveType>[PokemonMoveType.normal, PokemonMoveType.flying],
    278: <PokemonMoveType>[PokemonMoveType.water, PokemonMoveType.flying],
    279: <PokemonMoveType>[PokemonMoveType.water, PokemonMoveType.flying],
    280: <PokemonMoveType>[PokemonMoveType.psychic, PokemonMoveType.unknown],
    281: <PokemonMoveType>[PokemonMoveType.psychic, PokemonMoveType.unknown],
    282: <PokemonMoveType>[PokemonMoveType.psychic, PokemonMoveType.unknown],
    283: <PokemonMoveType>[PokemonMoveType.bug, PokemonMoveType.water],
    284: <PokemonMoveType>[PokemonMoveType.bug, PokemonMoveType.flying],
    285: <PokemonMoveType>[PokemonMoveType.grass],
    286: <PokemonMoveType>[PokemonMoveType.grass, PokemonMoveType.fighting],
    287: <PokemonMoveType>[PokemonMoveType.normal],
    288: <PokemonMoveType>[PokemonMoveType.normal],
    289: <PokemonMoveType>[PokemonMoveType.normal],
    290: <PokemonMoveType>[PokemonMoveType.bug, PokemonMoveType.ground],
    291: <PokemonMoveType>[PokemonMoveType.bug, PokemonMoveType.flying],
    292: <PokemonMoveType>[PokemonMoveType.bug, PokemonMoveType.ghost],
    293: <PokemonMoveType>[PokemonMoveType.normal],
    294: <PokemonMoveType>[PokemonMoveType.normal],
    295: <PokemonMoveType>[PokemonMoveType.normal],
    296: <PokemonMoveType>[PokemonMoveType.fighting],
    297: <PokemonMoveType>[PokemonMoveType.fighting],
    298: <PokemonMoveType>[PokemonMoveType.normal, PokemonMoveType.unknown],
    299: <PokemonMoveType>[PokemonMoveType.rock],
    300: <PokemonMoveType>[PokemonMoveType.normal],
    301: <PokemonMoveType>[PokemonMoveType.normal],
    302: <PokemonMoveType>[PokemonMoveType.dark, PokemonMoveType.ghost],
    303: <PokemonMoveType>[PokemonMoveType.steel, PokemonMoveType.unknown],
    304: <PokemonMoveType>[PokemonMoveType.steel, PokemonMoveType.rock],
    305: <PokemonMoveType>[PokemonMoveType.steel, PokemonMoveType.rock],
    306: <PokemonMoveType>[PokemonMoveType.steel, PokemonMoveType.rock],
    307: <PokemonMoveType>[PokemonMoveType.fighting, PokemonMoveType.psychic],
    308: <PokemonMoveType>[PokemonMoveType.fighting, PokemonMoveType.psychic],
    309: <PokemonMoveType>[PokemonMoveType.electric],
    310: <PokemonMoveType>[PokemonMoveType.electric],
    311: <PokemonMoveType>[PokemonMoveType.electric],
    312: <PokemonMoveType>[PokemonMoveType.electric],
    313: <PokemonMoveType>[PokemonMoveType.bug],
    314: <PokemonMoveType>[PokemonMoveType.bug],
    315: <PokemonMoveType>[PokemonMoveType.grass, PokemonMoveType.poison],
    316: <PokemonMoveType>[PokemonMoveType.poison],
    317: <PokemonMoveType>[PokemonMoveType.poison],
    318: <PokemonMoveType>[PokemonMoveType.water, PokemonMoveType.dark],
    319: <PokemonMoveType>[PokemonMoveType.water, PokemonMoveType.dark],
    320: <PokemonMoveType>[PokemonMoveType.water],
    321: <PokemonMoveType>[PokemonMoveType.water],
    322: <PokemonMoveType>[PokemonMoveType.fire, PokemonMoveType.ground],
    323: <PokemonMoveType>[PokemonMoveType.fire, PokemonMoveType.ground],
    324: <PokemonMoveType>[PokemonMoveType.fire],
    325: <PokemonMoveType>[PokemonMoveType.psychic],
    326: <PokemonMoveType>[PokemonMoveType.psychic],
    327: <PokemonMoveType>[PokemonMoveType.normal],
    328: <PokemonMoveType>[PokemonMoveType.ground],
    329: <PokemonMoveType>[PokemonMoveType.ground, PokemonMoveType.dragon],
    330: <PokemonMoveType>[PokemonMoveType.ground, PokemonMoveType.dragon],
    331: <PokemonMoveType>[PokemonMoveType.grass],
    332: <PokemonMoveType>[PokemonMoveType.grass, PokemonMoveType.dark],
    333: <PokemonMoveType>[PokemonMoveType.normal, PokemonMoveType.flying],
    334: <PokemonMoveType>[PokemonMoveType.dragon, PokemonMoveType.flying],
    335: <PokemonMoveType>[PokemonMoveType.normal],
    336: <PokemonMoveType>[PokemonMoveType.poison],
    337: <PokemonMoveType>[PokemonMoveType.rock, PokemonMoveType.psychic],
    338: <PokemonMoveType>[PokemonMoveType.rock, PokemonMoveType.psychic],
    339: <PokemonMoveType>[PokemonMoveType.water, PokemonMoveType.ground],
    340: <PokemonMoveType>[PokemonMoveType.water, PokemonMoveType.ground],
    341: <PokemonMoveType>[PokemonMoveType.water],
    342: <PokemonMoveType>[PokemonMoveType.water, PokemonMoveType.dark],
    343: <PokemonMoveType>[PokemonMoveType.ground, PokemonMoveType.psychic],
    344: <PokemonMoveType>[PokemonMoveType.ground, PokemonMoveType.psychic],
    345: <PokemonMoveType>[PokemonMoveType.rock, PokemonMoveType.grass],
    346: <PokemonMoveType>[PokemonMoveType.rock, PokemonMoveType.grass],
    347: <PokemonMoveType>[PokemonMoveType.rock, PokemonMoveType.bug],
    348: <PokemonMoveType>[PokemonMoveType.rock, PokemonMoveType.bug],
    349: <PokemonMoveType>[PokemonMoveType.water],
    350: <PokemonMoveType>[PokemonMoveType.water],
    351: <PokemonMoveType>[PokemonMoveType.normal],
    352: <PokemonMoveType>[PokemonMoveType.normal],
    353: <PokemonMoveType>[PokemonMoveType.ghost],
    354: <PokemonMoveType>[PokemonMoveType.ghost],
    355: <PokemonMoveType>[PokemonMoveType.ghost],
    356: <PokemonMoveType>[PokemonMoveType.ghost],
    357: <PokemonMoveType>[PokemonMoveType.grass, PokemonMoveType.flying],
    358: <PokemonMoveType>[PokemonMoveType.psychic],
    359: <PokemonMoveType>[PokemonMoveType.dark],
    360: <PokemonMoveType>[PokemonMoveType.psychic],
    361: <PokemonMoveType>[PokemonMoveType.ice],
    362: <PokemonMoveType>[PokemonMoveType.ice],
    363: <PokemonMoveType>[PokemonMoveType.ice, PokemonMoveType.water],
    364: <PokemonMoveType>[PokemonMoveType.ice, PokemonMoveType.water],
    365: <PokemonMoveType>[PokemonMoveType.ice, PokemonMoveType.water],
    366: <PokemonMoveType>[PokemonMoveType.water],
    367: <PokemonMoveType>[PokemonMoveType.water],
    368: <PokemonMoveType>[PokemonMoveType.water],
    369: <PokemonMoveType>[PokemonMoveType.water, PokemonMoveType.rock],
    370: <PokemonMoveType>[PokemonMoveType.water],
    371: <PokemonMoveType>[PokemonMoveType.dragon],
    372: <PokemonMoveType>[PokemonMoveType.dragon],
    373: <PokemonMoveType>[PokemonMoveType.dragon, PokemonMoveType.flying],
    374: <PokemonMoveType>[PokemonMoveType.steel, PokemonMoveType.psychic],
    375: <PokemonMoveType>[PokemonMoveType.steel, PokemonMoveType.psychic],
    376: <PokemonMoveType>[PokemonMoveType.steel, PokemonMoveType.psychic],
    377: <PokemonMoveType>[PokemonMoveType.rock],
    378: <PokemonMoveType>[PokemonMoveType.ice],
    379: <PokemonMoveType>[PokemonMoveType.steel],
    380: <PokemonMoveType>[PokemonMoveType.dragon, PokemonMoveType.psychic],
    381: <PokemonMoveType>[PokemonMoveType.dragon, PokemonMoveType.psychic],
    382: <PokemonMoveType>[PokemonMoveType.water],
    383: <PokemonMoveType>[PokemonMoveType.ground],
    384: <PokemonMoveType>[PokemonMoveType.dragon, PokemonMoveType.flying],
    385: <PokemonMoveType>[PokemonMoveType.steel, PokemonMoveType.psychic],
    386: <PokemonMoveType>[PokemonMoveType.psychic],
  };

  static const Map<int, List<PokemonMoveType>> _gen1Overrides =
      <int, List<PokemonMoveType>>{
    35: <PokemonMoveType>[PokemonMoveType.normal],
    36: <PokemonMoveType>[PokemonMoveType.normal],
    39: <PokemonMoveType>[PokemonMoveType.normal],
    40: <PokemonMoveType>[PokemonMoveType.normal],
    81: <PokemonMoveType>[PokemonMoveType.electric],
    82: <PokemonMoveType>[PokemonMoveType.electric],
    122: <PokemonMoveType>[PokemonMoveType.psychic],
    173: <PokemonMoveType>[PokemonMoveType.normal],
    174: <PokemonMoveType>[PokemonMoveType.normal],
    175: <PokemonMoveType>[PokemonMoveType.normal],
    176: <PokemonMoveType>[PokemonMoveType.normal, PokemonMoveType.flying],
    183: <PokemonMoveType>[PokemonMoveType.water],
    184: <PokemonMoveType>[PokemonMoveType.water],
    209: <PokemonMoveType>[PokemonMoveType.normal],
    210: <PokemonMoveType>[PokemonMoveType.normal],
    280: <PokemonMoveType>[PokemonMoveType.psychic],
    281: <PokemonMoveType>[PokemonMoveType.psychic],
    282: <PokemonMoveType>[PokemonMoveType.psychic],
    298: <PokemonMoveType>[PokemonMoveType.normal],
    303: <PokemonMoveType>[PokemonMoveType.steel],
  };

  static const Map<int, List<PokemonMoveType>> _gen2Overrides =
      <int, List<PokemonMoveType>>{
    35: <PokemonMoveType>[PokemonMoveType.normal],
    36: <PokemonMoveType>[PokemonMoveType.normal],
    39: <PokemonMoveType>[PokemonMoveType.normal],
    40: <PokemonMoveType>[PokemonMoveType.normal],
    122: <PokemonMoveType>[PokemonMoveType.psychic],
    173: <PokemonMoveType>[PokemonMoveType.normal],
    174: <PokemonMoveType>[PokemonMoveType.normal],
    175: <PokemonMoveType>[PokemonMoveType.normal],
    176: <PokemonMoveType>[PokemonMoveType.normal, PokemonMoveType.flying],
    183: <PokemonMoveType>[PokemonMoveType.water],
    184: <PokemonMoveType>[PokemonMoveType.water],
    209: <PokemonMoveType>[PokemonMoveType.normal],
    210: <PokemonMoveType>[PokemonMoveType.normal],
    280: <PokemonMoveType>[PokemonMoveType.psychic],
    281: <PokemonMoveType>[PokemonMoveType.psychic],
    282: <PokemonMoveType>[PokemonMoveType.psychic],
    298: <PokemonMoveType>[PokemonMoveType.normal],
    303: <PokemonMoveType>[PokemonMoveType.steel],
  };

  static const Map<int, List<PokemonMoveType>> _gen3Overrides =
      <int, List<PokemonMoveType>>{
    35: <PokemonMoveType>[PokemonMoveType.normal],
    36: <PokemonMoveType>[PokemonMoveType.normal],
    39: <PokemonMoveType>[PokemonMoveType.normal],
    40: <PokemonMoveType>[PokemonMoveType.normal],
    122: <PokemonMoveType>[PokemonMoveType.psychic],
    173: <PokemonMoveType>[PokemonMoveType.normal],
    174: <PokemonMoveType>[PokemonMoveType.normal],
    175: <PokemonMoveType>[PokemonMoveType.normal],
    176: <PokemonMoveType>[PokemonMoveType.normal, PokemonMoveType.flying],
    183: <PokemonMoveType>[PokemonMoveType.water],
    184: <PokemonMoveType>[PokemonMoveType.water],
    209: <PokemonMoveType>[PokemonMoveType.normal],
    210: <PokemonMoveType>[PokemonMoveType.normal],
    280: <PokemonMoveType>[PokemonMoveType.psychic],
    281: <PokemonMoveType>[PokemonMoveType.psychic],
    282: <PokemonMoveType>[PokemonMoveType.psychic],
    298: <PokemonMoveType>[PokemonMoveType.normal],
    303: <PokemonMoveType>[PokemonMoveType.steel],
  };
}
