import '../models/pokemon_game_profile.dart';
import '../models/pokemon_location.dart';
import 'locations/gen2/crystal_locations.g.dart';
import 'locations/gen3/emerald_locations.dart';
import 'locations/gen3/fire_red_leaf_green_locations.dart';
import 'locations/gen4/heart_gold_soul_silver_locations.dart';
import 'locations/gen4/platinum_locations.dart';
import 'locations/gen5/black_white_locations.dart';
import 'locations/gen5/black2_white2_locations.dart';

export '../models/pokemon_location.dart';

class PokemonDecoder {
  static String decodeText(List<int> bytes) {
    final out = StringBuffer();
    for (final value in bytes) {
      if (value == 0x50 || value == 0x00) break;
      final character = _characters[value];
      if (character != null) out.write(character);
    }
    return out.toString().trim();
  }

  /// Decodifica la tabla de caracteres occidental usada por Gen III.
  static String decodeGen3Text(List<int> bytes) {
    final StringBuffer out = StringBuffer();
    for (final int value in bytes) {
      if (value == 0xFF) break;
      if (value == 0x00) {
        out.write(' ');
      } else if (value >= 0xA1 && value <= 0xAA) {
        out.writeCharCode(0x30 + value - 0xA1);
      } else if (value >= 0xBB && value <= 0xD4) {
        out.writeCharCode(0x41 + value - 0xBB);
      } else if (value >= 0xD5 && value <= 0xEE) {
        out.writeCharCode(0x61 + value - 0xD5);
      } else {
        const Map<int, String> punctuation = <int, String>{
          0xAB: '!',
          0xAC: '?',
          0xAD: '.',
          0xAE: '-',
          0xB4: "'",
          0xB5: '♂',
          0xB6: '♀',
        };
        final String? character = punctuation[value];
        if (character != null) out.write(character);
      }
    }
    return out.toString().trim();
  }

  static int decodeBcd(List<int> bytes) {
    int result = 0;
    for (final byte in bytes) {
      final high = (byte >> 4) & 0x0f;
      final low = byte & 0x0f;
      if (high > 9 || low > 9) return -1;
      result = result * 100 + high * 10 + low;
    }
    return result;
  }

  /// Decodifica un entero binario sin signo almacenado en big-endian.
  /// Gen II guarda el dinero como tres bytes binarios, por ejemplo
  /// 00 0B B8 = 3000.
  static int decodeUnsignedBigEndian(List<int> bytes) {
    int result = 0;
    for (final int byte in bytes) {
      result = (result << 8) | (byte & 0xFF);
    }
    return result;
  }

  static int normalizeGen2JohtoBadges(int rawBadges) =>
      (rawBadges & ~0x30) |
      ((rawBadges & 0x10) << 1) |
      ((rawBadges & 0x20) >> 1);

  static int countBits(List<int> bytes) {
    int count = 0;
    for (int value in bytes) {
      while (value != 0) {
        count += value & 1;
        value >>= 1;
      }
    }
    return count;
  }

  static int dexId(PokemonGameProfile profile, int species) =>
      profile.isGen2 || profile.isGen4 || profile.isGen5
      ? species
      : (_gen1InternalToDex[species] ?? 0);

  static String pokemonName(int dexId) =>
      dexId > 0 && dexId < _names.length ? _names[dexId] : 'Pokémon #$dexId';

  static bool isGen2Shiny(int attackDefense, int speedSpecial) {
    final attack = (attackDefense >> 4) & 0x0f;
    final defense = attackDefense & 0x0f;
    final speed = (speedSpecial >> 4) & 0x0f;
    final special = speedSpecial & 0x0f;
    const shinyAttack = <int>{2, 3, 6, 7, 10, 11, 14, 15};
    return shinyAttack.contains(attack) &&
        defense == 10 &&
        speed == 10 &&
        special == 10;
  }

  static String mapName(PokemonGameProfile profile, int mapId) {
    final PokemonLocation? location = locationFor(profile, mapId);
    if (location != null) return location.name;
    if (profile.isGen3) {
      final String group = ((mapId >> 8) & 0xFF).toString().padLeft(2, '0');
      final String map = (mapId & 0xFF).toString().padLeft(2, '0');
      return 'Mapa $group:$map';
    }
    if (profile.isGen4 || profile.isGen5) return 'Zona $mapId';
    if (profile.isGen2) {
      return 'Mapa ${((mapId >> 8) & 0xff).toString().padLeft(2, '0')}:${(mapId & 0xff).toString().padLeft(2, '0')}';
    }
    return 'Mapa 0x${mapId.toRadixString(16).padLeft(2, '0').toUpperCase()}';
  }

  /// Devuelve la ubicación (nombre + tipo) para el mapa actual, usando la
  /// tabla propia de la versión del juego. Cada versión tiene su tabla
  /// separada: nunca se comparte una tabla entre versiones distintas,
  /// aunque hoy algunas contengan las mismas entradas conocidas.
  static PokemonLocation? locationFor(PokemonGameProfile profile, int mapId) {
    switch (profile.version) {
      case PokemonGameVersion.redBlue:
        return _redBlueLocations[mapId];
      case PokemonGameVersion.yellow:
        return _yellowLocations[mapId];
      case PokemonGameVersion.gold:
        return _goldLocations[mapId];
      case PokemonGameVersion.silver:
        return _silverLocations[mapId];
      case PokemonGameVersion.crystal:
        return generatedCrystalLocations[mapId];
      case PokemonGameVersion.ruby:
      case PokemonGameVersion.sapphire:
      case PokemonGameVersion.emerald:
        return emeraldLocations[mapId];
      case PokemonGameVersion.fireRed:
      case PokemonGameVersion.leafGreen:
        return fireRedLeafGreenLocations[mapId];
      case PokemonGameVersion.diamond:
      case PokemonGameVersion.pearl:
      case PokemonGameVersion.platinum:
        return platinumLocations[mapId];
      case PokemonGameVersion.heartGold:
      case PokemonGameVersion.soulSilver:
        return heartGoldSoulSilverLocations[mapId];
      case PokemonGameVersion.black:
      case PokemonGameVersion.white:
        return blackWhiteLocations[mapId];
      case PokemonGameVersion.black2:
      case PokemonGameVersion.white2:
        return black2White2Locations[mapId];
      case PokemonGameVersion.unsupported:
        return null;
    }
  }

  static String badgeName(PokemonGameProfile profile, int index) {
    final isHgss = profile.version == PokemonGameVersion.heartGold ||
        profile.version == PokemonGameVersion.soulSilver;
    final isB2W2 = profile.version == PokemonGameVersion.black2 ||
        profile.version == PokemonGameVersion.white2;
    final names = profile.isGen5
        ? (isB2W2 ? _unovaBlack2White2Badges : _unovaBlackWhiteBadges)
        : profile.isGen4
        ? (isHgss
              ? _gen2Badges
              : profile.version == PokemonGameVersion.platinum
              ? _sinnohPlatinumBadges
              : _sinnohBadges)
        : profile.version == PokemonGameVersion.fireRed ||
            profile.version == PokemonGameVersion.leafGreen
        ? _kantoBadges
        : profile.isGen3
        ? _gen3Badges
        : (profile.isGen2 ? _gen2Badges : _gen1Badges);
    return index >= 0 && index < names.length ? names[index] : 'Medalla';
  }

  static const _gen1Badges = <String>[
    'Medalla Roca',
    'Medalla Cascada',
    'Medalla Trueno',
    'Medalla Arcoíris',
    'Medalla Alma',
    'Medalla Pantano',
    'Medalla Volcán',
    'Medalla Tierra',
  ];
  static const _unovaBlackWhiteBadges = <String>[
    'Medalla Trío',
    'Medalla Base',
    'Medalla Élitro',
    'Medalla Voltio',
    'Medalla Temblor',
    'Medalla Jet',
    'Medalla Candelero',
    'Medalla Leyenda',
  ];
  static const _unovaBlack2White2Badges = <String>[
    'Medalla Base',
    'Medalla Tóxica',
    'Medalla Élitro',
    'Medalla Voltio',
    'Medalla Temblor',
    'Medalla Jet',
    'Medalla Leyenda',
    'Medalla Ola',
  ];
  static const _gen2Badges = <String>[
    'Medalla Céfiro',
    'Medalla Colmena',
    'Medalla Planicie',
    'Medalla Niebla',
    'Medalla Tormenta',
    'Medalla Mineral',
    'Medalla Glaciar',
    'Medalla Dragón',
    'Medalla Trueno',
    'Medalla Pantano',
    'Medalla Arcoíris',
    'Medalla Alma',
    'Medalla Cascada',
    'Medalla Roca',
    'Medalla Volcán',
    'Medalla Tierra',
  ];
  static const _gen3Badges = <String>[
    'Medalla Piedra',
    'Medalla Puño',
    'Medalla Dinamo',
    'Medalla Calor',
    'Medalla Equilibrio',
    'Medalla Pluma',
    'Medalla Mente',
    'Medalla Lluvia',
  ];
  static const _kantoBadges = <String>[
    'Medalla Roca',
    'Medalla Cascada',
    'Medalla Trueno',
    'Medalla Arcoíris',
    'Medalla Alma',
    'Medalla Pantano',
    'Medalla Volcán',
    'Medalla Tierra',
  ];
  static const _sinnohBadges = <String>[
    'Medalla Lignito',
    'Medalla Bosque',
    'Medalla Adoquín',
    'Medalla Ciénaga',
    'Medalla Reliquia',
    'Medalla Mina',
    'Medalla Carámbano',
    'Medalla Faro',
  ];
  static const _sinnohPlatinumBadges = <String>[
    'Medalla Lignito',
    'Medalla Bosque',
    'Medalla Reliquia',
    'Medalla Adoquín',
    'Medalla Ciénaga',
    'Medalla Mina',
    'Medalla Carámbano',
    'Medalla Faro',
  ];

  static const Map<int, String> _characters = <int, String>{
    0x80: 'A',
    0x81: 'B',
    0x82: 'C',
    0x83: 'D',
    0x84: 'E',
    0x85: 'F',
    0x86: 'G',
    0x87: 'H',
    0x88: 'I',
    0x89: 'J',
    0x8A: 'K',
    0x8B: 'L',
    0x8C: 'M',
    0x8D: 'N',
    0x8E: 'O',
    0x8F: 'P',
    0x90: 'Q',
    0x91: 'R',
    0x92: 'S',
    0x93: 'T',
    0x94: 'U',
    0x95: 'V',
    0x96: 'W',
    0x97: 'X',
    0x98: 'Y',
    0x99: 'Z',
    0xA0: 'a',
    0xA1: 'b',
    0xA2: 'c',
    0xA3: 'd',
    0xA4: 'e',
    0xA5: 'f',
    0xA6: 'g',
    0xA7: 'h',
    0xA8: 'i',
    0xA9: 'j',
    0xAA: 'k',
    0xAB: 'l',
    0xAC: 'm',
    0xAD: 'n',
    0xAE: 'o',
    0xAF: 'p',
    0xB0: 'q',
    0xB1: 'r',
    0xB2: 's',
    0xB3: 't',
    0xB4: 'u',
    0xB5: 'v',
    0xB6: 'w',
    0xB7: 'x',
    0xB8: 'y',
    0xB9: 'z',
    0xE0: "'",
    0xE3: '-',
    0xE6: '?',
    0xE7: '!',
    0xE8: '.',
    0xEF: '♂',
    0xF5: '♀',
    0xF6: '0',
    0xF7: '1',
    0xF8: '2',
    0xF9: '3',
    0xFA: '4',
    0xFB: '5',
    0xFC: '6',
    0xFD: '7',
    0xFE: '8',
    0xFF: '9',
    0x7F: ' ',
  };

  static const Map<int, int> _gen1InternalToDex = <int, int>{
    1: 112,
    2: 115,
    3: 32,
    4: 35,
    5: 21,
    6: 100,
    7: 34,
    8: 80,
    9: 2,
    10: 103,
    11: 108,
    12: 102,
    13: 88,
    14: 94,
    15: 29,
    16: 31,
    17: 104,
    18: 111,
    19: 131,
    20: 59,
    21: 151,
    22: 130,
    23: 90,
    24: 72,
    25: 92,
    26: 123,
    27: 120,
    28: 9,
    29: 127,
    30: 114,
    33: 58,
    34: 95,
    35: 22,
    36: 16,
    37: 79,
    38: 64,
    39: 75,
    40: 113,
    41: 67,
    42: 122,
    43: 106,
    44: 107,
    45: 24,
    46: 47,
    47: 54,
    48: 96,
    49: 76,
    51: 126,
    53: 125,
    54: 82,
    55: 109,
    57: 56,
    58: 86,
    59: 50,
    60: 128,
    64: 83,
    65: 48,
    66: 149,
    70: 84,
    71: 60,
    72: 124,
    73: 146,
    74: 144,
    75: 145,
    76: 132,
    77: 52,
    78: 98,
    82: 37,
    83: 38,
    84: 25,
    85: 26,
    88: 147,
    89: 148,
    90: 140,
    91: 141,
    92: 116,
    93: 117,
    96: 27,
    97: 28,
    98: 138,
    99: 139,
    100: 39,
    101: 40,
    102: 133,
    103: 136,
    104: 135,
    105: 134,
    106: 66,
    107: 41,
    108: 23,
    109: 46,
    110: 61,
    111: 62,
    112: 13,
    113: 14,
    114: 15,
    116: 85,
    117: 57,
    118: 51,
    119: 49,
    120: 87,
    123: 10,
    124: 11,
    125: 12,
    126: 68,
    128: 55,
    129: 97,
    130: 42,
    131: 150,
    132: 143,
    133: 129,
    136: 89,
    138: 99,
    139: 91,
    141: 101,
    142: 36,
    143: 110,
    144: 53,
    145: 105,
    147: 93,
    148: 63,
    149: 65,
    150: 17,
    151: 18,
    152: 121,
    153: 1,
    154: 3,
    155: 73,
    157: 118,
    158: 119,
    163: 77,
    164: 78,
    165: 19,
    166: 20,
    167: 33,
    168: 30,
    169: 74,
    170: 137,
    171: 142,
    173: 81,
    176: 4,
    177: 7,
    178: 5,
    179: 8,
    180: 6,
    185: 43,
    186: 44,
    187: 45,
    188: 69,
    189: 70,
    190: 71,
  };

  static const List<String> _names = <String>[
    '',
    'Bulbasaur',
    'Ivysaur',
    'Venusaur',
    'Charmander',
    'Charmeleon',
    'Charizard',
    'Squirtle',
    'Wartortle',
    'Blastoise',
    'Caterpie',
    'Metapod',
    'Butterfree',
    'Weedle',
    'Kakuna',
    'Beedrill',
    'Pidgey',
    'Pidgeotto',
    'Pidgeot',
    'Rattata',
    'Raticate',
    'Spearow',
    'Fearow',
    'Ekans',
    'Arbok',
    'Pikachu',
    'Raichu',
    'Sandshrew',
    'Sandslash',
    'Nidoran♀',
    'Nidorina',
    'Nidoqueen',
    'Nidoran♂',
    'Nidorino',
    'Nidoking',
    'Clefairy',
    'Clefable',
    'Vulpix',
    'Ninetales',
    'Jigglypuff',
    'Wigglytuff',
    'Zubat',
    'Golbat',
    'Oddish',
    'Gloom',
    'Vileplume',
    'Paras',
    'Parasect',
    'Venonat',
    'Venomoth',
    'Diglett',
    'Dugtrio',
    'Meowth',
    'Persian',
    'Psyduck',
    'Golduck',
    'Mankey',
    'Primeape',
    'Growlithe',
    'Arcanine',
    'Poliwag',
    'Poliwhirl',
    'Poliwrath',
    'Abra',
    'Kadabra',
    'Alakazam',
    'Machop',
    'Machoke',
    'Machamp',
    'Bellsprout',
    'Weepinbell',
    'Victreebel',
    'Tentacool',
    'Tentacruel',
    'Geodude',
    'Graveler',
    'Golem',
    'Ponyta',
    'Rapidash',
    'Slowpoke',
    'Slowbro',
    'Magnemite',
    'Magneton',
    'Farfetch’d',
    'Doduo',
    'Dodrio',
    'Seel',
    'Dewgong',
    'Grimer',
    'Muk',
    'Shellder',
    'Cloyster',
    'Gastly',
    'Haunter',
    'Gengar',
    'Onix',
    'Drowzee',
    'Hypno',
    'Krabby',
    'Kingler',
    'Voltorb',
    'Electrode',
    'Exeggcute',
    'Exeggutor',
    'Cubone',
    'Marowak',
    'Hitmonlee',
    'Hitmonchan',
    'Lickitung',
    'Koffing',
    'Weezing',
    'Rhyhorn',
    'Rhydon',
    'Chansey',
    'Tangela',
    'Kangaskhan',
    'Horsea',
    'Seadra',
    'Goldeen',
    'Seaking',
    'Staryu',
    'Starmie',
    'Mr. Mime',
    'Scyther',
    'Jynx',
    'Electabuzz',
    'Magmar',
    'Pinsir',
    'Tauros',
    'Magikarp',
    'Gyarados',
    'Lapras',
    'Ditto',
    'Eevee',
    'Vaporeon',
    'Jolteon',
    'Flareon',
    'Porygon',
    'Omanyte',
    'Omastar',
    'Kabuto',
    'Kabutops',
    'Aerodactyl',
    'Snorlax',
    'Articuno',
    'Zapdos',
    'Moltres',
    'Dratini',
    'Dragonair',
    'Dragonite',
    'Mewtwo',
    'Mew',
    'Chikorita',
    'Bayleef',
    'Meganium',
    'Cyndaquil',
    'Quilava',
    'Typhlosion',
    'Totodile',
    'Croconaw',
    'Feraligatr',
    'Sentret',
    'Furret',
    'Hoothoot',
    'Noctowl',
    'Ledyba',
    'Ledian',
    'Spinarak',
    'Ariados',
    'Crobat',
    'Chinchou',
    'Lanturn',
    'Pichu',
    'Cleffa',
    'Igglybuff',
    'Togepi',
    'Togetic',
    'Natu',
    'Xatu',
    'Mareep',
    'Flaaffy',
    'Ampharos',
    'Bellossom',
    'Marill',
    'Azumarill',
    'Sudowoodo',
    'Politoed',
    'Hoppip',
    'Skiploom',
    'Jumpluff',
    'Aipom',
    'Sunkern',
    'Sunflora',
    'Yanma',
    'Wooper',
    'Quagsire',
    'Espeon',
    'Umbreon',
    'Murkrow',
    'Slowking',
    'Misdreavus',
    'Unown',
    'Wobbuffet',
    'Girafarig',
    'Pineco',
    'Forretress',
    'Dunsparce',
    'Gligar',
    'Steelix',
    'Snubbull',
    'Granbull',
    'Qwilfish',
    'Scizor',
    'Shuckle',
    'Heracross',
    'Sneasel',
    'Teddiursa',
    'Ursaring',
    'Slugma',
    'Magcargo',
    'Swinub',
    'Piloswine',
    'Corsola',
    'Remoraid',
    'Octillery',
    'Delibird',
    'Mantine',
    'Skarmory',
    'Houndour',
    'Houndoom',
    'Kingdra',
    'Phanpy',
    'Donphan',
    'Porygon2',
    'Stantler',
    'Smeargle',
    'Tyrogue',
    'Hitmontop',
    'Smoochum',
    'Elekid',
    'Magby',
    'Miltank',
    'Blissey',
    'Raikou',
    'Entei',
    'Suicune',
    'Larvitar',
    'Pupitar',
    'Tyranitar',
    'Lugia',
    'Ho-Oh',
    'Celebi',
    'Treecko',
    'Grovyle',
    'Sceptile',
    'Torchic',
    'Combusken',
    'Blaziken',
    'Mudkip',
    'Marshtomp',
    'Swampert',
    'Poochyena',
    'Mightyena',
    'Zigzagoon',
    'Linoone',
    'Wurmple',
    'Silcoon',
    'Beautifly',
    'Cascoon',
    'Dustox',
    'Lotad',
    'Lombre',
    'Ludicolo',
    'Seedot',
    'Nuzleaf',
    'Shiftry',
    'Taillow',
    'Swellow',
    'Wingull',
    'Pelipper',
    'Ralts',
    'Kirlia',
    'Gardevoir',
    'Surskit',
    'Masquerain',
    'Shroomish',
    'Breloom',
    'Slakoth',
    'Vigoroth',
    'Slaking',
    'Nincada',
    'Ninjask',
    'Shedinja',
    'Whismur',
    'Loudred',
    'Exploud',
    'Makuhita',
    'Hariyama',
    'Azurill',
    'Nosepass',
    'Skitty',
    'Delcatty',
    'Sableye',
    'Mawile',
    'Aron',
    'Lairon',
    'Aggron',
    'Meditite',
    'Medicham',
    'Electrike',
    'Manectric',
    'Plusle',
    'Minun',
    'Volbeat',
    'Illumise',
    'Roselia',
    'Gulpin',
    'Swalot',
    'Carvanha',
    'Sharpedo',
    'Wailmer',
    'Wailord',
    'Numel',
    'Camerupt',
    'Torkoal',
    'Spoink',
    'Grumpig',
    'Spinda',
    'Trapinch',
    'Vibrava',
    'Flygon',
    'Cacnea',
    'Cacturne',
    'Swablu',
    'Altaria',
    'Zangoose',
    'Seviper',
    'Lunatone',
    'Solrock',
    'Barboach',
    'Whiscash',
    'Corphish',
    'Crawdaunt',
    'Baltoy',
    'Claydol',
    'Lileep',
    'Cradily',
    'Anorith',
    'Armaldo',
    'Feebas',
    'Milotic',
    'Castform',
    'Kecleon',
    'Shuppet',
    'Banette',
    'Duskull',
    'Dusclops',
    'Tropius',
    'Chimecho',
    'Absol',
    'Wynaut',
    'Snorunt',
    'Glalie',
    'Spheal',
    'Sealeo',
    'Walrein',
    'Clamperl',
    'Huntail',
    'Gorebyss',
    'Relicanth',
    'Luvdisc',
    'Bagon',
    'Shelgon',
    'Salamence',
    'Beldum',
    'Metang',
    'Metagross',
    'Regirock',
    'Regice',
    'Registeel',
    'Latias',
    'Latios',
    'Kyogre',
    'Groudon',
    'Rayquaza',
    'Jirachi',
    'Deoxys',
    'Turtwig',
    'Grotle',
    'Torterra',
    'Chimchar',
    'Monferno',
    'Infernape',
    'Piplup',
    'Prinplup',
    'Empoleon',
    'Starly',
    'Staravia',
    'Staraptor',
    'Bidoof',
    'Bibarel',
    'Kricketot',
    'Kricketune',
    'Shinx',
    'Luxio',
    'Luxray',
    'Budew',
    'Roserade',
    'Cranidos',
    'Rampardos',
    'Shieldon',
    'Bastiodon',
    'Burmy',
    'Wormadam',
    'Mothim',
    'Combee',
    'Vespiquen',
    'Pachirisu',
    'Buizel',
    'Floatzel',
    'Cherubi',
    'Cherrim',
    'Shellos',
    'Gastrodon',
    'Ambipom',
    'Drifloon',
    'Drifblim',
    'Buneary',
    'Lopunny',
    'Mismagius',
    'Honchkrow',
    'Glameow',
    'Purugly',
    'Chingling',
    'Stunky',
    'Skuntank',
    'Bronzor',
    'Bronzong',
    'Bonsly',
    'Mime Jr.',
    'Happiny',
    'Chatot',
    'Spiritomb',
    'Gible',
    'Gabite',
    'Garchomp',
    'Munchlax',
    'Riolu',
    'Lucario',
    'Hippopotas',
    'Hippowdon',
    'Skorupi',
    'Drapion',
    'Croagunk',
    'Toxicroak',
    'Carnivine',
    'Finneon',
    'Lumineon',
    'Mantyke',
    'Snover',
    'Abomasnow',
    'Weavile',
    'Magnezone',
    'Lickilicky',
    'Rhyperior',
    'Tangrowth',
    'Electivire',
    'Magmortar',
    'Togekiss',
    'Yanmega',
    'Leafeon',
    'Glaceon',
    'Gliscor',
    'Mamoswine',
    'Porygon-Z',
    'Gallade',
    'Probopass',
    'Dusknoir',
    'Froslass',
    'Rotom',
    'Uxie',
    'Mesprit',
    'Azelf',
    'Dialga',
    'Palkia',
    'Heatran',
    'Regigigas',
    'Giratina',
    'Cresselia',
    'Phione',
    'Manaphy',
    'Darkrai',
    'Shaymin',
    'Arceus',
    'Victini',
    'Snivy',
    'Servine',
    'Serperior',
    'Tepig',
    'Pignite',
    'Emboar',
    'Oshawott',
    'Dewott',
    'Samurott',
    'Patrat',
    'Watchog',
    'Lillipup',
    'Herdier',
    'Stoutland',
    'Purrloin',
    'Liepard',
    'Pansage',
    'Simisage',
    'Pansear',
    'Simisear',
    'Panpour',
    'Simipour',
    'Munna',
    'Musharna',
    'Pidove',
    'Tranquill',
    'Unfezant',
    'Blitzle',
    'Zebstrika',
    'Roggenrola',
    'Boldore',
    'Gigalith',
    'Woobat',
    'Swoobat',
    'Drilbur',
    'Excadrill',
    'Audino',
    'Timburr',
    'Gurdurr',
    'Conkeldurr',
    'Tympole',
    'Palpitoad',
    'Seismitoad',
    'Throh',
    'Sawk',
    'Sewaddle',
    'Swadloon',
    'Leavanny',
    'Venipede',
    'Whirlipede',
    'Scolipede',
    'Cottonee',
    'Whimsicott',
    'Petilil',
    'Lilligant',
    'Basculin',
    'Sandile',
    'Krokorok',
    'Krookodile',
    'Darumaka',
    'Darmanitan',
    'Maractus',
    'Dwebble',
    'Crustle',
    'Scraggy',
    'Scrafty',
    'Sigilyph',
    'Yamask',
    'Cofagrigus',
    'Tirtouga',
    'Carracosta',
    'Archen',
    'Archeops',
    'Trubbish',
    'Garbodor',
    'Zorua',
    'Zoroark',
    'Minccino',
    'Cinccino',
    'Gothita',
    'Gothorita',
    'Gothitelle',
    'Solosis',
    'Duosion',
    'Reuniclus',
    'Ducklett',
    'Swanna',
    'Vanillite',
    'Vanillish',
    'Vanilluxe',
    'Deerling',
    'Sawsbuck',
    'Emolga',
    'Karrablast',
    'Escavalier',
    'Foongus',
    'Amoonguss',
    'Frillish',
    'Jellicent',
    'Alomomola',
    'Joltik',
    'Galvantula',
    'Ferroseed',
    'Ferrothorn',
    'Klink',
    'Klang',
    'Klinklang',
    'Tynamo',
    'Eelektrik',
    'Eelektross',
    'Elgyem',
    'Beheeyem',
    'Litwick',
    'Lampent',
    'Chandelure',
    'Axew',
    'Fraxure',
    'Haxorus',
    'Cubchoo',
    'Beartic',
    'Cryogonal',
    'Shelmet',
    'Accelgor',
    'Stunfisk',
    'Mienfoo',
    'Mienshao',
    'Druddigon',
    'Golett',
    'Golurk',
    'Pawniard',
    'Bisharp',
    'Bouffalant',
    'Rufflet',
    'Braviary',
    'Vullaby',
    'Mandibuzz',
    'Heatmor',
    'Durant',
    'Deino',
    'Zweilous',
    'Hydreigon',
    'Larvesta',
    'Volcarona',
    'Cobalion',
    'Terrakion',
    'Virizion',
    'Tornadus',
    'Thundurus',
    'Reshiram',
    'Zekrom',
    'Landorus',
    'Kyurem',
    'Keldeo',
    'Meloetta',
    'Genesect',
  ];

  // --- Fase 4.1A: tabla de ubicaciones propia por versión de juego. ---
  // Cada versión tiene su propia tabla, aunque el contenido inicial de
  // algunas coincida (p. ej. Yellow reutiliza el mismo banco de mapas base
  // que Red/Blue, y Silver el mismo que Gold). Están separadas a propósito:
  // si se detecta una diferencia real jugando, se corrige la tabla de esa
  // versión sin arriesgar romper las demás.

  static const Map<int, PokemonLocation> _redBlueLocations =
      <int, PokemonLocation>{
        0x00: PokemonLocation('Pueblo Paleta', PokemonLocationKind.city),
        0x01: PokemonLocation('Ciudad Verde', PokemonLocationKind.city),
        0x02: PokemonLocation('Ciudad Plateada', PokemonLocationKind.city),
        0x03: PokemonLocation('Ciudad Celeste', PokemonLocationKind.city),
        0x04: PokemonLocation('Pueblo Lavanda', PokemonLocationKind.city),
        0x05: PokemonLocation('Ciudad Carmín', PokemonLocationKind.city),
        0x06: PokemonLocation('Ciudad Azulona', PokemonLocationKind.city),
        0x07: PokemonLocation('Ciudad Fucsia', PokemonLocationKind.city),
        0x08: PokemonLocation('Isla Canela', PokemonLocationKind.city),
        0x09: PokemonLocation('Meseta Añil', PokemonLocationKind.league),
        0x0A: PokemonLocation('Ciudad Azafrán', PokemonLocationKind.city),
        0x28: PokemonLocation(
          'Laboratorio del Profesor Oak',
          PokemonLocationKind.other,
        ),
        0x0C: PokemonLocation('Ruta 1', PokemonLocationKind.route),
        0x0D: PokemonLocation('Ruta 2', PokemonLocationKind.route),
        0x0E: PokemonLocation('Ruta 3', PokemonLocationKind.route),
        0x0F: PokemonLocation('Ruta 4', PokemonLocationKind.route),
        0x10: PokemonLocation('Ruta 5', PokemonLocationKind.route),
        0x11: PokemonLocation('Ruta 6', PokemonLocationKind.route),
        0x12: PokemonLocation('Ruta 7', PokemonLocationKind.route),
        0x13: PokemonLocation('Ruta 8', PokemonLocationKind.route),
        0x14: PokemonLocation('Ruta 9', PokemonLocationKind.route),
        0x15: PokemonLocation('Ruta 10', PokemonLocationKind.route),
        0x16: PokemonLocation('Ruta 11', PokemonLocationKind.route),
        0x17: PokemonLocation('Ruta 12', PokemonLocationKind.route),
        0x18: PokemonLocation('Ruta 13', PokemonLocationKind.route),
        0x19: PokemonLocation('Ruta 14', PokemonLocationKind.route),
        0x1A: PokemonLocation('Ruta 15', PokemonLocationKind.route),
        0x1B: PokemonLocation('Ruta 16', PokemonLocationKind.route),
        0x1C: PokemonLocation('Ruta 17', PokemonLocationKind.route),
        0x1D: PokemonLocation('Ruta 18', PokemonLocationKind.route),
        0x1E: PokemonLocation('Ruta 19', PokemonLocationKind.route),
        0x1F: PokemonLocation('Ruta 20', PokemonLocationKind.route),
        0x20: PokemonLocation('Ruta 21', PokemonLocationKind.route),
        0x21: PokemonLocation('Ruta 22', PokemonLocationKind.route),
        0x22: PokemonLocation('Ruta 23', PokemonLocationKind.route),
        0x23: PokemonLocation('Ruta 24', PokemonLocationKind.route),
        0x24: PokemonLocation('Ruta 25', PokemonLocationKind.route),
      };

  // Yellow: sin verificación propia todavía. Se deja como tabla
  // independiente (no un alias de Red/Blue) para poder corregirla si se
  // confirman diferencias sin tocar la tabla de Red/Blue.
  static const Map<int, PokemonLocation> _yellowLocations =
      <int, PokemonLocation>{
        0x00: PokemonLocation('Pueblo Paleta', PokemonLocationKind.city),
        0x01: PokemonLocation('Ciudad Verde', PokemonLocationKind.city),
        0x02: PokemonLocation('Ciudad Plateada', PokemonLocationKind.city),
        0x03: PokemonLocation('Ciudad Celeste', PokemonLocationKind.city),
        0x04: PokemonLocation('Pueblo Lavanda', PokemonLocationKind.city),
        0x05: PokemonLocation('Ciudad Carmín', PokemonLocationKind.city),
        0x06: PokemonLocation('Ciudad Azulona', PokemonLocationKind.city),
        0x07: PokemonLocation('Ciudad Fucsia', PokemonLocationKind.city),
        0x08: PokemonLocation('Isla Canela', PokemonLocationKind.city),
        0x09: PokemonLocation('Meseta Añil', PokemonLocationKind.league),
        0x0A: PokemonLocation('Ciudad Azafrán', PokemonLocationKind.city),
        0x28: PokemonLocation(
          'Laboratorio del Profesor Oak',
          PokemonLocationKind.other,
        ),
        0x0C: PokemonLocation('Ruta 1', PokemonLocationKind.route),
        0x0D: PokemonLocation('Ruta 2', PokemonLocationKind.route),
        0x0E: PokemonLocation('Ruta 3', PokemonLocationKind.route),
        0x0F: PokemonLocation('Ruta 4', PokemonLocationKind.route),
        0x10: PokemonLocation('Ruta 5', PokemonLocationKind.route),
        0x11: PokemonLocation('Ruta 6', PokemonLocationKind.route),
        0x12: PokemonLocation('Ruta 7', PokemonLocationKind.route),
        0x13: PokemonLocation('Ruta 8', PokemonLocationKind.route),
        0x14: PokemonLocation('Ruta 9', PokemonLocationKind.route),
        0x15: PokemonLocation('Ruta 10', PokemonLocationKind.route),
        0x16: PokemonLocation('Ruta 11', PokemonLocationKind.route),
        0x17: PokemonLocation('Ruta 12', PokemonLocationKind.route),
        0x18: PokemonLocation('Ruta 13', PokemonLocationKind.route),
        0x19: PokemonLocation('Ruta 14', PokemonLocationKind.route),
        0x1A: PokemonLocation('Ruta 15', PokemonLocationKind.route),
        0x1B: PokemonLocation('Ruta 16', PokemonLocationKind.route),
        0x1C: PokemonLocation('Ruta 17', PokemonLocationKind.route),
        0x1D: PokemonLocation('Ruta 18', PokemonLocationKind.route),
        0x1E: PokemonLocation('Ruta 19', PokemonLocationKind.route),
        0x1F: PokemonLocation('Ruta 20', PokemonLocationKind.route),
        0x20: PokemonLocation('Ruta 21', PokemonLocationKind.route),
        0x21: PokemonLocation('Ruta 22', PokemonLocationKind.route),
        0x22: PokemonLocation('Ruta 23', PokemonLocationKind.route),
        0x23: PokemonLocation('Ruta 24', PokemonLocationKind.route),
        0x24: PokemonLocation('Ruta 25', PokemonLocationKind.route),
      };

  // Claves grupo<<8 | mapa.
  static const Map<int, PokemonLocation> _goldLocations =
      <int, PokemonLocation>{
        0x1807: PokemonLocation('Pueblo Primavera', PokemonLocationKind.city),
        0x1801: PokemonLocation('Ciudad Cerezo', PokemonLocationKind.city),
        0x0A05: PokemonLocation('Ciudad Malva', PokemonLocationKind.city),
        0x0305: PokemonLocation('Pueblo Azalea', PokemonLocationKind.city),
        0x1205: PokemonLocation('Ciudad Trigal', PokemonLocationKind.city),
        0x0905: PokemonLocation('Ciudad Iris', PokemonLocationKind.city),
        0x0D05: PokemonLocation('Ciudad Olivo', PokemonLocationKind.city),
        0x0B05: PokemonLocation('Ciudad Orquídea', PokemonLocationKind.city),
        0x0F05: PokemonLocation('Pueblo Caoba', PokemonLocationKind.city),
        0x0E05: PokemonLocation('Ciudad Endrino', PokemonLocationKind.city),
        0x0105: PokemonLocation('Meseta Añil', PokemonLocationKind.league),
        0x1A05: PokemonLocation('Ciudad Verde', PokemonLocationKind.city),
        0x1705: PokemonLocation('Pueblo Paleta', PokemonLocationKind.city),
        0x1605: PokemonLocation('Ciudad Plateada', PokemonLocationKind.city),
        0x1905: PokemonLocation('Ciudad Celeste', PokemonLocationKind.city),
        0x1505: PokemonLocation('Ciudad Carmín', PokemonLocationKind.city),
        0x1405: PokemonLocation('Ciudad Azulona', PokemonLocationKind.city),
        0x1305: PokemonLocation('Ciudad Fucsia', PokemonLocationKind.city),
        0x1105: PokemonLocation('Pueblo Lavanda', PokemonLocationKind.city),
        0x1005: PokemonLocation('Ciudad Azafrán', PokemonLocationKind.city),
      };

  // Silver: mismo motor y banco de mapas base que Gold. Tabla separada por
  // si se confirma alguna diferencia real de IDs entre versiones.
  static const Map<int, PokemonLocation> _silverLocations =
      <int, PokemonLocation>{
        0x1807: PokemonLocation('Pueblo Primavera', PokemonLocationKind.city),
        0x1801: PokemonLocation('Ciudad Cerezo', PokemonLocationKind.city),
        0x0A05: PokemonLocation('Ciudad Malva', PokemonLocationKind.city),
        0x0305: PokemonLocation('Pueblo Azalea', PokemonLocationKind.city),
        0x1205: PokemonLocation('Ciudad Trigal', PokemonLocationKind.city),
        0x0905: PokemonLocation('Ciudad Iris', PokemonLocationKind.city),
        0x0D05: PokemonLocation('Ciudad Olivo', PokemonLocationKind.city),
        0x0B05: PokemonLocation('Ciudad Orquídea', PokemonLocationKind.city),
        0x0F05: PokemonLocation('Pueblo Caoba', PokemonLocationKind.city),
        0x0E05: PokemonLocation('Ciudad Endrino', PokemonLocationKind.city),
        0x0105: PokemonLocation('Meseta Añil', PokemonLocationKind.league),
        0x1A05: PokemonLocation('Ciudad Verde', PokemonLocationKind.city),
        0x1705: PokemonLocation('Pueblo Paleta', PokemonLocationKind.city),
        0x1605: PokemonLocation('Ciudad Plateada', PokemonLocationKind.city),
        0x1905: PokemonLocation('Ciudad Celeste', PokemonLocationKind.city),
        0x1505: PokemonLocation('Ciudad Carmín', PokemonLocationKind.city),
        0x1405: PokemonLocation('Ciudad Azulona', PokemonLocationKind.city),
        0x1305: PokemonLocation('Ciudad Fucsia', PokemonLocationKind.city),
        0x1105: PokemonLocation('Pueblo Lavanda', PokemonLocationKind.city),
        0x1005: PokemonLocation('Ciudad Azafrán', PokemonLocationKind.city),
      };
}

// Compatibilidad con código Gen I anterior.
class PokemonGen1Decoder {
  static String decodeText(List<int> bytes) => PokemonDecoder.decodeText(bytes);
  static String decodePlayerName(List<int> bytes) =>
      PokemonDecoder.decodeText(bytes);
  static bool isPlausibleText(List<int> bytes) =>
      PokemonDecoder.decodeText(bytes).isNotEmpty;
  static int decodeBcd(List<int> bytes) => PokemonDecoder.decodeBcd(bytes);
  static int countBits(List<int> bytes) => PokemonDecoder.countBits(bytes);
  static int pokedexIdFromInternal(int id) =>
      PokemonDecoder._gen1InternalToDex[id] ?? 0;
  static String pokemonName(int dexId) => PokemonDecoder.pokemonName(dexId);
  static String mapName(int mapId) =>
      PokemonDecoder._redBlueLocations[mapId]?.name ??
      'Mapa 0x${mapId.toRadixString(16).padLeft(2, '0').toUpperCase()}';
  static String badgeName(int index) =>
      index >= 0 && index < PokemonDecoder._gen1Badges.length
      ? PokemonDecoder._gen1Badges[index]
      : 'Medalla';
}
