import '../../../models/pokemon_location.dart';

/// Ubicaciones de HeartGold y SoulSilver indexadas por MapHeader.
/// Los interiores heredan el nombre de su área para mantener una ubicación
/// reconocible durante toda la exploración de Johto y Kanto.
const Map<int, PokemonLocation> heartGoldSoulSilverLocations =
    <int, PokemonLocation>{
  6: PokemonLocation('Camino Campana', PokemonLocationKind.city),
  7: PokemonLocation('Torre Quemada'),
  8: PokemonLocation('Ruinas Alfa'),
  9: PokemonLocation('Ruta 1', PokemonLocationKind.route),
  10: PokemonLocation('Ruta 2', PokemonLocationKind.route),
  11: PokemonLocation('Ruta 3', PokemonLocationKind.route),
  12: PokemonLocation('Ruta 4', PokemonLocationKind.route),
  13: PokemonLocation('Ruta 5', PokemonLocationKind.route),
  14: PokemonLocation('Ruta 6', PokemonLocationKind.route),
  15: PokemonLocation('Ruta 7', PokemonLocationKind.route),
  16: PokemonLocation('Ruta 8', PokemonLocationKind.route),
  17: PokemonLocation('Ruta 9', PokemonLocationKind.route),
  18: PokemonLocation('Ruta 10', PokemonLocationKind.route),
  19: PokemonLocation('Ruta 11', PokemonLocationKind.route),
  20: PokemonLocation('Ruta 12', PokemonLocationKind.route),
  21: PokemonLocation('Ruta 13', PokemonLocationKind.route),
  22: PokemonLocation('Ruta 14', PokemonLocationKind.route),
  23: PokemonLocation('Ruta 15', PokemonLocationKind.route),
  24: PokemonLocation('Ruta 16', PokemonLocationKind.route),
  25: PokemonLocation('Ruta 17', PokemonLocationKind.route),
  26: PokemonLocation('Ruta 18', PokemonLocationKind.route),
  27: PokemonLocation('Ruta 22', PokemonLocationKind.route),
  28: PokemonLocation('Ruta 24', PokemonLocationKind.route),
  29: PokemonLocation('Ruta 25', PokemonLocationKind.route),
  30: PokemonLocation('Ruta 26', PokemonLocationKind.route),
  31: PokemonLocation('Ruta 27', PokemonLocationKind.route),
  32: PokemonLocation('Ruta 28', PokemonLocationKind.route),
  33: PokemonLocation('Ruta 29', PokemonLocationKind.route),
  34: PokemonLocation('Ruta 30', PokemonLocationKind.route),
  35: PokemonLocation('Ruta 31', PokemonLocationKind.route),
  36: PokemonLocation('Ruta 32', PokemonLocationKind.route),
  37: PokemonLocation('Ruta 33', PokemonLocationKind.route),
  38: PokemonLocation('Ruta 34', PokemonLocationKind.route),
  39: PokemonLocation('Ruta 35', PokemonLocationKind.route),
  40: PokemonLocation('Ruta 36', PokemonLocationKind.route),
  41: PokemonLocation('Ruta 37', PokemonLocationKind.route),
  42: PokemonLocation('Ruta 38', PokemonLocationKind.route),
  43: PokemonLocation('Ruta 39', PokemonLocationKind.route),
  44: PokemonLocation('Ruta 42', PokemonLocationKind.route),
  45: PokemonLocation('Ruta 43', PokemonLocationKind.route),
  46: PokemonLocation('Ruta 44', PokemonLocationKind.route),
  47: PokemonLocation('Ruta 45', PokemonLocationKind.route),
  48: PokemonLocation('Ruta 46', PokemonLocationKind.route),
  49: PokemonLocation('Pueblo Paleta', PokemonLocationKind.city),
  50: PokemonLocation('Ciudad Verde', PokemonLocationKind.city),
  51: PokemonLocation('Ciudad Plateada', PokemonLocationKind.city),
  52: PokemonLocation('Ciudad Celeste', PokemonLocationKind.city),
  53: PokemonLocation('Pueblo Lavanda', PokemonLocationKind.city),
  54: PokemonLocation('Ciudad Carmín', PokemonLocationKind.city),
  55: PokemonLocation('Ciudad Azulona', PokemonLocationKind.city),
  56: PokemonLocation('Ciudad Fucsia', PokemonLocationKind.city),
  57: PokemonLocation('Isla Canela', PokemonLocationKind.city),
  58: PokemonLocation('Meseta Añil', PokemonLocationKind.league),
  59: PokemonLocation('Ciudad Azafrán', PokemonLocationKind.city),
  60: PokemonLocation('Pueblo Primavera', PokemonLocationKind.city),
  61: PokemonLocation('Pueblo Primavera', PokemonLocationKind.city),
  62: PokemonLocation('Pueblo Primavera', PokemonLocationKind.city),
  63: PokemonLocation('Pueblo Primavera', PokemonLocationKind.city),
  64: PokemonLocation('Pueblo Primavera', PokemonLocationKind.city),
  65: PokemonLocation('Pueblo Primavera', PokemonLocationKind.city),
  66: PokemonLocation('Pueblo Primavera', PokemonLocationKind.city),
  67: PokemonLocation('Ciudad Cerezo', PokemonLocationKind.city),
  68: PokemonLocation('Ciudad Cerezo', PokemonLocationKind.city),
  69: PokemonLocation('Ciudad Cerezo', PokemonLocationKind.city),
  70: PokemonLocation('Ciudad Cerezo', PokemonLocationKind.city),
  71: PokemonLocation('Ciudad Cerezo', PokemonLocationKind.city),
  72: PokemonLocation('Ciudad Cerezo', PokemonLocationKind.city),
  73: PokemonLocation('Ciudad Malva', PokemonLocationKind.city),
  74: PokemonLocation('Pueblo Azalea', PokemonLocationKind.city),
  75: PokemonLocation('Ciudad Orquídea', PokemonLocationKind.city),
  76: PokemonLocation('Ciudad Trigal', PokemonLocationKind.city),
  77: PokemonLocation('Ciudad Olivo', PokemonLocationKind.city),
  78: PokemonLocation('Ciudad Iris', PokemonLocationKind.city),
  79: PokemonLocation('Ciudad Iris', PokemonLocationKind.city),
  80: PokemonLocation('Ciudad Iris', PokemonLocationKind.city),
  81: PokemonLocation('Ciudad Iris', PokemonLocationKind.city),
  82: PokemonLocation('Ciudad Jubileo', PokemonLocationKind.city),
  83: PokemonLocation('Ciudad Iris', PokemonLocationKind.city),
  84: PokemonLocation('Ciudad Iris', PokemonLocationKind.city),
  85: PokemonLocation('Ciudad Iris', PokemonLocationKind.city),
  86: PokemonLocation('Ciudad Iris', PokemonLocationKind.city),
  87: PokemonLocation('Pueblo Caoba', PokemonLocationKind.city),
  88: PokemonLocation('Lago de la Furia'),
  89: PokemonLocation('Ciudad Endrino', PokemonLocationKind.city),
  90: PokemonLocation('Monte Plateado', PokemonLocationKind.city),
  91: PokemonLocation('Ruta 19', PokemonLocationKind.route),
  92: PokemonLocation('Ruta 20', PokemonLocationKind.route),
  93: PokemonLocation('Ruta 21', PokemonLocationKind.route),
  94: PokemonLocation('Ruta 40', PokemonLocationKind.route),
  95: PokemonLocation('Ruta 41', PokemonLocationKind.route),
  96: PokemonLocation('Parque Nacional', PokemonLocationKind.city),
  97: PokemonLocation('Ruta 31', PokemonLocationKind.route),
  98: PokemonLocation('Ruta 32', PokemonLocationKind.route),
  99: PokemonLocation('Cueva Unión'),
  100: PokemonLocation('Pueblo Azalea', PokemonLocationKind.city),
  101: PokemonLocation('Ruta 35', PokemonLocationKind.route),
  102: PokemonLocation('Ruta 35', PokemonLocationKind.route),
  103: PokemonLocation('Ruta 36', PokemonLocationKind.route),
  104: PokemonLocation('Ruta 36', PokemonLocationKind.route),
  105: PokemonLocation('Ciudad Jubileo', PokemonLocationKind.city),
  106: PokemonLocation('Cueva Diglett'),
  107: PokemonLocation('Monte Moon'),
  108: PokemonLocation('Túnel Roca'),
  109: PokemonLocation('Parque Compi'),
  110: PokemonLocation('Torre Bellsprout'),
  111: PokemonLocation('Torre Campana'),
  112: PokemonLocation('Torre Radio'),
  113: PokemonLocation('Ruinas Alfa'),
  114: PokemonLocation('Pozo Slowpoke'),
  115: PokemonLocation('Faro Olivo'),
  116: PokemonLocation('Pueblo Caoba', PokemonLocationKind.city),
  117: PokemonLocation('Encinar'),
  118: PokemonLocation('Túnel Trigal'),
  119: PokemonLocation('Monte Mortero'),
  120: PokemonLocation('Ruta Helada'),
  121: PokemonLocation('Islas Remolino'),
  122: PokemonLocation('Cueva Plateada'),
  123: PokemonLocation('Cueva Oscura'),
  124: PokemonLocation('Calle Victoria', PokemonLocationKind.league),
  125: PokemonLocation('Guarida Dragón'),
  126: PokemonLocation('Cataratas Tohjo'),
  127: PokemonLocation('Ruta 30', PokemonLocationKind.route),
  128: PokemonLocation('Ciudad Iris', PokemonLocationKind.city),
  129: PokemonLocation('Ciudad Iris', PokemonLocationKind.city),
  130: PokemonLocation('Ciudad Iris', PokemonLocationKind.city),
  131: PokemonLocation('Ciudad Iris', PokemonLocationKind.city),
  132: PokemonLocation('Ruta 42', PokemonLocationKind.route),
  133: PokemonLocation('Pueblo Caoba', PokemonLocationKind.city),
  134: PokemonLocation('Ruta 29', PokemonLocationKind.route),
  135: PokemonLocation('Ciudad Malva', PokemonLocationKind.city),
  136: PokemonLocation('Pueblo Azalea', PokemonLocationKind.city),
  137: PokemonLocation('Ciudad Trigal', PokemonLocationKind.city),
  138: PokemonLocation('Ciudad Olivo', PokemonLocationKind.city),
  139: PokemonLocation('Ciudad Orquídea', PokemonLocationKind.city),
  140: PokemonLocation('Pueblo Caoba', PokemonLocationKind.city),
  141: PokemonLocation('Ciudad Endrino', PokemonLocationKind.city),
  142: PokemonLocation('Ruta 43', PokemonLocationKind.route),
  143: PokemonLocation('Ruta 30', PokemonLocationKind.route),
  144: PokemonLocation('Ciudad Cerezo', PokemonLocationKind.city),
  145: PokemonLocation('Cueva Celeste'),
  146: PokemonLocation('Islas Espuma'),
  147: PokemonLocation('Bosque Verde'),
  148: PokemonLocation('Central Energía'),
  149: PokemonLocation('Ruta 36', PokemonLocationKind.route),
  150: PokemonLocation('Pokéathlon'),
  151: PokemonLocation('Ruta 47', PokemonLocationKind.route),
  152: PokemonLocation('Ruta 48', PokemonLocationKind.route),
  153: PokemonLocation('Cueva Unión'),
  154: PokemonLocation('Cueva Unión'),
  155: PokemonLocation('Torre Bellsprout'),
  156: PokemonLocation('Torre Bellsprout'),
  157: PokemonLocation('Ciudad Malva', PokemonLocationKind.city),
  158: PokemonLocation('Ciudad Malva', PokemonLocationKind.city),
  159: PokemonLocation('Ciudad Malva', PokemonLocationKind.city),
  160: PokemonLocation('Ciudad Malva', PokemonLocationKind.city),
  161: PokemonLocation('Ciudad Jubileo', PokemonLocationKind.city),
  162: PokemonLocation('Ciudad Malva', PokemonLocationKind.city),
  163: PokemonLocation('Pueblo Azalea', PokemonLocationKind.city),
  164: PokemonLocation('Pueblo Azalea', PokemonLocationKind.city),
  165: PokemonLocation('Pueblo Azalea', PokemonLocationKind.city),
  166: PokemonLocation('Pueblo Azalea', PokemonLocationKind.city),
  167: PokemonLocation('Ciudad Malva', PokemonLocationKind.city),
  168: PokemonLocation('Pueblo Azalea', PokemonLocationKind.city),
  169: PokemonLocation('Ruta 32', PokemonLocationKind.route),
  170: PokemonLocation('Ruta 32', PokemonLocationKind.route),
  171: PokemonLocation('Ruta 34', PokemonLocationKind.route),
  172: PokemonLocation('Ruta 38', PokemonLocationKind.route),
  173: PokemonLocation('Entrada Zona Safari'),
  174: PokemonLocation('Entrada Zona Safari'),
  175: PokemonLocation('Ciudad Jubileo', PokemonLocationKind.city),
  176: PokemonLocation('Cueva Oscura'),
  177: PokemonLocation('Pozo Slowpoke'),
  178: PokemonLocation('Calle Victoria', PokemonLocationKind.league),
  179: PokemonLocation('Calle Victoria', PokemonLocationKind.league),
  180: PokemonLocation('Pueblo Azalea', PokemonLocationKind.city),
  181: PokemonLocation('Pozo Slowpoke'),
  182: PokemonLocation('Ciudad Trigal', PokemonLocationKind.city),
  183: PokemonLocation('Ciudad Trigal', PokemonLocationKind.city),
  184: PokemonLocation('Ciudad Trigal', PokemonLocationKind.city),
  185: PokemonLocation('Ciudad Trigal', PokemonLocationKind.city),
  186: PokemonLocation('Torre Radio'),
  187: PokemonLocation('Torre Radio'),
  188: PokemonLocation('Torre Radio'),
  189: PokemonLocation('Torre Radio'),
  190: PokemonLocation('Torre Radio'),
  191: PokemonLocation('Ciudad Trigal', PokemonLocationKind.city),
  192: PokemonLocation('Ciudad Trigal', PokemonLocationKind.city),
  193: PokemonLocation('Ciudad Trigal', PokemonLocationKind.city),
  194: PokemonLocation('Ciudad Trigal', PokemonLocationKind.city),
  195: PokemonLocation('Ciudad Trigal', PokemonLocationKind.city),
  196: PokemonLocation('Ciudad Trigal', PokemonLocationKind.city),
  197: PokemonLocation('Ciudad Trigal', PokemonLocationKind.city),
  198: PokemonLocation('Ciudad Trigal', PokemonLocationKind.city),
  199: PokemonLocation('Túnel Trigal'),
  200: PokemonLocation('Ciudad Trigal', PokemonLocationKind.city),
  201: PokemonLocation('Ciudad Trigal', PokemonLocationKind.city),
  202: PokemonLocation('Ciudad Trigal', PokemonLocationKind.city),
  203: PokemonLocation('Ciudad Trigal', PokemonLocationKind.city),
  204: PokemonLocation('Ciudad Trigal', PokemonLocationKind.city),
  205: PokemonLocation('Ciudad Trigal', PokemonLocationKind.city),
  206: PokemonLocation('Ciudad Trigal', PokemonLocationKind.city),
  207: PokemonLocation('Terminal Global'),
  208: PokemonLocation('Ciudad Trigal', PokemonLocationKind.city),
  209: PokemonLocation('Ciudad Trigal', PokemonLocationKind.city),
  210: PokemonLocation('Ciudad Trigal', PokemonLocationKind.city),
  211: PokemonLocation('Ciudad Trigal', PokemonLocationKind.city),
  212: PokemonLocation('Ciudad Trigal', PokemonLocationKind.city),
  213: PokemonLocation('Ciudad Trigal', PokemonLocationKind.city),
  214: PokemonLocation('Ruta 39', PokemonLocationKind.route),
  215: PokemonLocation('Ruta 39', PokemonLocationKind.route),
  216: PokemonLocation('Ciudad Iris', PokemonLocationKind.city),
  217: PokemonLocation('Torre Quemada'),
  218: PokemonLocation('Ruinas Alfa'),
  219: PokemonLocation('Ciudad Trigal', PokemonLocationKind.city),
  220: PokemonLocation('Faro Olivo'),
  221: PokemonLocation('Faro Olivo'),
  222: PokemonLocation('Faro Olivo'),
  223: PokemonLocation('Faro Olivo'),
  224: PokemonLocation('Faro Olivo'),
  225: PokemonLocation('Faro Olivo'),
  226: PokemonLocation('Ciudad Olivo', PokemonLocationKind.city),
  227: PokemonLocation('Ciudad Olivo', PokemonLocationKind.city),
  228: PokemonLocation('Ciudad Olivo', PokemonLocationKind.city),
  229: PokemonLocation('Ciudad Olivo', PokemonLocationKind.city),
  230: PokemonLocation('Ciudad Olivo', PokemonLocationKind.city),
  231: PokemonLocation('Ciudad Olivo', PokemonLocationKind.city),
  232: PokemonLocation('Ciudad Orquídea', PokemonLocationKind.city),
  233: PokemonLocation('Ciudad Orquídea', PokemonLocationKind.city),
  234: PokemonLocation('Ciudad Orquídea', PokemonLocationKind.city),
  235: PokemonLocation('Ciudad Orquídea', PokemonLocationKind.city),
  236: PokemonLocation('Ciudad Orquídea', PokemonLocationKind.city),
  237: PokemonLocation('Ruta Helada'),
  238: PokemonLocation('Ruta Helada'),
  239: PokemonLocation('Ruta Helada'),
  240: PokemonLocation('Ciudad Olivo', PokemonLocationKind.city),
  241: PokemonLocation('Ciudad Orquídea', PokemonLocationKind.city),
  242: PokemonLocation('Islas Remolino'),
  243: PokemonLocation('Islas Remolino'),
  244: PokemonLocation('Islas Remolino'),
  245: PokemonLocation('Ruta 43', PokemonLocationKind.route),
  246: PokemonLocation('Pueblo Caoba', PokemonLocationKind.city),
  247: PokemonLocation('Guarida Team Rocket'),
  248: PokemonLocation('Guarida Team Rocket'),
  249: PokemonLocation('Guarida Team Rocket'),
  250: PokemonLocation('Monte Mortero'),
  251: PokemonLocation('Monte Mortero'),
  252: PokemonLocation('Monte Mortero'),
  253: PokemonLocation('Guarida Dragón'),
  254: PokemonLocation('Zona Combate', PokemonLocationKind.city),
  255: PokemonLocation('Zona Combate'),
  256: PokemonLocation('Zona Combate'),
  257: PokemonLocation('Zona Combate'),
  258: PokemonLocation('Zona Combate'),
  259: PokemonLocation('Zona Combate'),
  260: PokemonLocation('Zona Combate'),
  261: PokemonLocation('Zona Combate'),
  262: PokemonLocation('Zona Combate'),
  263: PokemonLocation('Parque Batalla'),
  264: PokemonLocation('Parque Batalla'),
  265: PokemonLocation('Torre Batalla'),
  266: PokemonLocation('Torre Batalla'),
  267: PokemonLocation('Torre Batalla'),
  268: PokemonLocation('Torre Batalla'),
  269: PokemonLocation('Torre Batalla'),
  270: PokemonLocation('Torre Batalla'),
  271: PokemonLocation('Torre Batalla'),
  272: PokemonLocation('Frente Batalla', PokemonLocationKind.city),
  273: PokemonLocation('Frente Batalla'),
  274: PokemonLocation('Torre Batalla'),
  275: PokemonLocation('Fábrica Batalla'),
  276: PokemonLocation('Salón Batalla'),
  277: PokemonLocation('Castillo Batalla'),
  278: PokemonLocation('Ruleta Batalla'),
  279: PokemonLocation('Entrada Acantilado'),
  280: PokemonLocation('Pokéathlon', PokemonLocationKind.city),
  281: PokemonLocation('Pokéathlon'),
  282: PokemonLocation('Pokéathlon'),
  283: PokemonLocation('Pokéathlon'),
  284: PokemonLocation('Pokéathlon'),
  285: PokemonLocation('Pokéathlon'),
  286: PokemonLocation('Pokéathlon'),
  287: PokemonLocation('Pokéathlon'),
  288: PokemonLocation('Guarida Dragón'),
  289: PokemonLocation('Ciudad Endrino', PokemonLocationKind.city),
  290: PokemonLocation('Ciudad Endrino', PokemonLocationKind.city),
  291: PokemonLocation('Ciudad Endrino', PokemonLocationKind.city),
  292: PokemonLocation('Ciudad Endrino', PokemonLocationKind.city),
  293: PokemonLocation('Ciudad Endrino', PokemonLocationKind.city),
  294: PokemonLocation('Lago de la Furia'),
  295: PokemonLocation('Lago de la Furia'),
  296: PokemonLocation('Ruta 26', PokemonLocationKind.route),
  297: PokemonLocation('Ruta 26', PokemonLocationKind.route),
  298: PokemonLocation('Cataratas Tohjo'),
  299: PokemonLocation('Ruta 26', PokemonLocationKind.route),
  300: PokemonLocation('Liga Pokémon', PokemonLocationKind.league),
  301: PokemonLocation('Liga Pokémon', PokemonLocationKind.league),
  302: PokemonLocation('Liga Pokémon', PokemonLocationKind.league),
  303: PokemonLocation('Liga Pokémon', PokemonLocationKind.league),
  304: PokemonLocation('Liga Pokémon', PokemonLocationKind.league),
  305: PokemonLocation('Liga Pokémon', PokemonLocationKind.league),
  306: PokemonLocation('Liga Pokémon', PokemonLocationKind.league),
  307: PokemonLocation('S.S. Aqua'),
  308: PokemonLocation('S.S. Aqua'),
  309: PokemonLocation('S.S. Aqua'),
  310: PokemonLocation('S.S. Aqua'),
  311: PokemonLocation('S.S. Aqua'),
  312: PokemonLocation('Ruinas Alfa'),
  313: PokemonLocation('Ruinas Alfa'),
  314: PokemonLocation('Ruinas Alfa'),
  315: PokemonLocation('Ruinas Alfa'),
  316: PokemonLocation('Ruinas Alfa'),
  317: PokemonLocation('Ruinas Alfa'),
  318: PokemonLocation('Ruinas Alfa'),
  319: PokemonLocation('Ruinas Alfa'),
  320: PokemonLocation('Ruinas Alfa'),
  321: PokemonLocation('Ruinas Alfa'),
  322: PokemonLocation('Ruta 27', PokemonLocationKind.route),
  323: PokemonLocation('Ruinas Alfa'),
  324: PokemonLocation('Ruinas Alfa'),
  325: PokemonLocation('Ruinas Alfa'),
  326: PokemonLocation('Ruinas Alfa'),
  327: PokemonLocation('Ruinas Alfa'),
  328: PokemonLocation('S.S. Aqua'),
  329: PokemonLocation('S.S. Aqua'),
  330: PokemonLocation('Ciudad Olivo', PokemonLocationKind.city),
  331: PokemonLocation('Ruta 34', PokemonLocationKind.route),
  332: PokemonLocation('Torre Campana'),
  333: PokemonLocation('Torre Campana'),
  334: PokemonLocation('Torre Campana'),
  335: PokemonLocation('Torre Campana'),
  336: PokemonLocation('Torre Campana'),
  337: PokemonLocation('Torre Campana'),
  338: PokemonLocation('Torre Campana'),
  339: PokemonLocation('Torre Campana'),
  340: PokemonLocation('Torre Campana'),
  341: PokemonLocation('Torre Campana'),
  342: PokemonLocation('Cueva Acantilado'),
  343: PokemonLocation('Zona Safari'),
  344: PokemonLocation('Zona Safari'),
  345: PokemonLocation('Zona Safari'),
  346: PokemonLocation('Zona Safari'),
  347: PokemonLocation('Zona Safari'),
  348: PokemonLocation('Zona Safari'),
  349: PokemonLocation('Zona Safari'),
  350: PokemonLocation('Zona Safari'),
  351: PokemonLocation('Zona Safari'),
  352: PokemonLocation('Zona Safari'),
  353: PokemonLocation('Zona Safari'),
  354: PokemonLocation('Zona Safari'),
  355: PokemonLocation('Zona Safari'),
  356: PokemonLocation('Zona Safari'),
  357: PokemonLocation('Zona Safari'),
  358: PokemonLocation('Ciudad Carmín', PokemonLocationKind.city),
  359: PokemonLocation('Ciudad Carmín', PokemonLocationKind.city),
  360: PokemonLocation('Ciudad Carmín', PokemonLocationKind.city),
  361: PokemonLocation('Ciudad Carmín', PokemonLocationKind.city),
  362: PokemonLocation('Ciudad Carmín', PokemonLocationKind.city),
  363: PokemonLocation('Ciudad Carmín', PokemonLocationKind.city),
  364: PokemonLocation('Ciudad Carmín', PokemonLocationKind.city),
  365: PokemonLocation('Ciudad Carmín', PokemonLocationKind.city),
  366: PokemonLocation('Ruta 40', PokemonLocationKind.route),
  367: PokemonLocation('Ciudad Olivo', PokemonLocationKind.city),
  368: PokemonLocation('Pueblo Caoba', PokemonLocationKind.city),
  369: PokemonLocation('Ciudad Endrino', PokemonLocationKind.city),
  370: PokemonLocation('Ciudad Azulona', PokemonLocationKind.city),
  371: PokemonLocation('Ciudad Azulona', PokemonLocationKind.city),
  372: PokemonLocation('Ciudad Azulona', PokemonLocationKind.city),
  373: PokemonLocation('Ciudad Azulona', PokemonLocationKind.city),
  374: PokemonLocation('Ciudad Azulona', PokemonLocationKind.city),
  375: PokemonLocation('Ciudad Azulona', PokemonLocationKind.city),
  376: PokemonLocation('Ciudad Azulona', PokemonLocationKind.city),
  377: PokemonLocation('Ciudad Azulona', PokemonLocationKind.city),
  378: PokemonLocation('Ciudad Azulona', PokemonLocationKind.city),
  379: PokemonLocation('Ciudad Azulona', PokemonLocationKind.city),
  380: PokemonLocation('Ciudad Azulona', PokemonLocationKind.city),
  381: PokemonLocation('Ciudad Azulona', PokemonLocationKind.city),
  382: PokemonLocation('Ciudad Azulona', PokemonLocationKind.city),
  383: PokemonLocation('Ciudad Azulona', PokemonLocationKind.city),
  384: PokemonLocation('Pueblo Primavera', PokemonLocationKind.city),
  385: PokemonLocation('Ciudad Orquídea', PokemonLocationKind.city),
  386: PokemonLocation('Ciudad Carmín', PokemonLocationKind.city),
  387: PokemonLocation('Ciudad Carmín', PokemonLocationKind.city),
  388: PokemonLocation('Ruta 10', PokemonLocationKind.route),
  389: PokemonLocation('Ruta 6', PokemonLocationKind.route),
  390: PokemonLocation('Ruta 8', PokemonLocationKind.route),
  391: PokemonLocation('Ruta 5', PokemonLocationKind.route),
  392: PokemonLocation('Ruta 15', PokemonLocationKind.route),
  393: PokemonLocation('Ciudad Azulona', PokemonLocationKind.city),
  394: PokemonLocation('Ciudad Azulona', PokemonLocationKind.city),
  395: PokemonLocation('Ciudad Azulona', PokemonLocationKind.city),
  396: PokemonLocation('Pueblo Caoba', PokemonLocationKind.city),
  397: PokemonLocation('Pueblo Caoba', PokemonLocationKind.city),
  398: PokemonLocation('Ciudad Azafrán', PokemonLocationKind.city),
  399: PokemonLocation('Ciudad Azafrán', PokemonLocationKind.city),
  400: PokemonLocation('Ciudad Azafrán', PokemonLocationKind.city),
  401: PokemonLocation('Ciudad Azafrán', PokemonLocationKind.city),
  402: PokemonLocation('Ciudad Azafrán', PokemonLocationKind.city),
  403: PokemonLocation('Habitación de Rotom'),
  404: PokemonLocation('Ciudad Azafrán', PokemonLocationKind.city),
  405: PokemonLocation('Ciudad Azafrán', PokemonLocationKind.city),
  406: PokemonLocation('Ciudad Azafrán', PokemonLocationKind.city),
  407: PokemonLocation('Ciudad Azafrán', PokemonLocationKind.city),
  408: PokemonLocation('Ciudad Azafrán', PokemonLocationKind.city),
  409: PokemonLocation('Ciudad Azafrán', PokemonLocationKind.city),
  410: PokemonLocation('Ciudad Azafrán', PokemonLocationKind.city),
  411: PokemonLocation('Acceso Frente Batalla', PokemonLocationKind.city),
  412: PokemonLocation('Terminal Global'),
  413: PokemonLocation('Terminal Global'),
  414: PokemonLocation('Ruta 2', PokemonLocationKind.route),
  415: PokemonLocation('Ruta 16', PokemonLocationKind.route),
  416: PokemonLocation('Ruta 20', PokemonLocationKind.route),
  417: PokemonLocation('Ruta 2', PokemonLocationKind.route),
  418: PokemonLocation('Ruta 2', PokemonLocationKind.route),
  419: PokemonLocation('Ruta 2', PokemonLocationKind.route),
  420: PokemonLocation('Ruta 2', PokemonLocationKind.route),
  421: PokemonLocation('Ruta 16', PokemonLocationKind.route),
  422: PokemonLocation('Ruta 16', PokemonLocationKind.route),
  423: PokemonLocation('Ruta 18', PokemonLocationKind.route),
  424: PokemonLocation('Ruta 19', PokemonLocationKind.route),
  425: PokemonLocation('Ruta 11', PokemonLocationKind.route),
  426: PokemonLocation('Ciudad Celeste', PokemonLocationKind.city),
  427: PokemonLocation('Ciudad Celeste', PokemonLocationKind.city),
  428: PokemonLocation('Ciudad Celeste', PokemonLocationKind.city),
  429: PokemonLocation('Ciudad Celeste', PokemonLocationKind.city),
  430: PokemonLocation('Ciudad Celeste', PokemonLocationKind.city),
  431: PokemonLocation('Ciudad Celeste', PokemonLocationKind.city),
  432: PokemonLocation('Ciudad Celeste', PokemonLocationKind.city),
  433: PokemonLocation('Pueblo Lavanda', PokemonLocationKind.city),
  434: PokemonLocation('Pueblo Lavanda', PokemonLocationKind.city),
  435: PokemonLocation('Pueblo Lavanda', PokemonLocationKind.city),
  436: PokemonLocation('Pueblo Lavanda', PokemonLocationKind.city),
  437: PokemonLocation('Pueblo Lavanda', PokemonLocationKind.city),
  438: PokemonLocation('Pueblo Lavanda', PokemonLocationKind.city),
  439: PokemonLocation('Pueblo Lavanda', PokemonLocationKind.city),
  440: PokemonLocation('Ruta 25', PokemonLocationKind.route),
  441: PokemonLocation('Ciudad Trigal', PokemonLocationKind.city),
  442: PokemonLocation('Ciudad Azulona', PokemonLocationKind.city),
  443: PokemonLocation('Ciudad Azulona', PokemonLocationKind.city),
  444: PokemonLocation('Ciudad Azulona', PokemonLocationKind.city),
  445: PokemonLocation('Ciudad Azafrán', PokemonLocationKind.city),
  446: PokemonLocation('Faro Olivo'),
  447: PokemonLocation('Torre Radio'),
  448: PokemonLocation('Monte Moon'),
  449: PokemonLocation('Monte Moon'),
  450: PokemonLocation('Cueva Celeste'),
  451: PokemonLocation('Cueva Celeste'),
  452: PokemonLocation('Túnel Roca'),
  453: PokemonLocation('Islas Espuma'),
  454: PokemonLocation('Islas Espuma'),
  455: PokemonLocation('Islas Espuma'),
  456: PokemonLocation('Islas Espuma'),
  457: PokemonLocation('Islas Espuma'),
  458: PokemonLocation('Islas Espuma'),
  459: PokemonLocation('Cueva Plateada'),
  460: PokemonLocation('Cueva Plateada'),
  461: PokemonLocation('Cueva Plateada'),
  462: PokemonLocation('Cueva Plateada'),
  463: PokemonLocation('Cueva Plateada'),
  464: PokemonLocation('Cueva Plateada'),
  465: PokemonLocation('Cueva Plateada'),
  466: PokemonLocation('Ruta 10', PokemonLocationKind.route),
  467: PokemonLocation('Central Energía'),
  468: PokemonLocation('Ruta 5', PokemonLocationKind.route),
  469: PokemonLocation('Ruta 5', PokemonLocationKind.route),
  470: PokemonLocation('Ruta 6', PokemonLocationKind.route),
  471: PokemonLocation('Ciudad Plateada', PokemonLocationKind.city),
  472: PokemonLocation('Ciudad Plateada', PokemonLocationKind.city),
  473: PokemonLocation('Ciudad Plateada', PokemonLocationKind.city),
  474: PokemonLocation('Ciudad Plateada', PokemonLocationKind.city),
  475: PokemonLocation('Ciudad Plateada', PokemonLocationKind.city),
  476: PokemonLocation('Ciudad Plateada', PokemonLocationKind.city),
  477: PokemonLocation('Ciudad Plateada', PokemonLocationKind.city),
  478: PokemonLocation('Ciudad Fucsia', PokemonLocationKind.city),
  479: PokemonLocation('Parque Compi'),
  480: PokemonLocation('Ciudad Fucsia', PokemonLocationKind.city),
  481: PokemonLocation('Ciudad Fucsia', PokemonLocationKind.city),
  482: PokemonLocation('Ciudad Fucsia', PokemonLocationKind.city),
  483: PokemonLocation('Ciudad Fucsia', PokemonLocationKind.city),
  484: PokemonLocation('Ruta 10', PokemonLocationKind.route),
  485: PokemonLocation('Ciudad Fucsia', PokemonLocationKind.city),
  486: PokemonLocation('Islas Remolino'),
  487: PokemonLocation('Parque Nacional', PokemonLocationKind.city),
  488: PokemonLocation('Parque Nacional', PokemonLocationKind.city),
  489: PokemonLocation('Central Energía'),
  490: PokemonLocation('Ruinas Alfa'),
  491: PokemonLocation('Ruinas Alfa'),
  492: PokemonLocation('Ruinas Alfa'),
  493: PokemonLocation('Ruta 7', PokemonLocationKind.route),
  494: PokemonLocation('Pueblo Lavanda', PokemonLocationKind.city),
  495: PokemonLocation('Ciudad Celeste', PokemonLocationKind.city),
  496: PokemonLocation('Ciudad Verde', PokemonLocationKind.city),
  497: PokemonLocation('Ciudad Verde', PokemonLocationKind.city),
  498: PokemonLocation('Ciudad Verde', PokemonLocationKind.city),
  499: PokemonLocation('Ciudad Verde', PokemonLocationKind.city),
  500: PokemonLocation('Ciudad Verde', PokemonLocationKind.city),
  501: PokemonLocation('Ciudad Verde', PokemonLocationKind.city),
  502: PokemonLocation('Ciudad Verde', PokemonLocationKind.city),
  503: PokemonLocation('Pueblo Paleta', PokemonLocationKind.city),
  504: PokemonLocation('Pueblo Paleta', PokemonLocationKind.city),
  505: PokemonLocation('Pueblo Paleta', PokemonLocationKind.city),
  506: PokemonLocation('Pueblo Paleta', PokemonLocationKind.city),
  507: PokemonLocation('Pueblo Paleta', PokemonLocationKind.city),
  508: PokemonLocation('Isla Canela'),
  509: PokemonLocation('Isla Canela'),
  510: PokemonLocation('Ruta 28', PokemonLocationKind.route),
  511: PokemonLocation('Ruta 3', PokemonLocationKind.route),
  512: PokemonLocation('Ruta 3', PokemonLocationKind.route),
  513: PokemonLocation('Monte Moon'),
  514: PokemonLocation('Monte Plateado'),
  515: PokemonLocation('Monte Plateado'),
  517: PokemonLocation('Ruta 5', PokemonLocationKind.route),
  518: PokemonLocation('Monte Moon'),
  519: PokemonLocation('Ciudad Trigal', PokemonLocationKind.city),
  520: PokemonLocation('Ciudad Azafrán', PokemonLocationKind.city),
  521: PokemonLocation('Ruinas Sinjoh'),
  522: PokemonLocation('Ruinas Sinjoh'),
  523: PokemonLocation('Ruinas Sinjoh'),
  524: PokemonLocation('Torre Oculta'),
  525: PokemonLocation('Torre Oculta'),
  526: PokemonLocation('Torre Oculta'),
  527: PokemonLocation('Ruta 1', PokemonLocationKind.route),
  528: PokemonLocation('Acceso Frente Batalla'),
  529: PokemonLocation('Acceso Frente Batalla'),
  530: PokemonLocation('Acceso Frente Batalla'),
  531: PokemonLocation('Acceso Frente Batalla'),
  532: PokemonLocation('Ruta 5', PokemonLocationKind.route),
  533: PokemonLocation('Ruta 12', PokemonLocationKind.route),
  534: PokemonLocation('Entrada Zona Safari'),
  535: PokemonLocation('Entrada Zona Safari'),
  536: PokemonLocation('Ciudad Trigal', PokemonLocationKind.city),
  537: PokemonLocation('Ciudad Azulona', PokemonLocationKind.city),
  539: PokemonLocation('Liga Pokémon', PokemonLocationKind.league),
};
