import '../../../models/pokemon_location.dart';

/// Mapas iniciales de Sinnoh usados por la bitácora de Platino.
/// Los índices corresponden a `MapHeader` del juego, no al ID de la Pokédex.
const Map<int, PokemonLocation> platinumLocations = <int, PokemonLocation>{
  311: PokemonLocation('Lago Veraz'),
  312: PokemonLocation('Lago Veraz'),
  342: PokemonLocation('Ruta 201', PokemonLocationKind.route),
  343: PokemonLocation('Ruta 202', PokemonLocationKind.route),
  344: PokemonLocation('Ruta 203', PokemonLocationKind.route),
  345: PokemonLocation('Ruta 204', PokemonLocationKind.route),
  346: PokemonLocation('Ruta 204', PokemonLocationKind.route),
  347: PokemonLocation('Ruta 205', PokemonLocationKind.route),
  349: PokemonLocation('Ruta 205', PokemonLocationKind.route),
  350: PokemonLocation('Ruta 206', PokemonLocationKind.route),
  353: PokemonLocation('Ruta 207', PokemonLocationKind.route),
  354: PokemonLocation('Ruta 208', PokemonLocationKind.route),
  355: PokemonLocation('Ruta 209', PokemonLocationKind.route),
  358: PokemonLocation('Ruta 210', PokemonLocationKind.route),
  359: PokemonLocation('Ruta 210', PokemonLocationKind.route),
  361: PokemonLocation('Ruta 211', PokemonLocationKind.route),
  362: PokemonLocation('Ruta 211', PokemonLocationKind.route),
  363: PokemonLocation('Ruta 212', PokemonLocationKind.route),
  364: PokemonLocation('Ruta 212', PokemonLocationKind.route),
  366: PokemonLocation('Ruta 213', PokemonLocationKind.route),
  367: PokemonLocation('Ruta 214', PokemonLocationKind.route),
  368: PokemonLocation('Ruta 215', PokemonLocationKind.route),
  369: PokemonLocation('Ruta 216', PokemonLocationKind.route),
  370: PokemonLocation('Ruta 217', PokemonLocationKind.route),
  372: PokemonLocation('Ruta 218', PokemonLocationKind.route),
  373: PokemonLocation('Ruta 219', PokemonLocationKind.route),
  374: PokemonLocation('Ruta 220', PokemonLocationKind.route),
  375: PokemonLocation('Ruta 221', PokemonLocationKind.route),
  376: PokemonLocation('Ruta 222', PokemonLocationKind.route),
  377: PokemonLocation('Ruta 224', PokemonLocationKind.route),
  378: PokemonLocation('Ruta 225', PokemonLocationKind.route),
  379: PokemonLocation('Ruta 226', PokemonLocationKind.route),
  380: PokemonLocation('Ruta 227', PokemonLocationKind.route),
  381: PokemonLocation('Ruta 228', PokemonLocationKind.route),
  382: PokemonLocation('Ruta 229', PokemonLocationKind.route),
  383: PokemonLocation('Ruta 230', PokemonLocationKind.route),
  411: PokemonLocation('Pueblo Hojaverde', PokemonLocationKind.city),
  412: PokemonLocation('Pueblo Hojaverde', PokemonLocationKind.city),
  413: PokemonLocation('Pueblo Hojaverde', PokemonLocationKind.city),
  414: PokemonLocation('Pueblo Hojaverde', PokemonLocationKind.city),
  415: PokemonLocation('Pueblo Hojaverde', PokemonLocationKind.city),
  416: PokemonLocation('Pueblo Hojaverde', PokemonLocationKind.city),
  417: PokemonLocation('Pueblo Hojaverde', PokemonLocationKind.city),
  418: PokemonLocation('Pueblo Arena', PokemonLocationKind.city),
  419: PokemonLocation('Pueblo Arena', PokemonLocationKind.city),
  420: PokemonLocation('Pueblo Arena', PokemonLocationKind.city),
  421: PokemonLocation('Pueblo Arena', PokemonLocationKind.city),
  422: PokemonLocation('Pueblo Arena', PokemonLocationKind.city),
  423: PokemonLocation('Pueblo Arena', PokemonLocationKind.city),
  424: PokemonLocation('Pueblo Arena', PokemonLocationKind.city),
  425: PokemonLocation('Pueblo Arena', PokemonLocationKind.city),
};
