import '../../../models/pokemon_location.dart';

/// Ubicaciones de Sinnoh indexadas por MapHeader de Generación IV.
/// Incluye exteriores e interiores bajo su ubicación principal para evitar
/// mostrar identificadores crudos mientras el jugador explora edificios.
const Map<int, PokemonLocation> platinumLocations = <int, PokemonLocation>{
  3: PokemonLocation('Ciudad Jubileo', PokemonLocationKind.city),
  4: PokemonLocation('Ciudad Jubileo', PokemonLocationKind.city),
  5: PokemonLocation('Ciudad Jubileo', PokemonLocationKind.city),
  6: PokemonLocation('Ciudad Jubileo', PokemonLocationKind.city),
  7: PokemonLocation('Ciudad Jubileo', PokemonLocationKind.city),
  19: PokemonLocation('Ciudad Jubileo', PokemonLocationKind.city),
  20: PokemonLocation('Ciudad Jubileo', PokemonLocationKind.city),
  21: PokemonLocation('Ciudad Jubileo', PokemonLocationKind.city),
  22: PokemonLocation('Ciudad Jubileo', PokemonLocationKind.city),
  23: PokemonLocation('Ciudad Jubileo', PokemonLocationKind.city),
  24: PokemonLocation('Ciudad Jubileo', PokemonLocationKind.city),
  25: PokemonLocation('Ciudad Jubileo', PokemonLocationKind.city),
  26: PokemonLocation('Ciudad Jubileo', PokemonLocationKind.city),
  27: PokemonLocation('Ciudad Jubileo', PokemonLocationKind.city),
  30: PokemonLocation('Ciudad Jubileo', PokemonLocationKind.city),
  31: PokemonLocation('Ciudad Jubileo', PokemonLocationKind.city),
  32: PokemonLocation('Ciudad Jubileo', PokemonLocationKind.city),
  33: PokemonLocation('Ciudad Canal', PokemonLocationKind.city),
  34: PokemonLocation('Ciudad Canal', PokemonLocationKind.city),
  35: PokemonLocation('Ciudad Canal', PokemonLocationKind.city),
  36: PokemonLocation('Ciudad Canal', PokemonLocationKind.city),
  37: PokemonLocation('Ciudad Canal', PokemonLocationKind.city),
  41: PokemonLocation('Ciudad Canal', PokemonLocationKind.city),
  42: PokemonLocation('Ciudad Canal', PokemonLocationKind.city),
  43: PokemonLocation('Ciudad Canal', PokemonLocationKind.city),
  44: PokemonLocation('Ciudad Canal', PokemonLocationKind.city),
  45: PokemonLocation('Ciudad Pirita', PokemonLocationKind.city),
  46: PokemonLocation('Ciudad Pirita', PokemonLocationKind.city),
  47: PokemonLocation('Ciudad Pirita', PokemonLocationKind.city),
  48: PokemonLocation('Ciudad Pirita', PokemonLocationKind.city),
  49: PokemonLocation('Ciudad Pirita', PokemonLocationKind.city),
  50: PokemonLocation('Ciudad Pirita', PokemonLocationKind.city),
  51: PokemonLocation('Ciudad Pirita', PokemonLocationKind.city),
  52: PokemonLocation('Ciudad Pirita', PokemonLocationKind.city),
  53: PokemonLocation('Ciudad Pirita', PokemonLocationKind.city),
  54: PokemonLocation('Ciudad Pirita', PokemonLocationKind.city),
  55: PokemonLocation('Ciudad Pirita', PokemonLocationKind.city),
  56: PokemonLocation('Ciudad Pirita', PokemonLocationKind.city),
  57: PokemonLocation('Ciudad Pirita', PokemonLocationKind.city),
  58: PokemonLocation('Ciudad Pirita', PokemonLocationKind.city),
  60: PokemonLocation('Ciudad Pirita', PokemonLocationKind.city),
  61: PokemonLocation('Ciudad Pirita', PokemonLocationKind.city),
  62: PokemonLocation('Ciudad Pirita', PokemonLocationKind.city),
  63: PokemonLocation('Ciudad Pirita', PokemonLocationKind.city),
  64: PokemonLocation('Ciudad Pirita', PokemonLocationKind.city),
  65: PokemonLocation('Ciudad Vetusta', PokemonLocationKind.city),
  66: PokemonLocation('Ciudad Vetusta', PokemonLocationKind.city),
  67: PokemonLocation('Ciudad Vetusta', PokemonLocationKind.city),
  68: PokemonLocation('Ciudad Vetusta', PokemonLocationKind.city),
  69: PokemonLocation('Ciudad Vetusta', PokemonLocationKind.city),
  70: PokemonLocation('Ciudad Vetusta', PokemonLocationKind.city),
  76: PokemonLocation('Ciudad Vetusta', PokemonLocationKind.city),
  77: PokemonLocation('Ciudad Vetusta', PokemonLocationKind.city),
  78: PokemonLocation('Ciudad Vetusta', PokemonLocationKind.city),
  79: PokemonLocation('Ciudad Vetusta', PokemonLocationKind.city),
  80: PokemonLocation('Ruta 206', PokemonLocationKind.route),
  81: PokemonLocation('Ciudad Vetusta', PokemonLocationKind.city),
  82: PokemonLocation('Ciudad Vetusta', PokemonLocationKind.city),
  83: PokemonLocation('Ciudad Vetusta', PokemonLocationKind.city),
  84: PokemonLocation('Ciudad Vetusta', PokemonLocationKind.city),
  85: PokemonLocation('Ciudad Vetusta', PokemonLocationKind.city),
  86: PokemonLocation('Ciudad Corazón', PokemonLocationKind.city),
  87: PokemonLocation('Ciudad Corazón', PokemonLocationKind.city),
  88: PokemonLocation('Ciudad Corazón', PokemonLocationKind.city),
  89: PokemonLocation('Ciudad Corazón', PokemonLocationKind.city),
  90: PokemonLocation('Ciudad Corazón', PokemonLocationKind.city),
  91: PokemonLocation('Ciudad Corazón', PokemonLocationKind.city),
  92: PokemonLocation('Ciudad Corazón', PokemonLocationKind.city),
  93: PokemonLocation('Ciudad Corazón', PokemonLocationKind.city),
  94: PokemonLocation('Ciudad Corazón', PokemonLocationKind.city),
  95: PokemonLocation('Ciudad Corazón', PokemonLocationKind.city),
  96: PokemonLocation('Ciudad Corazón', PokemonLocationKind.city),
  97: PokemonLocation('Ciudad Corazón', PokemonLocationKind.city),
  98: PokemonLocation('Ciudad Corazón', PokemonLocationKind.city),
  99: PokemonLocation('Ciudad Corazón', PokemonLocationKind.city),
  100: PokemonLocation('Ciudad Corazón', PokemonLocationKind.city),
  101: PokemonLocation('Ciudad Corazón', PokemonLocationKind.city),
  102: PokemonLocation('Ciudad Corazón', PokemonLocationKind.city),
  103: PokemonLocation('Ciudad Corazón', PokemonLocationKind.city),
  104: PokemonLocation('Ciudad Corazón', PokemonLocationKind.city),
  105: PokemonLocation('Ciudad Corazón', PokemonLocationKind.city),
  106: PokemonLocation('Ciudad Corazón', PokemonLocationKind.city),
  107: PokemonLocation('Ciudad Corazón', PokemonLocationKind.city),
  108: PokemonLocation('Ciudad Corazón', PokemonLocationKind.city),
  109: PokemonLocation('Ruta 208', PokemonLocationKind.route),
  110: PokemonLocation('Ruta 209', PokemonLocationKind.route),
  111: PokemonLocation('Ruta 212', PokemonLocationKind.route),
  112: PokemonLocation('Ciudad Corazón', PokemonLocationKind.city),
  113: PokemonLocation('Ciudad Corazón', PokemonLocationKind.city),
  114: PokemonLocation('Ciudad Corazón', PokemonLocationKind.city),
  115: PokemonLocation('Ciudad Corazón', PokemonLocationKind.city),
  120: PokemonLocation('Ciudad Pradera', PokemonLocationKind.city),
  121: PokemonLocation('Ciudad Pradera', PokemonLocationKind.city),
  122: PokemonLocation('Ciudad Pradera', PokemonLocationKind.city),
  123: PokemonLocation('Ciudad Pradera', PokemonLocationKind.city),
  124: PokemonLocation('Ciudad Pradera', PokemonLocationKind.city),
  125: PokemonLocation('Ciudad Pradera', PokemonLocationKind.city),
  126: PokemonLocation('Ciudad Pradera', PokemonLocationKind.city),
  127: PokemonLocation('Ciudad Pradera', PokemonLocationKind.city),
  128: PokemonLocation('Ciudad Pradera', PokemonLocationKind.city),
  129: PokemonLocation('Ciudad Pradera', PokemonLocationKind.city),
  130: PokemonLocation('Ciudad Pradera', PokemonLocationKind.city),
  131: PokemonLocation('Ciudad Pradera', PokemonLocationKind.city),
  132: PokemonLocation('Ciudad Rocavelo', PokemonLocationKind.city),
  133: PokemonLocation('Ciudad Rocavelo', PokemonLocationKind.city),
  134: PokemonLocation('Ciudad Rocavelo', PokemonLocationKind.city),
  135: PokemonLocation('Ciudad Rocavelo', PokemonLocationKind.city),
  143: PokemonLocation('Ciudad Rocavelo', PokemonLocationKind.city),
  144: PokemonLocation('Ciudad Rocavelo', PokemonLocationKind.city),
  145: PokemonLocation('Ciudad Rocavelo', PokemonLocationKind.city),
  146: PokemonLocation('Ciudad Rocavelo', PokemonLocationKind.city),
  147: PokemonLocation('Ciudad Rocavelo', PokemonLocationKind.city),
  148: PokemonLocation('Ciudad Rocavelo', PokemonLocationKind.city),
  149: PokemonLocation('Ruta 215', PokemonLocationKind.route),
  150: PokemonLocation('Ciudad Marina', PokemonLocationKind.city),
  151: PokemonLocation('Ciudad Marina', PokemonLocationKind.city),
  152: PokemonLocation('Ciudad Marina', PokemonLocationKind.city),
  153: PokemonLocation('Ciudad Marina', PokemonLocationKind.city),
  154: PokemonLocation('Ciudad Marina', PokemonLocationKind.city),
  155: PokemonLocation('Ciudad Marina', PokemonLocationKind.city),
  156: PokemonLocation('Ciudad Marina', PokemonLocationKind.city),
  158: PokemonLocation('Ciudad Marina', PokemonLocationKind.city),
  159: PokemonLocation('Ciudad Marina', PokemonLocationKind.city),
  160: PokemonLocation('Ciudad Marina', PokemonLocationKind.city),
  161: PokemonLocation('Ciudad Marina', PokemonLocationKind.city),
  162: PokemonLocation('Ciudad Marina', PokemonLocationKind.city),
  163: PokemonLocation('Ciudad Marina', PokemonLocationKind.city),
  165: PokemonLocation('Ciudad Puntaneva', PokemonLocationKind.city),
  166: PokemonLocation('Ciudad Puntaneva', PokemonLocationKind.city),
  167: PokemonLocation('Ciudad Puntaneva', PokemonLocationKind.city),
  168: PokemonLocation('Ciudad Puntaneva', PokemonLocationKind.city),
  169: PokemonLocation('Ciudad Puntaneva', PokemonLocationKind.city),
  170: PokemonLocation('Ciudad Puntaneva', PokemonLocationKind.city),
  171: PokemonLocation('Ciudad Puntaneva', PokemonLocationKind.city),
  172: PokemonLocation('Liga Pokémon', PokemonLocationKind.league),
  173: PokemonLocation('Liga Pokémon', PokemonLocationKind.league),
  174: PokemonLocation('Liga Pokémon', PokemonLocationKind.league),
  175: PokemonLocation('Liga Pokémon', PokemonLocationKind.league),
  176: PokemonLocation('Liga Pokémon', PokemonLocationKind.league),
  177: PokemonLocation('Liga Pokémon', PokemonLocationKind.league),
  178: PokemonLocation('Liga Pokémon', PokemonLocationKind.league),
  179: PokemonLocation('Liga Pokémon', PokemonLocationKind.league),
  180: PokemonLocation('Liga Pokémon', PokemonLocationKind.league),
  181: PokemonLocation('Liga Pokémon', PokemonLocationKind.league),
  182: PokemonLocation('Liga Pokémon', PokemonLocationKind.league),
  183: PokemonLocation('Liga Pokémon', PokemonLocationKind.league),
  184: PokemonLocation('Liga Pokémon', PokemonLocationKind.league),
  185: PokemonLocation('Liga Pokémon', PokemonLocationKind.league),
  186: PokemonLocation('Liga Pokémon', PokemonLocationKind.league),
  187: PokemonLocation('Liga Pokémon', PokemonLocationKind.league),
  188: PokemonLocation('Zona Combate', PokemonLocationKind.city),
  189: PokemonLocation('Zona Combate', PokemonLocationKind.city),
  190: PokemonLocation('Zona Combate', PokemonLocationKind.city),
  191: PokemonLocation('Zona Combate', PokemonLocationKind.city),
  192: PokemonLocation('Zona Combate', PokemonLocationKind.city),
  193: PokemonLocation('Ruta 225', PokemonLocationKind.route),
  194: PokemonLocation('Zona Combate', PokemonLocationKind.city),
  195: PokemonLocation('Zona Combate', PokemonLocationKind.city),
  196: PokemonLocation('Zona Combate', PokemonLocationKind.city),
  200: PokemonLocation('Valle Eólico'),
  201: PokemonLocation('Valle Eólico'),
  202: PokemonLocation('Bosque Vetusto'),
  203: PokemonLocation('Bosque Vetusto'),
  204: PokemonLocation('Forja Fuego'),
  205: PokemonLocation('Forja Fuego'),
  207: PokemonLocation('Monte Corona'),
  208: PokemonLocation('Monte Corona'),
  209: PokemonLocation('Monte Corona'),
  210: PokemonLocation('Monte Corona'),
  211: PokemonLocation('Monte Corona'),
  212: PokemonLocation('Monte Corona'),
  213: PokemonLocation('Monte Corona'),
  214: PokemonLocation('Monte Corona'),
  215: PokemonLocation('Monte Corona'),
  216: PokemonLocation('Monte Corona'),
  217: PokemonLocation('Monte Corona'),
  218: PokemonLocation('Monte Corona'),
  219: PokemonLocation('Monte Corona'),
  220: PokemonLocation('Columna Lanza'),
  221: PokemonLocation('Columna Lanza'),
  223: PokemonLocation('Ciudad Pradera', PokemonLocationKind.city),
  225: PokemonLocation('Ruinas Sosiego'),
  226: PokemonLocation('Ruinas Sosiego'),
  227: PokemonLocation('Ruinas Sosiego'),
  228: PokemonLocation('Ruinas Sosiego'),
  229: PokemonLocation('Ruinas Sosiego'),
  230: PokemonLocation('Ruinas Sosiego'),
  231: PokemonLocation('Ruinas Sosiego'),
  232: PokemonLocation('Ruinas Sosiego'),
  233: PokemonLocation('Ruinas Sosiego'),
  234: PokemonLocation('Ruinas Sosiego'),
  235: PokemonLocation('Ruinas Sosiego'),
  236: PokemonLocation('Ruinas Sosiego'),
  237: PokemonLocation('Ruinas Sosiego'),
  238: PokemonLocation('Ruinas Sosiego'),
  239: PokemonLocation('Ruinas Sosiego'),
  240: PokemonLocation('Ruinas Sosiego'),
  241: PokemonLocation('Ruinas Sosiego'),
  242: PokemonLocation('Ruinas Sosiego'),
  244: PokemonLocation('Calle Victoria', PokemonLocationKind.league),
  245: PokemonLocation('Calle Victoria', PokemonLocationKind.league),
  246: PokemonLocation('Calle Victoria', PokemonLocationKind.league),
  247: PokemonLocation('Calle Victoria', PokemonLocationKind.league),
  248: PokemonLocation('Calle Victoria', PokemonLocationKind.league),
  249: PokemonLocation('Calle Victoria', PokemonLocationKind.league),
  251: PokemonLocation('Parque Compi'),
  253: PokemonLocation('Plaza Amistad'),
  254: PokemonLocation('Senda Desolada'),
  260: PokemonLocation('Isla Plenilunio'),
  261: PokemonLocation('Isla Plenilunio'),
  262: PokemonLocation('Montaña Dura'),
  263: PokemonLocation('Montaña Dura'),
  264: PokemonLocation('Montaña Dura'),
  265: PokemonLocation('Montaña Dura'),
  267: PokemonLocation('Fuente Despedida'),
  268: PokemonLocation('Cueva Retorno'),
  269: PokemonLocation('Cueva Retorno'),
  270: PokemonLocation('Cueva Retorno'),
  271: PokemonLocation('Cueva Retorno'),
  272: PokemonLocation('Cueva Retorno'),
  273: PokemonLocation('Cueva Retorno'),
  288: PokemonLocation('Isla Hierro'),
  289: PokemonLocation('Isla Hierro'),
  290: PokemonLocation('Isla Hierro'),
  291: PokemonLocation('Isla Hierro'),
  292: PokemonLocation('Isla Hierro'),
  293: PokemonLocation('Isla Hierro'),
  294: PokemonLocation('Isla Hierro'),
  295: PokemonLocation('Vieja Mansión'),
  296: PokemonLocation('Vieja Mansión'),
  297: PokemonLocation('Vieja Mansión'),
  298: PokemonLocation('Vieja Mansión'),
  299: PokemonLocation('Vieja Mansión'),
  300: PokemonLocation('Vieja Mansión'),
  301: PokemonLocation('Vieja Mansión'),
  302: PokemonLocation('Vieja Mansión'),
  303: PokemonLocation('Vieja Mansión'),
  305: PokemonLocation('Sede Galaxia'),
  306: PokemonLocation('Sede Galaxia'),
  307: PokemonLocation('Sede Galaxia'),
  308: PokemonLocation('Sede Galaxia'),
  309: PokemonLocation('Sede Galaxia'),
  310: PokemonLocation('Sede Galaxia'),
  311: PokemonLocation('Lago Veraz'),
  312: PokemonLocation('Lago Veraz'),
  314: PokemonLocation('Lago Valor'),
  315: PokemonLocation('Lago Valor'),
  317: PokemonLocation('Lago Agudeza'),
  318: PokemonLocation('Lago Agudeza'),
  320: PokemonLocation('Isla Lunanueva'),
  321: PokemonLocation('Isla Lunanueva'),
  326: PokemonLocation('Torre Batalla'),
  327: PokemonLocation('Torre Batalla'),
  328: PokemonLocation('Torre Batalla'),
  329: PokemonLocation('Torre Batalla'),
  330: PokemonLocation('Torre Batalla'),
  331: PokemonLocation('Torre Batalla'),
  338: PokemonLocation('Lago Valor'),
  339: PokemonLocation('Lago Valor'),
  342: PokemonLocation('Ruta 201', PokemonLocationKind.route),
  343: PokemonLocation('Ruta 202', PokemonLocationKind.route),
  344: PokemonLocation('Ruta 203', PokemonLocationKind.route),
  345: PokemonLocation('Ruta 204', PokemonLocationKind.route),
  346: PokemonLocation('Ruta 204', PokemonLocationKind.route),
  347: PokemonLocation('Ruta 205', PokemonLocationKind.route),
  348: PokemonLocation('Ruta 205', PokemonLocationKind.route),
  349: PokemonLocation('Ruta 205', PokemonLocationKind.route),
  350: PokemonLocation('Ruta 206', PokemonLocationKind.route),
  351: PokemonLocation('Ruta 206', PokemonLocationKind.route),
  352: PokemonLocation('Ruta 206', PokemonLocationKind.route),
  353: PokemonLocation('Ruta 207', PokemonLocationKind.route),
  354: PokemonLocation('Ruta 208', PokemonLocationKind.route),
  355: PokemonLocation('Ruta 208', PokemonLocationKind.route),
  356: PokemonLocation('Ruta 209', PokemonLocationKind.route),
  357: PokemonLocation('Ruta 209', PokemonLocationKind.route),
  358: PokemonLocation('Ruta 209', PokemonLocationKind.route),
  359: PokemonLocation('Ruta 209', PokemonLocationKind.route),
  360: PokemonLocation('Ruta 209', PokemonLocationKind.route),
  361: PokemonLocation('Ruta 209', PokemonLocationKind.route),
  362: PokemonLocation('Ruta 210', PokemonLocationKind.route),
  363: PokemonLocation('Ruta 210', PokemonLocationKind.route),
  364: PokemonLocation('Ruta 210', PokemonLocationKind.route),
  365: PokemonLocation('Ruta 211', PokemonLocationKind.route),
  366: PokemonLocation('Ruta 211', PokemonLocationKind.route),
  367: PokemonLocation('Ruta 212', PokemonLocationKind.route),
  371: PokemonLocation('Ruta 212', PokemonLocationKind.route),
  372: PokemonLocation('Ruta 212', PokemonLocationKind.route),
  373: PokemonLocation('Ruta 213', PokemonLocationKind.route),
  374: PokemonLocation('Ruta 213', PokemonLocationKind.route),
  376: PokemonLocation('Ruta 213', PokemonLocationKind.route),
  377: PokemonLocation('Ruta 213', PokemonLocationKind.route),
  378: PokemonLocation('Ruta 213', PokemonLocationKind.route),
  379: PokemonLocation('Ruta 213', PokemonLocationKind.route),
  380: PokemonLocation('Ruta 214', PokemonLocationKind.route),
  381: PokemonLocation('Ruta 214', PokemonLocationKind.route),
  382: PokemonLocation('Ruta 215', PokemonLocationKind.route),
  383: PokemonLocation('Ruta 216', PokemonLocationKind.route),
  384: PokemonLocation('Ruta 216', PokemonLocationKind.route),
  385: PokemonLocation('Ruta 217', PokemonLocationKind.route),
  386: PokemonLocation('Ruta 217', PokemonLocationKind.route),
  387: PokemonLocation('Ruta 217', PokemonLocationKind.route),
  388: PokemonLocation('Ruta 218', PokemonLocationKind.route),
  389: PokemonLocation('Ruta 218', PokemonLocationKind.route),
  390: PokemonLocation('Ruta 218', PokemonLocationKind.route),
  391: PokemonLocation('Ruta 219', PokemonLocationKind.route),
  392: PokemonLocation('Ruta 221', PokemonLocationKind.route),
  393: PokemonLocation('Parque Compi'),
  394: PokemonLocation('Ruta 221', PokemonLocationKind.route),
  395: PokemonLocation('Ruta 222', PokemonLocationKind.route),
  396: PokemonLocation('Ruta 222', PokemonLocationKind.route),
  397: PokemonLocation('Ruta 222', PokemonLocationKind.route),
  398: PokemonLocation('Ruta 222', PokemonLocationKind.route),
  399: PokemonLocation('Ruta 224', PokemonLocationKind.route),
  400: PokemonLocation('Ruta 225', PokemonLocationKind.route),
  403: PokemonLocation('Ruta 227', PokemonLocationKind.route),
  406: PokemonLocation('Ruta 228', PokemonLocationKind.route),
  407: PokemonLocation('Ruta 229', PokemonLocationKind.route),
  411: PokemonLocation('Pueblo Hojaverde', PokemonLocationKind.city),
  412: PokemonLocation('Pueblo Hojaverde', PokemonLocationKind.city),
  413: PokemonLocation('Pueblo Hojaverde', PokemonLocationKind.city),
  414: PokemonLocation('Pueblo Hojaverde', PokemonLocationKind.city),
  415: PokemonLocation('Pueblo Hojaverde', PokemonLocationKind.city),
  416: PokemonLocation('Pueblo Hojaverde', PokemonLocationKind.city),
  417: PokemonLocation('Pueblo Hojaverde', PokemonLocationKind.city),
  418: PokemonLocation('Pueblo Arena', PokemonLocationKind.city),
  419: PokemonLocation('Pueblo Arena', PokemonLocationKind.city),
  420: PokemonLocation('Pueblo Arena', PokemonLocationKind.city),
  421: PokemonLocation('Pueblo Arena', PokemonLocationKind.city),
  422: PokemonLocation('Pueblo Arena', PokemonLocationKind.city),
  423: PokemonLocation('Pueblo Arena', PokemonLocationKind.city),
  424: PokemonLocation('Pueblo Arena', PokemonLocationKind.city),
  425: PokemonLocation('Pueblo Arena', PokemonLocationKind.city),
  426: PokemonLocation('Pueblo Aromaflor', PokemonLocationKind.city),
  427: PokemonLocation('Pueblo Aromaflor', PokemonLocationKind.city),
  428: PokemonLocation('Pueblo Aromaflor', PokemonLocationKind.city),
  429: PokemonLocation('Pueblo Aromaflor', PokemonLocationKind.city),
  431: PokemonLocation('Pueblo Aromaflor', PokemonLocationKind.city),
  432: PokemonLocation('Pueblo Aromaflor', PokemonLocationKind.city),
  433: PokemonLocation('Pueblo Sosiego', PokemonLocationKind.city),
  434: PokemonLocation('Pueblo Sosiego', PokemonLocationKind.city),
  435: PokemonLocation('Pueblo Sosiego', PokemonLocationKind.city),
  436: PokemonLocation('Pueblo Sosiego', PokemonLocationKind.city),
  438: PokemonLocation('Pueblo Sosiego', PokemonLocationKind.city),
  439: PokemonLocation('Pueblo Sosiego', PokemonLocationKind.city),
  440: PokemonLocation('Pueblo Sosiego', PokemonLocationKind.city),
  441: PokemonLocation('Pueblo Sosiego', PokemonLocationKind.city),
  442: PokemonLocation('Pueblo Caelestis', PokemonLocationKind.city),
  443: PokemonLocation('Pueblo Caelestis', PokemonLocationKind.city),
  444: PokemonLocation('Pueblo Caelestis', PokemonLocationKind.city),
  445: PokemonLocation('Pueblo Caelestis', PokemonLocationKind.city),
  446: PokemonLocation('Pueblo Caelestis', PokemonLocationKind.city),
  447: PokemonLocation('Pueblo Caelestis', PokemonLocationKind.city),
  448: PokemonLocation('Pueblo Caelestis', PokemonLocationKind.city),
  449: PokemonLocation('Pueblo Caelestis', PokemonLocationKind.city),
  450: PokemonLocation('Zona Sobrevivir', PokemonLocationKind.city),
  451: PokemonLocation('Zona Sobrevivir', PokemonLocationKind.city),
  452: PokemonLocation('Zona Sobrevivir', PokemonLocationKind.city),
  453: PokemonLocation('Zona Sobrevivir', PokemonLocationKind.city),
  455: PokemonLocation('Zona Sobrevivir', PokemonLocationKind.city),
  456: PokemonLocation('Zona Sobrevivir', PokemonLocationKind.city),
  457: PokemonLocation('Zona Descanso', PokemonLocationKind.city),
  458: PokemonLocation('Zona Descanso', PokemonLocationKind.city),
  459: PokemonLocation('Zona Descanso', PokemonLocationKind.city),
  460: PokemonLocation('Zona Descanso', PokemonLocationKind.city),
  461: PokemonLocation('Zona Descanso', PokemonLocationKind.city),
  462: PokemonLocation('Zona Descanso', PokemonLocationKind.city),
  463: PokemonLocation('Zona Descanso', PokemonLocationKind.city),
  465: PokemonLocation('Zona Descanso', PokemonLocationKind.city),
  467: PokemonLocation('Ruta 220', PokemonLocationKind.route),
  468: PokemonLocation('Ruta 223', PokemonLocationKind.route),
  469: PokemonLocation('Ruta 226', PokemonLocationKind.route),
  471: PokemonLocation('Ruta 230', PokemonLocationKind.route),
  474: PokemonLocation('Ciudad Jubileo', PokemonLocationKind.city),
  475: PokemonLocation('Ciudad Canal', PokemonLocationKind.city),
  476: PokemonLocation('Ciudad Pirita', PokemonLocationKind.city),
  477: PokemonLocation('Ciudad Vetusta', PokemonLocationKind.city),
  478: PokemonLocation('Ciudad Corazón', PokemonLocationKind.city),
  479: PokemonLocation('Ciudad Pradera', PokemonLocationKind.city),
  480: PokemonLocation('Ciudad Rocavelo', PokemonLocationKind.city),
  481: PokemonLocation('Ciudad Marina', PokemonLocationKind.city),
  482: PokemonLocation('Ciudad Puntaneva', PokemonLocationKind.city),
  483: PokemonLocation('Liga Pokémon', PokemonLocationKind.league),
  484: PokemonLocation('Zona Combate', PokemonLocationKind.city),
  485: PokemonLocation('Pueblo Arena', PokemonLocationKind.city),
  486: PokemonLocation('Pueblo Aromaflor', PokemonLocationKind.city),
  487: PokemonLocation('Pueblo Sosiego', PokemonLocationKind.city),
  488: PokemonLocation('Pueblo Caelestis', PokemonLocationKind.city),
  489: PokemonLocation('Zona Sobrevivir', PokemonLocationKind.city),
  490: PokemonLocation('Zona Descanso', PokemonLocationKind.city),
  491: PokemonLocation('Ciudad Canal', PokemonLocationKind.city),
  493: PokemonLocation('Torre Batalla'),
  494: PokemonLocation('Sede Galaxia'),
  495: PokemonLocation('Liga Pokémon', PokemonLocationKind.league),
  496: PokemonLocation('Liga Pokémon', PokemonLocationKind.league),
  497: PokemonLocation('Sede Galaxia'),
  498: PokemonLocation('Ruta 225', PokemonLocationKind.route),
  499: PokemonLocation('Ruta 226', PokemonLocationKind.route),
  500: PokemonLocation('Ruta 227', PokemonLocationKind.route),
  501: PokemonLocation('Ruta 228', PokemonLocationKind.route),
  502: PokemonLocation('Ruta 228', PokemonLocationKind.route),
  503: PokemonLocation('Ruta 228', PokemonLocationKind.route),
  504: PokemonLocation('Gran Pantano'),
  505: PokemonLocation('Gran Pantano'),
  506: PokemonLocation('Gran Pantano'),
  507: PokemonLocation('Gran Pantano'),
  508: PokemonLocation('Gran Pantano'),
  509: PokemonLocation('Gran Pantano'),
  514: PokemonLocation('Isla Hierro'),
  515: PokemonLocation('Ruinas Sosiego'),
  517: PokemonLocation('Ciudad Jubileo', PokemonLocationKind.city),
  518: PokemonLocation('Cueva Retorno'),
  519: PokemonLocation('Cueva Retorno'),
  520: PokemonLocation('Cueva Retorno'),
  521: PokemonLocation('Cueva Retorno'),
  522: PokemonLocation('Cueva Retorno'),
  523: PokemonLocation('Cueva Retorno'),
  524: PokemonLocation('Cueva Retorno'),
  525: PokemonLocation('Cueva Retorno'),
  526: PokemonLocation('Cueva Retorno'),
  527: PokemonLocation('Cueva Retorno'),
  528: PokemonLocation('Cueva Retorno'),
  529: PokemonLocation('Cueva Retorno'),
  530: PokemonLocation('Cueva Retorno'),
  531: PokemonLocation('Cueva Retorno'),
  532: PokemonLocation('Cueva Retorno'),
  559: PokemonLocation('Frente Batalla'),
  560: PokemonLocation('Zona Combate', PokemonLocationKind.city),
  569: PokemonLocation('Sede Galaxia'),
  573: PokemonLocation('Mundo Distorsión'),
  574: PokemonLocation('Mundo Distorsión'),
  575: PokemonLocation('Mundo Distorsión'),
  576: PokemonLocation('Mundo Distorsión'),
  577: PokemonLocation('Mundo Distorsión'),
  579: PokemonLocation('Mundo Distorsión'),
  580: PokemonLocation('Mundo Distorsión'),
  581: PokemonLocation('Mundo Distorsión'),
  582: PokemonLocation('Mundo Distorsión'),
  583: PokemonLocation('Cueva Retorno'),
  584: PokemonLocation('Columna Lanza'),
  585: PokemonLocation('Columna Lanza'),
  587: PokemonLocation('Isla Hierro'),
  589: PokemonLocation('Monte Corona'),
  591: PokemonLocation('Ruta 228', PokemonLocationKind.route),
};
