enum EmeraldTrainerKind {
  regular,
  rival,
  gymLeader,
  eliteFour,
  champion,
  specialTrainer,
  frontierBrain,
}

class EmeraldTrainerInfo {
  final String name;
  final String? spritePath;
  final EmeraldTrainerKind kind;

  const EmeraldTrainerInfo(this.name, this.kind, [this.spritePath]);
}

/// Resuelve los oponentes con identidad propia de Pokémon Esmeralda.
///
/// Los IDs proceden de `include/constants/opponents.h` de pret/pokeemerald.
/// Los IDs, nombres, clases y apariencias proceden de las tablas de
/// `pret/pokeemerald`. Los entrenadores corrientes comparten el sprite de su
/// clase, mientras los personajes especiales conservan su sprite individual.
final class EmeraldTrainerResolver {
  const EmeraldTrainerResolver._();

  static EmeraldTrainerInfo forTrainerId(int id) {
    final EmeraldTrainerInfo? special = _special[id];
    if (special != null) return special;

    if (id >= 770 && id <= 801) {
      final int firstBattleId = 265 + ((id - 770) ~/ 4);
      return _special[firstBattleId]!;
    }

    // Los Cerebros de la Frontera tienen un ID para el símbolo de plata
    // (805-811) y otro para el de oro (812-818).
    if (id >= 812 && id <= 818) {
      return _special[id - 7]!;
    }

    if (_brendanIds.contains(id)) {
      return const EmeraldTrainerInfo(
        'Rival Brendan',
        EmeraldTrainerKind.rival,
        'assets/sprites/characters/rivals/brendan_emerald.png',
      );
    }
    if (_mayIds.contains(id)) {
      return const EmeraldTrainerInfo(
        'Rival May',
        EmeraldTrainerKind.rival,
        'assets/sprites/characters/rivals/may_emerald.png',
      );
    }
    if (_wallyIds.contains(id)) {
      return const EmeraldTrainerInfo(
        'Rival Wally',
        EmeraldTrainerKind.rival,
        'assets/sprites/characters/rivals/wally_hoenn.png',
      );
    }

    if (id > 0 && id < _regular.length) {
      final _EmeraldRegularTrainer? trainer = _regular[id];
      if (trainer != null) {
        return _resolveRegularTrainer(trainer);

      }
    }

    return EmeraldTrainerInfo('Entrenador #$id', EmeraldTrainerKind.regular);
  }

  static EmeraldTrainerInfo _resolveRegularTrainer(
    _EmeraldRegularTrainer trainer,
  ) {
    final String? villainSprite = switch (trainer.spriteName) {
      'aqua_grunt_m' =>
        'assets/sprites/characters/villains/aqua/grunt_male.png',
      'aqua_grunt_f' =>
        'assets/sprites/characters/villains/aqua/grunt_female.png',
      'aqua_admin_m' => 'assets/sprites/characters/villains/aqua/matt.png',
      'aqua_admin_f' => 'assets/sprites/characters/villains/aqua/shelly.png',
      'aqua_leader_archie' =>
        'assets/sprites/characters/villains/aqua/archie.png',
      'magma_grunt_m' =>
        'assets/sprites/characters/villains/magma/grunt_male.png',
      'magma_grunt_f' =>
        'assets/sprites/characters/villains/magma/grunt_female.png',
      'magma_admin' => 'assets/sprites/characters/villains/magma/tabitha.png',
      'magma_leader_maxie' =>
        'assets/sprites/characters/villains/magma/maxie.png',
      _ => null,
    };

    if (villainSprite != null) {
      final String name = switch (trainer.spriteName) {
        'aqua_grunt_m' || 'aqua_grunt_f' => 'Recluta del Equipo Aqua',
        'magma_grunt_m' || 'magma_grunt_f' => 'Recluta del Equipo Magma',
        _ => '${trainer.className} ${trainer.name}',
      };
      return EmeraldTrainerInfo(
        name,
        EmeraldTrainerKind.regular,
        villainSprite,
      );
    }

    return EmeraldTrainerInfo(
      '${trainer.className} ${trainer.name}',
      EmeraldTrainerKind.regular,
      'assets/sprites/characters/trainers/gba/Hoenn/${trainer.spriteName}.png',
    );
  }

  static const List<_EmeraldRegularTrainer?> _regular =
      <_EmeraldRegularTrainer?>[
    null,
    _EmeraldRegularTrainer("Sawyer", "Montañero", "hiker"),
    _EmeraldRegularTrainer("Grunt", "Recluta Aqua", "aqua_grunt_m"),
    _EmeraldRegularTrainer("Grunt", "Recluta Aqua", "aqua_grunt_m"),
    _EmeraldRegularTrainer("Grunt", "Recluta Aqua", "aqua_grunt_m"),
    _EmeraldRegularTrainer("Grunt", "Recluta Aqua", "aqua_grunt_m"),
    _EmeraldRegularTrainer("Grunt", "Recluta Aqua", "aqua_grunt_m"),
    _EmeraldRegularTrainer("Grunt", "Recluta Aqua", "aqua_grunt_m"),
    _EmeraldRegularTrainer("Grunt", "Recluta Aqua", "aqua_grunt_m"),
    _EmeraldRegularTrainer("Gabrielle", "Criador Pokémon", "pokemon_breeder_female"),
    _EmeraldRegularTrainer("Grunt", "Recluta Aqua", "aqua_grunt_m"),
    _EmeraldRegularTrainer("Marcel", "Entrenador Guay", "cooltrainer_male"),
    _EmeraldRegularTrainer("Alberto", "Ornitólogo", "bird_keeper"),
    _EmeraldRegularTrainer("Ed", "Coleccionista", "collector"),
    _EmeraldRegularTrainer("Grunt", "Recluta Aqua", "aqua_grunt_f"),
    _EmeraldRegularTrainer("Declan", "Nadador", "swimmer_male"),
    _EmeraldRegularTrainer("Grunt", "Recluta Aqua", "aqua_grunt_m"),
    _EmeraldRegularTrainer("Grunt", "Recluta Aqua", "aqua_grunt_m"),
    _EmeraldRegularTrainer("Grunt", "Recluta Aqua", "aqua_grunt_m"),
    _EmeraldRegularTrainer("Grunt", "Recluta Aqua", "aqua_grunt_m"),
    _EmeraldRegularTrainer("Grunt", "Recluta Aqua", "aqua_grunt_m"),
    _EmeraldRegularTrainer("Grunt", "Recluta Aqua", "aqua_grunt_m"),
    _EmeraldRegularTrainer("Grunt", "Recluta Magma", "magma_grunt_m"),
    _EmeraldRegularTrainer("Grunt", "Recluta Aqua", "aqua_grunt_m"),
    _EmeraldRegularTrainer("Grunt", "Recluta Aqua", "aqua_grunt_m"),
    _EmeraldRegularTrainer("Grunt", "Recluta Aqua", "aqua_grunt_m"),
    _EmeraldRegularTrainer("Grunt", "Recluta Aqua", "aqua_grunt_f"),
    _EmeraldRegularTrainer("Grunt", "Recluta Aqua", "aqua_grunt_f"),
    _EmeraldRegularTrainer("Grunt", "Recluta Aqua", "aqua_grunt_f"),
    _EmeraldRegularTrainer("Fredrick", "Experto", "expert_male"),
    _EmeraldRegularTrainer("Matt", "Comandante Aqua", "aqua_admin_m"),
    _EmeraldRegularTrainer("Zander", "Karateka", "black_belt"),
    _EmeraldRegularTrainer("Shelly", "Comandante Aqua", "aqua_admin_f"),
    _EmeraldRegularTrainer("Shelly", "Comandante Aqua", "aqua_admin_f"),
    _EmeraldRegularTrainer("Archie", "Líder Aqua", "aqua_leader_archie"),
    _EmeraldRegularTrainer("Leah", "Bruja", "hex_maniac"),
    _EmeraldRegularTrainer("Daisy", "Dama Aroma", "aroma_lady"),
    _EmeraldRegularTrainer("Rose", "Dama Aroma", "aroma_lady"),
    _EmeraldRegularTrainer("Felix", "Entrenador Guay", "cooltrainer_male"),
    _EmeraldRegularTrainer("Violet", "Dama Aroma", "aroma_lady"),
    _EmeraldRegularTrainer("Rose", "Dama Aroma", "aroma_lady"),
    _EmeraldRegularTrainer("Rose", "Dama Aroma", "aroma_lady"),
    _EmeraldRegularTrainer("Rose", "Dama Aroma", "aroma_lady"),
    _EmeraldRegularTrainer("Rose", "Dama Aroma", "aroma_lady"),
    _EmeraldRegularTrainer("Dusty", "Ruinamaníaco", "ruin_maniac"),
    _EmeraldRegularTrainer("Chip", "Ruinamaníaco", "ruin_maniac"),
    _EmeraldRegularTrainer("Foster", "Ruinamaníaco", "ruin_maniac"),
    _EmeraldRegularTrainer("Dusty", "Ruinamaníaco", "ruin_maniac"),
    _EmeraldRegularTrainer("Dusty", "Ruinamaníaco", "ruin_maniac"),
    _EmeraldRegularTrainer("Dusty", "Ruinamaníaco", "ruin_maniac"),
    _EmeraldRegularTrainer("Dusty", "Ruinamaníaco", "ruin_maniac"),
    _EmeraldRegularTrainer("Gabby & Ty", "Reporteros", "interviewers"),
    _EmeraldRegularTrainer("Gabby & Ty", "Reporteros", "interviewers"),
    _EmeraldRegularTrainer("Gabby & Ty", "Reporteros", "interviewers"),
    _EmeraldRegularTrainer("Gabby & Ty", "Reporteros", "interviewers"),
    _EmeraldRegularTrainer("Gabby & Ty", "Reporteros", "interviewers"),
    _EmeraldRegularTrainer("Gabby & Ty", "Reporteros", "interviewers"),
    _EmeraldRegularTrainer("Lola", "Niña Bien", "tuber_female"),
    _EmeraldRegularTrainer("Austina", "Niña Bien", "tuber_female"),
    _EmeraldRegularTrainer("Gwen", "Niña Bien", "tuber_female"),
    _EmeraldRegularTrainer("Lola", "Niña Bien", "tuber_female"),
    _EmeraldRegularTrainer("Lola", "Niña Bien", "tuber_female"),
    _EmeraldRegularTrainer("Lola", "Niña Bien", "tuber_female"),
    _EmeraldRegularTrainer("Lola", "Niña Bien", "tuber_female"),
    _EmeraldRegularTrainer("Ricky", "Niño Bien", "tuber_male"),
    _EmeraldRegularTrainer("Simon", "Niño Bien", "tuber_male"),
    _EmeraldRegularTrainer("Charlie", "Niño Bien", "tuber_male"),
    _EmeraldRegularTrainer("Ricky", "Niño Bien", "tuber_male"),
    _EmeraldRegularTrainer("Ricky", "Niño Bien", "tuber_male"),
    _EmeraldRegularTrainer("Ricky", "Niño Bien", "tuber_male"),
    _EmeraldRegularTrainer("Ricky", "Niño Bien", "tuber_male"),
    _EmeraldRegularTrainer("Randall", "Entrenador Guay", "cooltrainer_male"),
    _EmeraldRegularTrainer("Parker", "Entrenador Guay", "cooltrainer_male"),
    _EmeraldRegularTrainer("George", "Entrenador Guay", "cooltrainer_male"),
    _EmeraldRegularTrainer("Berke", "Entrenador Guay", "cooltrainer_male"),
    _EmeraldRegularTrainer("Braxton", "Entrenador Guay", "cooltrainer_male"),
    _EmeraldRegularTrainer("Vincent", "Entrenador Guay", "cooltrainer_male"),
    _EmeraldRegularTrainer("Leroy", "Entrenador Guay", "cooltrainer_male"),
    _EmeraldRegularTrainer("Wilton", "Entrenador Guay", "cooltrainer_male"),
    _EmeraldRegularTrainer("Edgar", "Entrenador Guay", "cooltrainer_male"),
    _EmeraldRegularTrainer("Albert", "Entrenador Guay", "cooltrainer_male"),
    _EmeraldRegularTrainer("Samuel", "Entrenador Guay", "cooltrainer_male"),
    _EmeraldRegularTrainer("Vito", "Entrenador Guay", "cooltrainer_male"),
    _EmeraldRegularTrainer("Owen", "Entrenador Guay", "cooltrainer_male"),
    _EmeraldRegularTrainer("Wilton", "Entrenador Guay", "cooltrainer_male"),
    _EmeraldRegularTrainer("Wilton", "Entrenador Guay", "cooltrainer_male"),
    _EmeraldRegularTrainer("Wilton", "Entrenador Guay", "cooltrainer_male"),
    _EmeraldRegularTrainer("Wilton", "Entrenador Guay", "cooltrainer_male"),
    _EmeraldRegularTrainer("Warren", "Entrenador Guay", "cooltrainer_male"),
    _EmeraldRegularTrainer("Mary", "Entrenador Guay", "cooltrainer_female"),
    _EmeraldRegularTrainer("Alexia", "Entrenador Guay", "cooltrainer_female"),
    _EmeraldRegularTrainer("Jody", "Entrenador Guay", "cooltrainer_female"),
    _EmeraldRegularTrainer("Wendy", "Entrenador Guay", "cooltrainer_female"),
    _EmeraldRegularTrainer("Keira", "Entrenador Guay", "cooltrainer_female"),
    _EmeraldRegularTrainer("Brooke", "Entrenador Guay", "cooltrainer_female"),
    _EmeraldRegularTrainer("Jennifer", "Entrenador Guay", "cooltrainer_female"),
    _EmeraldRegularTrainer("Hope", "Entrenador Guay", "cooltrainer_female"),
    _EmeraldRegularTrainer("Shannon", "Entrenador Guay", "cooltrainer_female"),
    _EmeraldRegularTrainer("Michelle", "Entrenador Guay", "cooltrainer_female"),
    _EmeraldRegularTrainer("Caroline", "Entrenador Guay", "cooltrainer_female"),
    _EmeraldRegularTrainer("Julie", "Entrenador Guay", "cooltrainer_female"),
    _EmeraldRegularTrainer("Brooke", "Entrenador Guay", "cooltrainer_female"),
    _EmeraldRegularTrainer("Brooke", "Entrenador Guay", "cooltrainer_female"),
    _EmeraldRegularTrainer("Brooke", "Entrenador Guay", "cooltrainer_female"),
    _EmeraldRegularTrainer("Brooke", "Entrenador Guay", "cooltrainer_female"),
    _EmeraldRegularTrainer("Patricia", "Bruja", "hex_maniac"),
    _EmeraldRegularTrainer("Kindra", "Bruja", "hex_maniac"),
    _EmeraldRegularTrainer("Tammy", "Bruja", "hex_maniac"),
    _EmeraldRegularTrainer("Valerie", "Bruja", "hex_maniac"),
    _EmeraldRegularTrainer("Tasha", "Bruja", "hex_maniac"),
    _EmeraldRegularTrainer("Valerie", "Bruja", "hex_maniac"),
    _EmeraldRegularTrainer("Valerie", "Bruja", "hex_maniac"),
    _EmeraldRegularTrainer("Valerie", "Bruja", "hex_maniac"),
    _EmeraldRegularTrainer("Valerie", "Bruja", "hex_maniac"),
    _EmeraldRegularTrainer("Cindy", "Dama", "lady"),
    _EmeraldRegularTrainer("Daphne", "Dama", "lady"),
    _EmeraldRegularTrainer("Grunt", "Recluta Magma", "magma_grunt_m"),
    _EmeraldRegularTrainer("Cindy", "Dama", "lady"),
    _EmeraldRegularTrainer("Brianna", "Dama", "lady"),
    _EmeraldRegularTrainer("Naomi", "Dama", "lady"),
    _EmeraldRegularTrainer("Cindy", "Dama", "lady"),
    _EmeraldRegularTrainer("Cindy", "Dama", "lady"),
    _EmeraldRegularTrainer("Cindy", "Dama", "lady"),
    _EmeraldRegularTrainer("Cindy", "Dama", "lady"),
    _EmeraldRegularTrainer("Melissa", "Bella", "beauty"),
    _EmeraldRegularTrainer("Sheila", "Bella", "beauty"),
    _EmeraldRegularTrainer("Shirley", "Bella", "beauty"),
    _EmeraldRegularTrainer("Jessica", "Bella", "beauty"),
    _EmeraldRegularTrainer("Connie", "Bella", "beauty"),
    _EmeraldRegularTrainer("Bridget", "Bella", "beauty"),
    _EmeraldRegularTrainer("Olivia", "Bella", "beauty"),
    _EmeraldRegularTrainer("Tiffany", "Bella", "beauty"),
    _EmeraldRegularTrainer("Jessica", "Bella", "beauty"),
    _EmeraldRegularTrainer("Jessica", "Bella", "beauty"),
    _EmeraldRegularTrainer("Jessica", "Bella", "beauty"),
    _EmeraldRegularTrainer("Jessica", "Bella", "beauty"),
    _EmeraldRegularTrainer("Winston", "Niño Rico", "rich_boy"),
    _EmeraldRegularTrainer("Mollie", "Experto", "expert_female"),
    _EmeraldRegularTrainer("Garret", "Niño Rico", "rich_boy"),
    _EmeraldRegularTrainer("Winston", "Niño Rico", "rich_boy"),
    _EmeraldRegularTrainer("Winston", "Niño Rico", "rich_boy"),
    _EmeraldRegularTrainer("Winston", "Niño Rico", "rich_boy"),
    _EmeraldRegularTrainer("Winston", "Niño Rico", "rich_boy"),
    _EmeraldRegularTrainer("Steve", "Pokémaníaco", "pokemaniac"),
    _EmeraldRegularTrainer("Thalia", "Bella", "beauty"),
    _EmeraldRegularTrainer("Mark", "Pokémaníaco", "pokemaniac"),
    _EmeraldRegularTrainer("Grunt", "Recluta Magma", "magma_grunt_f"),
    _EmeraldRegularTrainer("Steve", "Pokémaníaco", "pokemaniac"),
    _EmeraldRegularTrainer("Steve", "Pokémaníaco", "pokemaniac"),
    _EmeraldRegularTrainer("Steve", "Pokémaníaco", "pokemaniac"),
    _EmeraldRegularTrainer("Steve", "Pokémaníaco", "pokemaniac"),
    _EmeraldRegularTrainer("Luis", "Nadador", "swimmer_male"),
    _EmeraldRegularTrainer("Dominik", "Nadador", "swimmer_male"),
    _EmeraldRegularTrainer("Douglas", "Nadador", "swimmer_male"),
    _EmeraldRegularTrainer("Darrin", "Nadador", "swimmer_male"),
    _EmeraldRegularTrainer("Tony", "Nadador", "swimmer_male"),
    _EmeraldRegularTrainer("Jerome", "Nadador", "swimmer_male"),
    _EmeraldRegularTrainer("Matthew", "Nadador", "swimmer_male"),
    _EmeraldRegularTrainer("David", "Nadador", "swimmer_male"),
    _EmeraldRegularTrainer("Spencer", "Nadador", "swimmer_male"),
    _EmeraldRegularTrainer("Roland", "Nadador", "swimmer_male"),
    _EmeraldRegularTrainer("Nolen", "Nadador", "swimmer_male"),
    _EmeraldRegularTrainer("Stan", "Nadador", "swimmer_male"),
    _EmeraldRegularTrainer("Barry", "Nadador", "swimmer_male"),
    _EmeraldRegularTrainer("Dean", "Nadador", "swimmer_male"),
    _EmeraldRegularTrainer("Rodney", "Nadador", "swimmer_male"),
    _EmeraldRegularTrainer("Richard", "Nadador", "swimmer_male"),
    _EmeraldRegularTrainer("Herman", "Nadador", "swimmer_male"),
    _EmeraldRegularTrainer("Santiago", "Nadador", "swimmer_male"),
    _EmeraldRegularTrainer("Gilbert", "Nadador", "swimmer_male"),
    _EmeraldRegularTrainer("Franklin", "Nadador", "swimmer_male"),
    _EmeraldRegularTrainer("Kevin", "Nadador", "swimmer_male"),
    _EmeraldRegularTrainer("Jack", "Nadador", "swimmer_male"),
    _EmeraldRegularTrainer("Dudley", "Nadador", "swimmer_male"),
    _EmeraldRegularTrainer("Chad", "Nadador", "swimmer_male"),
    _EmeraldRegularTrainer("Tony", "Nadador", "swimmer_male"),
    _EmeraldRegularTrainer("Tony", "Nadador", "swimmer_male"),
    _EmeraldRegularTrainer("Tony", "Nadador", "swimmer_male"),
    _EmeraldRegularTrainer("Tony", "Nadador", "swimmer_male"),
    _EmeraldRegularTrainer("Takao", "Karateka", "black_belt"),
    _EmeraldRegularTrainer("Hitoshi", "Karateka", "black_belt"),
    _EmeraldRegularTrainer("Kiyo", "Karateka", "black_belt"),
    _EmeraldRegularTrainer("Koichi", "Karateka", "black_belt"),
    _EmeraldRegularTrainer("Nob", "Karateka", "black_belt"),
    _EmeraldRegularTrainer("Nob", "Karateka", "black_belt"),
    _EmeraldRegularTrainer("Nob", "Karateka", "black_belt"),
    _EmeraldRegularTrainer("Nob", "Karateka", "black_belt"),
    _EmeraldRegularTrainer("Nob", "Karateka", "black_belt"),
    _EmeraldRegularTrainer("Yuji", "Karateka", "black_belt"),
    _EmeraldRegularTrainer("Daisuke", "Karateka", "black_belt"),
    _EmeraldRegularTrainer("Atsushi", "Karateka", "black_belt"),
    _EmeraldRegularTrainer("Kirk", "Guitarrista", "guitarist"),
    _EmeraldRegularTrainer("Grunt", "Recluta Aqua", "aqua_grunt_f"),
    _EmeraldRegularTrainer("Grunt", "Recluta Aqua", "aqua_grunt_m"),
    _EmeraldRegularTrainer("Shawn", "Guitarrista", "guitarist"),
    _EmeraldRegularTrainer("Fernando", "Guitarrista", "guitarist"),
    _EmeraldRegularTrainer("Dalton", "Guitarrista", "guitarist"),
    _EmeraldRegularTrainer("Dalton", "Guitarrista", "guitarist"),
    _EmeraldRegularTrainer("Dalton", "Guitarrista", "guitarist"),
    _EmeraldRegularTrainer("Dalton", "Guitarrista", "guitarist"),
    _EmeraldRegularTrainer("Dalton", "Guitarrista", "guitarist"),
    _EmeraldRegularTrainer("Cole", "Prendefuegos", "kindler"),
    _EmeraldRegularTrainer("Jeff", "Prendefuegos", "kindler"),
    _EmeraldRegularTrainer("Axle", "Prendefuegos", "kindler"),
    _EmeraldRegularTrainer("Jace", "Prendefuegos", "kindler"),
    _EmeraldRegularTrainer("Keegan", "Prendefuegos", "kindler"),
    _EmeraldRegularTrainer("Bernie", "Prendefuegos", "kindler"),
    _EmeraldRegularTrainer("Bernie", "Prendefuegos", "kindler"),
    _EmeraldRegularTrainer("Bernie", "Prendefuegos", "kindler"),
    _EmeraldRegularTrainer("Bernie", "Prendefuegos", "kindler"),
    _EmeraldRegularTrainer("Bernie", "Prendefuegos", "kindler"),
    _EmeraldRegularTrainer("Drew", "Campista", "camper"),
    _EmeraldRegularTrainer("Beau", "Campista", "camper"),
    _EmeraldRegularTrainer("Larry", "Campista", "camper"),
    _EmeraldRegularTrainer("Shane", "Campista", "camper"),
    _EmeraldRegularTrainer("Justin", "Campista", "camper"),
    _EmeraldRegularTrainer("Ethan", "Campista", "camper"),
    _EmeraldRegularTrainer("Autumn", "Dominguera", "picnicker"),
    _EmeraldRegularTrainer("Travis", "Campista", "camper"),
    _EmeraldRegularTrainer("Ethan", "Campista", "camper"),
    _EmeraldRegularTrainer("Ethan", "Campista", "camper"),
    _EmeraldRegularTrainer("Ethan", "Campista", "camper"),
    _EmeraldRegularTrainer("Ethan", "Campista", "camper"),
    _EmeraldRegularTrainer("Brent", "Bichomaníaco", "bug_maniac"),
    _EmeraldRegularTrainer("Donald", "Bichomaníaco", "bug_maniac"),
    _EmeraldRegularTrainer("Taylor", "Bichomaníaco", "bug_maniac"),
    _EmeraldRegularTrainer("Jeffrey", "Bichomaníaco", "bug_maniac"),
    _EmeraldRegularTrainer("Derek", "Bichomaníaco", "bug_maniac"),
    _EmeraldRegularTrainer("Jeffrey", "Bichomaníaco", "bug_maniac"),
    _EmeraldRegularTrainer("Jeffrey", "Bichomaníaco", "bug_maniac"),
    _EmeraldRegularTrainer("Jeffrey", "Bichomaníaco", "bug_maniac"),
    _EmeraldRegularTrainer("Jeffrey", "Bichomaníaco", "bug_maniac"),
    _EmeraldRegularTrainer("Edward", "Médium", "psychic_male"),
    _EmeraldRegularTrainer("Preston", "Médium", "psychic_male"),
    _EmeraldRegularTrainer("Virgil", "Médium", "psychic_male"),
    _EmeraldRegularTrainer("Blake", "Médium", "psychic_male"),
    _EmeraldRegularTrainer("William", "Médium", "psychic_male"),
    _EmeraldRegularTrainer("Joshua", "Médium", "psychic_male"),
    _EmeraldRegularTrainer("Cameron", "Médium", "psychic_male"),
    _EmeraldRegularTrainer("Cameron", "Médium", "psychic_male"),
    _EmeraldRegularTrainer("Cameron", "Médium", "psychic_male"),
    _EmeraldRegularTrainer("Cameron", "Médium", "psychic_male"),
    _EmeraldRegularTrainer("Cameron", "Médium", "psychic_male"),
    _EmeraldRegularTrainer("Jaclyn", "Médium", "psychic_female"),
    _EmeraldRegularTrainer("Hannah", "Médium", "psychic_female"),
    _EmeraldRegularTrainer("Samantha", "Médium", "psychic_female"),
    _EmeraldRegularTrainer("Maura", "Médium", "psychic_female"),
    _EmeraldRegularTrainer("Kayla", "Médium", "psychic_female"),
    _EmeraldRegularTrainer("Alexis", "Médium", "psychic_female"),
    _EmeraldRegularTrainer("Jacki", "Médium", "psychic_female"),
    _EmeraldRegularTrainer("Jacki", "Médium", "psychic_female"),
    _EmeraldRegularTrainer("Jacki", "Médium", "psychic_female"),
    _EmeraldRegularTrainer("Jacki", "Médium", "psychic_female"),
    _EmeraldRegularTrainer("Jacki", "Médium", "psychic_female"),
    _EmeraldRegularTrainer("Walter", "Caballero", "gentleman"),
    _EmeraldRegularTrainer("Micah", "Caballero", "gentleman"),
    _EmeraldRegularTrainer("Thomas", "Caballero", "gentleman"),
    _EmeraldRegularTrainer("Walter", "Caballero", "gentleman"),
    _EmeraldRegularTrainer("Walter", "Caballero", "gentleman"),
    _EmeraldRegularTrainer("Walter", "Caballero", "gentleman"),
    _EmeraldRegularTrainer("Walter", "Caballero", "gentleman"),
    _EmeraldRegularTrainer("Sidney", "Alto Mando", "elite_four_sidney"),
    _EmeraldRegularTrainer("Phoebe", "Alto Mando", "elite_four_phoebe"),
    _EmeraldRegularTrainer("Glacia", "Alto Mando", "elite_four_glacia"),
    _EmeraldRegularTrainer("Drake", "Alto Mando", "elite_four_drake"),
    _EmeraldRegularTrainer("Roxanne", "Líder", "leader_roxanne"),
    _EmeraldRegularTrainer("Brawly", "Líder", "leader_brawly"),
    _EmeraldRegularTrainer("Wattson", "Líder", "leader_wattson"),
    _EmeraldRegularTrainer("Flannery", "Líder", "leader_flannery"),
    _EmeraldRegularTrainer("Norman", "Líder", "leader_norman"),
    _EmeraldRegularTrainer("Winona", "Líder", "leader_winona"),
    _EmeraldRegularTrainer("Tate&liza", "Líder", "leader_tate_and_liza"),
    _EmeraldRegularTrainer("Juan", "Líder", "leader_juan"),
    _EmeraldRegularTrainer("Jerry", "Escolar", "school_kid_male"),
    _EmeraldRegularTrainer("Ted", "Escolar", "school_kid_male"),
    _EmeraldRegularTrainer("Paul", "Escolar", "school_kid_male"),
    _EmeraldRegularTrainer("Jerry", "Escolar", "school_kid_male"),
    _EmeraldRegularTrainer("Jerry", "Escolar", "school_kid_male"),
    _EmeraldRegularTrainer("Jerry", "Escolar", "school_kid_male"),
    _EmeraldRegularTrainer("Jerry", "Escolar", "school_kid_male"),
    _EmeraldRegularTrainer("Karen", "Escolar", "school_kid_female"),
    _EmeraldRegularTrainer("Georgia", "Escolar", "school_kid_female"),
    _EmeraldRegularTrainer("Karen", "Escolar", "school_kid_female"),
    _EmeraldRegularTrainer("Karen", "Escolar", "school_kid_female"),
    _EmeraldRegularTrainer("Karen", "Escolar", "school_kid_female"),
    _EmeraldRegularTrainer("Karen", "Escolar", "school_kid_female"),
    _EmeraldRegularTrainer("Kate & Joy", "Senior y Junior", "students"),
    _EmeraldRegularTrainer("Anna & Meg", "Senior y Junior", "students"),
    _EmeraldRegularTrainer("Anna & Meg", "Senior y Junior", "students"),
    _EmeraldRegularTrainer("Anna & Meg", "Senior y Junior", "students"),
    _EmeraldRegularTrainer("Anna & Meg", "Senior y Junior", "students"),
    _EmeraldRegularTrainer("Anna & Meg", "Senior y Junior", "students"),
    _EmeraldRegularTrainer("Victor", "Familia Estratega", "pokefan_male"),
    _EmeraldRegularTrainer("Miguel", "Pokéfan", "pokefan_male"),
    _EmeraldRegularTrainer("Colton", "Pokéfan", "pokefan_male"),
    _EmeraldRegularTrainer("Miguel", "Pokéfan", "pokefan_male"),
    _EmeraldRegularTrainer("Miguel", "Pokéfan", "pokefan_male"),
    _EmeraldRegularTrainer("Miguel", "Pokéfan", "pokefan_male"),
    _EmeraldRegularTrainer("Miguel", "Pokéfan", "pokefan_male"),
    _EmeraldRegularTrainer("Victoria", "Familia Estratega", "pokefan_female"),
    _EmeraldRegularTrainer("Vanessa", "Pokéfan", "pokefan_female"),
    _EmeraldRegularTrainer("Bethany", "Pokéfan", "pokefan_female"),
    _EmeraldRegularTrainer("Isabel", "Pokéfan", "pokefan_female"),
    _EmeraldRegularTrainer("Isabel", "Pokéfan", "pokefan_female"),
    _EmeraldRegularTrainer("Isabel", "Pokéfan", "pokefan_female"),
    _EmeraldRegularTrainer("Isabel", "Pokéfan", "pokefan_female"),
    _EmeraldRegularTrainer("Isabel", "Pokéfan", "pokefan_female"),
    _EmeraldRegularTrainer("Timothy", "Experto", "expert_male"),
    _EmeraldRegularTrainer("Timothy", "Experto", "expert_male"),
    _EmeraldRegularTrainer("Timothy", "Experto", "expert_male"),
    _EmeraldRegularTrainer("Timothy", "Experto", "expert_male"),
    _EmeraldRegularTrainer("Timothy", "Experto", "expert_male"),
    _EmeraldRegularTrainer("Vicky", "Familia Estratega", "expert_female"),
    _EmeraldRegularTrainer("Shelby", "Experto", "expert_female"),
    _EmeraldRegularTrainer("Shelby", "Experto", "expert_female"),
    _EmeraldRegularTrainer("Shelby", "Experto", "expert_female"),
    _EmeraldRegularTrainer("Shelby", "Experto", "expert_female"),
    _EmeraldRegularTrainer("Shelby", "Experto", "expert_female"),
    _EmeraldRegularTrainer("Calvin", "Joven", "youngster"),
    _EmeraldRegularTrainer("Billy", "Joven", "youngster"),
    _EmeraldRegularTrainer("Josh", "Joven", "youngster"),
    _EmeraldRegularTrainer("Tommy", "Joven", "youngster"),
    _EmeraldRegularTrainer("Joey", "Joven", "youngster"),
    _EmeraldRegularTrainer("Ben", "Joven", "youngster"),
    _EmeraldRegularTrainer("Quincy", "Entrenador Guay", "cooltrainer_male"),
    _EmeraldRegularTrainer("Katelynn", "Entrenador Guay", "cooltrainer_female"),
    _EmeraldRegularTrainer("Jaylen", "Joven", "youngster"),
    _EmeraldRegularTrainer("Dillon", "Joven", "youngster"),
    _EmeraldRegularTrainer("Calvin", "Joven", "youngster"),
    _EmeraldRegularTrainer("Calvin", "Joven", "youngster"),
    _EmeraldRegularTrainer("Calvin", "Joven", "youngster"),
    _EmeraldRegularTrainer("Calvin", "Joven", "youngster"),
    _EmeraldRegularTrainer("Eddie", "Joven", "youngster"),
    _EmeraldRegularTrainer("Allen", "Joven", "youngster"),
    _EmeraldRegularTrainer("Timmy", "Joven", "youngster"),
    _EmeraldRegularTrainer("Wallace", "Campeón", "champion_wallace"),
    _EmeraldRegularTrainer("Andrew", "Pescador", "fisherman"),
    _EmeraldRegularTrainer("Ivan", "Pescador", "fisherman"),
    _EmeraldRegularTrainer("Claude", "Pescador", "fisherman"),
    _EmeraldRegularTrainer("Elliot", "Pescador", "fisherman"),
    _EmeraldRegularTrainer("Ned", "Pescador", "fisherman"),
    _EmeraldRegularTrainer("Dale", "Pescador", "fisherman"),
    _EmeraldRegularTrainer("Nolan", "Pescador", "fisherman"),
    _EmeraldRegularTrainer("Barny", "Pescador", "fisherman"),
    _EmeraldRegularTrainer("Wade", "Pescador", "fisherman"),
    _EmeraldRegularTrainer("Carter", "Pescador", "fisherman"),
    _EmeraldRegularTrainer("Elliot", "Pescador", "fisherman"),
    _EmeraldRegularTrainer("Elliot", "Pescador", "fisherman"),
    _EmeraldRegularTrainer("Elliot", "Pescador", "fisherman"),
    _EmeraldRegularTrainer("Elliot", "Pescador", "fisherman"),
    _EmeraldRegularTrainer("Ronald", "Pescador", "fisherman"),
    _EmeraldRegularTrainer("Jacob", "Triatleta", "triathlete_cycling_male"),
    _EmeraldRegularTrainer("Anthony", "Triatleta", "triathlete_cycling_male"),
    _EmeraldRegularTrainer("Benjamin", "Triatleta", "triathlete_cycling_male"),
    _EmeraldRegularTrainer("Benjamin", "Triatleta", "triathlete_cycling_male"),
    _EmeraldRegularTrainer("Benjamin", "Triatleta", "triathlete_cycling_male"),
    _EmeraldRegularTrainer("Benjamin", "Triatleta", "triathlete_cycling_male"),
    _EmeraldRegularTrainer("Benjamin", "Triatleta", "triathlete_cycling_male"),
    _EmeraldRegularTrainer("Abigail", "Triatleta", "triathlete_cycling_female"),
    _EmeraldRegularTrainer("Jasmine", "Triatleta", "triathlete_cycling_female"),
    _EmeraldRegularTrainer("Abigail", "Triatleta", "triathlete_cycling_female"),
    _EmeraldRegularTrainer("Abigail", "Triatleta", "triathlete_cycling_female"),
    _EmeraldRegularTrainer("Abigail", "Triatleta", "triathlete_cycling_female"),
    _EmeraldRegularTrainer("Abigail", "Triatleta", "triathlete_cycling_female"),
    _EmeraldRegularTrainer("Dylan", "Triatleta", "triathlete_running_male"),
    _EmeraldRegularTrainer("Dylan", "Triatleta", "triathlete_running_male"),
    _EmeraldRegularTrainer("Dylan", "Triatleta", "triathlete_running_male"),
    _EmeraldRegularTrainer("Dylan", "Triatleta", "triathlete_running_male"),
    _EmeraldRegularTrainer("Dylan", "Triatleta", "triathlete_running_male"),
    _EmeraldRegularTrainer("Maria", "Triatleta", "triathlete_running_female"),
    _EmeraldRegularTrainer("Maria", "Triatleta", "triathlete_running_female"),
    _EmeraldRegularTrainer("Maria", "Triatleta", "triathlete_running_female"),
    _EmeraldRegularTrainer("Maria", "Triatleta", "triathlete_running_female"),
    _EmeraldRegularTrainer("Maria", "Triatleta", "triathlete_running_female"),
    _EmeraldRegularTrainer("Camden", "Triatleta", "triathlete_swimming_male"),
    _EmeraldRegularTrainer("Demetrius", "Joven", "youngster"),
    _EmeraldRegularTrainer("Isaiah", "Triatleta", "triathlete_swimming_male"),
    _EmeraldRegularTrainer("Pablo", "Triatleta", "triathlete_swimming_male"),
    _EmeraldRegularTrainer("Chase", "Triatleta", "triathlete_swimming_male"),
    _EmeraldRegularTrainer("Isaiah", "Triatleta", "triathlete_swimming_male"),
    _EmeraldRegularTrainer("Isaiah", "Triatleta", "triathlete_swimming_male"),
    _EmeraldRegularTrainer("Isaiah", "Triatleta", "triathlete_swimming_male"),
    _EmeraldRegularTrainer("Isaiah", "Triatleta", "triathlete_swimming_male"),
    _EmeraldRegularTrainer("Isobel", "Triatleta", "triathlete_swimming_female"),
    _EmeraldRegularTrainer("Donny", "Triatleta", "triathlete_swimming_female"),
    _EmeraldRegularTrainer("Talia", "Triatleta", "triathlete_swimming_female"),
    _EmeraldRegularTrainer("Katelyn", "Triatleta", "triathlete_swimming_female"),
    _EmeraldRegularTrainer("Allison", "Triatleta", "triathlete_swimming_female"),
    _EmeraldRegularTrainer("Katelyn", "Triatleta", "triathlete_swimming_female"),
    _EmeraldRegularTrainer("Katelyn", "Triatleta", "triathlete_swimming_female"),
    _EmeraldRegularTrainer("Katelyn", "Triatleta", "triathlete_swimming_female"),
    _EmeraldRegularTrainer("Katelyn", "Triatleta", "triathlete_swimming_female"),
    _EmeraldRegularTrainer("Nicolas", "Domadragones", "dragon_tamer"),
    _EmeraldRegularTrainer("Nicolas", "Domadragones", "dragon_tamer"),
    _EmeraldRegularTrainer("Nicolas", "Domadragones", "dragon_tamer"),
    _EmeraldRegularTrainer("Nicolas", "Domadragones", "dragon_tamer"),
    _EmeraldRegularTrainer("Nicolas", "Domadragones", "dragon_tamer"),
    _EmeraldRegularTrainer("Aaron", "Domadragones", "dragon_tamer"),
    _EmeraldRegularTrainer("Perry", "Ornitólogo", "bird_keeper"),
    _EmeraldRegularTrainer("Hugh", "Ornitólogo", "bird_keeper"),
    _EmeraldRegularTrainer("Phil", "Ornitólogo", "bird_keeper"),
    _EmeraldRegularTrainer("Jared", "Ornitólogo", "bird_keeper"),
    _EmeraldRegularTrainer("Humberto", "Ornitólogo", "bird_keeper"),
    _EmeraldRegularTrainer("Presley", "Ornitólogo", "bird_keeper"),
    _EmeraldRegularTrainer("Edwardo", "Ornitólogo", "bird_keeper"),
    _EmeraldRegularTrainer("Colin", "Ornitólogo", "bird_keeper"),
    _EmeraldRegularTrainer("Robert", "Ornitólogo", "bird_keeper"),
    _EmeraldRegularTrainer("Benny", "Ornitólogo", "bird_keeper"),
    _EmeraldRegularTrainer("Chester", "Ornitólogo", "bird_keeper"),
    _EmeraldRegularTrainer("Robert", "Ornitólogo", "bird_keeper"),
    _EmeraldRegularTrainer("Robert", "Ornitólogo", "bird_keeper"),
    _EmeraldRegularTrainer("Robert", "Ornitólogo", "bird_keeper"),
    _EmeraldRegularTrainer("Robert", "Ornitólogo", "bird_keeper"),
    _EmeraldRegularTrainer("Alex", "Ornitólogo", "bird_keeper"),
    _EmeraldRegularTrainer("Beck", "Ornitólogo", "bird_keeper"),
    _EmeraldRegularTrainer("Yasu", "Niño Ninja", "ninja_boy"),
    _EmeraldRegularTrainer("Takashi", "Niño Ninja", "ninja_boy"),
    _EmeraldRegularTrainer("Dianne", "Entrenador Guay", "cooltrainer_female"),
    _EmeraldRegularTrainer("Jani", "Niña Bien", "tuber_female"),
    _EmeraldRegularTrainer("Lao", "Niño Ninja", "ninja_boy"),
    _EmeraldRegularTrainer("Lung", "Niño Ninja", "ninja_boy"),
    _EmeraldRegularTrainer("Lao", "Niño Ninja", "ninja_boy"),
    _EmeraldRegularTrainer("Lao", "Niño Ninja", "ninja_boy"),
    _EmeraldRegularTrainer("Lao", "Niño Ninja", "ninja_boy"),
    _EmeraldRegularTrainer("Lao", "Niño Ninja", "ninja_boy"),
    _EmeraldRegularTrainer("Jocelyn", "Luchadora", "battle_girl"),
    _EmeraldRegularTrainer("Laura", "Luchadora", "battle_girl"),
    _EmeraldRegularTrainer("Cyndy", "Luchadora", "battle_girl"),
    _EmeraldRegularTrainer("Cora", "Luchadora", "battle_girl"),
    _EmeraldRegularTrainer("Paula", "Luchadora", "battle_girl"),
    _EmeraldRegularTrainer("Cyndy", "Luchadora", "battle_girl"),
    _EmeraldRegularTrainer("Cyndy", "Luchadora", "battle_girl"),
    _EmeraldRegularTrainer("Cyndy", "Luchadora", "battle_girl"),
    _EmeraldRegularTrainer("Cyndy", "Luchadora", "battle_girl"),
    _EmeraldRegularTrainer("Madeline", "Dama Sombrilla", "parasol_lady"),
    _EmeraldRegularTrainer("Clarissa", "Dama Sombrilla", "parasol_lady"),
    _EmeraldRegularTrainer("Angelica", "Dama Sombrilla", "parasol_lady"),
    _EmeraldRegularTrainer("Madeline", "Dama Sombrilla", "parasol_lady"),
    _EmeraldRegularTrainer("Madeline", "Dama Sombrilla", "parasol_lady"),
    _EmeraldRegularTrainer("Madeline", "Dama Sombrilla", "parasol_lady"),
    _EmeraldRegularTrainer("Madeline", "Dama Sombrilla", "parasol_lady"),
    _EmeraldRegularTrainer("Beverly", "Nadadora", "swimmer_female"),
    _EmeraldRegularTrainer("Imani", "Nadadora", "swimmer_female"),
    _EmeraldRegularTrainer("Kyla", "Nadadora", "swimmer_female"),
    _EmeraldRegularTrainer("Denise", "Nadadora", "swimmer_female"),
    _EmeraldRegularTrainer("Beth", "Nadadora", "swimmer_female"),
    _EmeraldRegularTrainer("Tara", "Nadadora", "swimmer_female"),
    _EmeraldRegularTrainer("Missy", "Nadadora", "swimmer_female"),
    _EmeraldRegularTrainer("Alice", "Nadadora", "swimmer_female"),
    _EmeraldRegularTrainer("Jenny", "Nadadora", "swimmer_female"),
    _EmeraldRegularTrainer("Grace", "Nadadora", "swimmer_female"),
    _EmeraldRegularTrainer("Tanya", "Nadadora", "swimmer_female"),
    _EmeraldRegularTrainer("Sharon", "Nadadora", "swimmer_female"),
    _EmeraldRegularTrainer("Nikki", "Nadadora", "swimmer_female"),
    _EmeraldRegularTrainer("Brenda", "Nadadora", "swimmer_female"),
    _EmeraldRegularTrainer("Katie", "Nadadora", "swimmer_female"),
    _EmeraldRegularTrainer("Susie", "Nadadora", "swimmer_female"),
    _EmeraldRegularTrainer("Kara", "Nadadora", "swimmer_female"),
    _EmeraldRegularTrainer("Dana", "Nadadora", "swimmer_female"),
    _EmeraldRegularTrainer("Sienna", "Nadadora", "swimmer_female"),
    _EmeraldRegularTrainer("Debra", "Nadadora", "swimmer_female"),
    _EmeraldRegularTrainer("Linda", "Nadadora", "swimmer_female"),
    _EmeraldRegularTrainer("Kaylee", "Nadadora", "swimmer_female"),
    _EmeraldRegularTrainer("Laurel", "Nadadora", "swimmer_female"),
    _EmeraldRegularTrainer("Carlee", "Nadadora", "swimmer_female"),
    _EmeraldRegularTrainer("Jenny", "Nadadora", "swimmer_female"),
    _EmeraldRegularTrainer("Jenny", "Nadadora", "swimmer_female"),
    _EmeraldRegularTrainer("Jenny", "Nadadora", "swimmer_female"),
    _EmeraldRegularTrainer("Jenny", "Nadadora", "swimmer_female"),
    _EmeraldRegularTrainer("Heidi", "Dominguera", "picnicker"),
    _EmeraldRegularTrainer("Becky", "Dominguera", "picnicker"),
    _EmeraldRegularTrainer("Carol", "Dominguera", "picnicker"),
    _EmeraldRegularTrainer("Nancy", "Dominguera", "picnicker"),
    _EmeraldRegularTrainer("Martha", "Dominguera", "picnicker"),
    _EmeraldRegularTrainer("Diana", "Dominguera", "picnicker"),
    _EmeraldRegularTrainer("Cedric", "Médium", "psychic_male"),
    _EmeraldRegularTrainer("Irene", "Dominguera", "picnicker"),
    _EmeraldRegularTrainer("Diana", "Dominguera", "picnicker"),
    _EmeraldRegularTrainer("Diana", "Dominguera", "picnicker"),
    _EmeraldRegularTrainer("Diana", "Dominguera", "picnicker"),
    _EmeraldRegularTrainer("Diana", "Dominguera", "picnicker"),
    _EmeraldRegularTrainer("Amy & Liv", "Gemelas", "twins"),
    _EmeraldRegularTrainer("Amy & Liv", "Gemelas", "twins"),
    _EmeraldRegularTrainer("Gina & Mia", "Gemelas", "twins"),
    _EmeraldRegularTrainer("Miu & Yuki", "Gemelas", "twins"),
    _EmeraldRegularTrainer("Amy & Liv", "Gemelas", "twins"),
    _EmeraldRegularTrainer("Gina & Mia", "Gemelas", "twins"),
    _EmeraldRegularTrainer("Amy & Liv", "Gemelas", "twins"),
    _EmeraldRegularTrainer("Amy & Liv", "Gemelas", "twins"),
    _EmeraldRegularTrainer("Amy & Liv", "Gemelas", "twins"),
    _EmeraldRegularTrainer("Huey", "Marinero", "sailor"),
    _EmeraldRegularTrainer("Edmond", "Marinero", "sailor"),
    _EmeraldRegularTrainer("Ernest", "Marinero", "sailor"),
    _EmeraldRegularTrainer("Dwayne", "Marinero", "sailor"),
    _EmeraldRegularTrainer("Phillip", "Marinero", "sailor"),
    _EmeraldRegularTrainer("Leonard", "Marinero", "sailor"),
    _EmeraldRegularTrainer("Duncan", "Marinero", "sailor"),
    _EmeraldRegularTrainer("Ernest", "Marinero", "sailor"),
    _EmeraldRegularTrainer("Ernest", "Marinero", "sailor"),
    _EmeraldRegularTrainer("Ernest", "Marinero", "sailor"),
    _EmeraldRegularTrainer("Ernest", "Marinero", "sailor"),
    _EmeraldRegularTrainer("Eli", "Montañero", "hiker"),
    _EmeraldRegularTrainer("Annika", "Pokéfan", "pokefan_female"),
    _EmeraldRegularTrainer("Jazmyn", "Entrenador Guay", "cooltrainer_female"),
    _EmeraldRegularTrainer("Jonas", "Niño Ninja", "ninja_boy"),
    _EmeraldRegularTrainer("Kayley", "Dama Sombrilla", "parasol_lady"),
    _EmeraldRegularTrainer("Auron", "Experto", "expert_male"),
    _EmeraldRegularTrainer("Kelvin", "Marinero", "sailor"),
    _EmeraldRegularTrainer("Marley", "Entrenador Guay", "cooltrainer_female"),
    _EmeraldRegularTrainer("Reyna", "Luchadora", "battle_girl"),
    _EmeraldRegularTrainer("Hudson", "Marinero", "sailor"),
    _EmeraldRegularTrainer("Conor", "Experto", "expert_male"),
    _EmeraldRegularTrainer("Edwin", "Coleccionista", "collector"),
    _EmeraldRegularTrainer("Hector", "Coleccionista", "collector"),
    _EmeraldRegularTrainer("Tabitha", "Comandante Magma", "magma_admin"),
    _EmeraldRegularTrainer("Edwin", "Coleccionista", "collector"),
    _EmeraldRegularTrainer("Edwin", "Coleccionista", "collector"),
    _EmeraldRegularTrainer("Edwin", "Coleccionista", "collector"),
    _EmeraldRegularTrainer("Edwin", "Coleccionista", "collector"),
    _EmeraldRegularTrainer("Wally", "Rival", "wally"),
    _EmeraldRegularTrainer("Brendan", "Rival", "brendan"),
    _EmeraldRegularTrainer("Brendan", "Rival", "brendan"),
    _EmeraldRegularTrainer("Brendan", "Rival", "brendan"),
    _EmeraldRegularTrainer("Brendan", "Rival", "brendan"),
    _EmeraldRegularTrainer("Brendan", "Rival", "brendan"),
    _EmeraldRegularTrainer("Brendan", "Rival", "brendan"),
    _EmeraldRegularTrainer("Brendan", "Rival", "brendan"),
    _EmeraldRegularTrainer("Brendan", "Rival", "brendan"),
    _EmeraldRegularTrainer("Brendan", "Rival", "brendan"),
    _EmeraldRegularTrainer("May", "Rival", "may"),
    _EmeraldRegularTrainer("May", "Rival", "may"),
    _EmeraldRegularTrainer("May", "Rival", "may"),
    _EmeraldRegularTrainer("May", "Rival", "may"),
    _EmeraldRegularTrainer("May", "Rival", "may"),
    _EmeraldRegularTrainer("May", "Rival", "may"),
    _EmeraldRegularTrainer("May", "Rival", "may"),
    _EmeraldRegularTrainer("May", "Rival", "may"),
    _EmeraldRegularTrainer("May", "Rival", "may"),
    _EmeraldRegularTrainer("Isaac", "Criador Pokémon", "pokemon_breeder_male"),
    _EmeraldRegularTrainer("Davis", "Cazabichos", "bug_catcher"),
    _EmeraldRegularTrainer("Mitchell", "Entrenador Guay", "cooltrainer_male"),
    _EmeraldRegularTrainer("Isaac", "Criador Pokémon", "pokemon_breeder_male"),
    _EmeraldRegularTrainer("Isaac", "Criador Pokémon", "pokemon_breeder_male"),
    _EmeraldRegularTrainer("Isaac", "Criador Pokémon", "pokemon_breeder_male"),
    _EmeraldRegularTrainer("Isaac", "Criador Pokémon", "pokemon_breeder_male"),
    _EmeraldRegularTrainer("Lydia", "Criador Pokémon", "pokemon_breeder_female"),
    _EmeraldRegularTrainer("Halle", "Entrenador Guay", "cooltrainer_female"),
    _EmeraldRegularTrainer("Garrison", "Ruinamaníaco", "ruin_maniac"),
    _EmeraldRegularTrainer("Lydia", "Criador Pokémon", "pokemon_breeder_female"),
    _EmeraldRegularTrainer("Lydia", "Criador Pokémon", "pokemon_breeder_female"),
    _EmeraldRegularTrainer("Lydia", "Criador Pokémon", "pokemon_breeder_female"),
    _EmeraldRegularTrainer("Lydia", "Criador Pokémon", "pokemon_breeder_female"),
    _EmeraldRegularTrainer("Jackson", "Pokémon Ranger", "pokemon_ranger_male"),
    _EmeraldRegularTrainer("Lorenzo", "Pokémon Ranger", "pokemon_ranger_male"),
    _EmeraldRegularTrainer("Sebastian", "Pokémon Ranger", "pokemon_ranger_male"),
    _EmeraldRegularTrainer("Jackson", "Pokémon Ranger", "pokemon_ranger_male"),
    _EmeraldRegularTrainer("Jackson", "Pokémon Ranger", "pokemon_ranger_male"),
    _EmeraldRegularTrainer("Jackson", "Pokémon Ranger", "pokemon_ranger_male"),
    _EmeraldRegularTrainer("Jackson", "Pokémon Ranger", "pokemon_ranger_male"),
    _EmeraldRegularTrainer("Catherine", "Pokémon Ranger", "pokemon_ranger_female"),
    _EmeraldRegularTrainer("Jenna", "Pokémon Ranger", "pokemon_ranger_female"),
    _EmeraldRegularTrainer("Sophia", "Pokémon Ranger", "pokemon_ranger_female"),
    _EmeraldRegularTrainer("Catherine", "Pokémon Ranger", "pokemon_ranger_female"),
    _EmeraldRegularTrainer("Catherine", "Pokémon Ranger", "pokemon_ranger_female"),
    _EmeraldRegularTrainer("Catherine", "Pokémon Ranger", "pokemon_ranger_female"),
    _EmeraldRegularTrainer("Catherine", "Pokémon Ranger", "pokemon_ranger_female"),
    _EmeraldRegularTrainer("Julio", "Triatleta", "triathlete_cycling_male"),
    _EmeraldRegularTrainer("Grunt", "Recluta Aqua", "aqua_grunt_m"),
    _EmeraldRegularTrainer("Grunt", "Recluta Magma", "aqua_grunt_f"),
    _EmeraldRegularTrainer("Grunt", "Recluta Aqua", "aqua_grunt_f"),
    _EmeraldRegularTrainer("Grunt", "Recluta Magma", "magma_grunt_m"),
    _EmeraldRegularTrainer("Marc", "Montañero", "hiker"),
    _EmeraldRegularTrainer("Brenden", "Marinero", "sailor"),
    _EmeraldRegularTrainer("Lilith", "Luchadora", "battle_girl"),
    _EmeraldRegularTrainer("Cristian", "Karateka", "black_belt"),
    _EmeraldRegularTrainer("Sylvia", "Bruja", "hex_maniac"),
    _EmeraldRegularTrainer("Leonardo", "Nadador", "swimmer_male"),
    _EmeraldRegularTrainer("Athena", "Entrenador Guay", "cooltrainer_female"),
    _EmeraldRegularTrainer("Harrison", "Nadador", "swimmer_male"),
    _EmeraldRegularTrainer("Grunt", "Recluta Magma", "magma_grunt_m"),
    _EmeraldRegularTrainer("Clarence", "Nadador", "swimmer_male"),
    _EmeraldRegularTrainer("Terry", "Médium", "psychic_female"),
    _EmeraldRegularTrainer("Nate", "Caballero", "gentleman"),
    _EmeraldRegularTrainer("Kathleen", "Bruja", "hex_maniac"),
    _EmeraldRegularTrainer("Clifford", "Caballero", "gentleman"),
    _EmeraldRegularTrainer("Nicholas", "Médium", "psychic_male"),
    _EmeraldRegularTrainer("Grunt", "Recluta Magma", "magma_grunt_f"),
    _EmeraldRegularTrainer("Grunt", "Recluta Magma", "magma_grunt_m"),
    _EmeraldRegularTrainer("Grunt", "Recluta Magma", "magma_grunt_m"),
    _EmeraldRegularTrainer("Grunt", "Recluta Magma", "magma_grunt_m"),
    _EmeraldRegularTrainer("Grunt", "Recluta Magma", "magma_grunt_m"),
    _EmeraldRegularTrainer("Macey", "Médium", "psychic_female"),
    _EmeraldRegularTrainer("Brendan", "Rival", "brendan"),
    _EmeraldRegularTrainer("Brendan", "Rival", "brendan"),
    _EmeraldRegularTrainer("Paxton", "Experto", "expert_male"),
    _EmeraldRegularTrainer("Isabella", "Triatleta", "triathlete_swimming_female"),
    _EmeraldRegularTrainer("Grunt", "Recluta Aqua", "aqua_grunt_f"),
    _EmeraldRegularTrainer("Tabitha", "Comandante Magma", "magma_admin"),
    _EmeraldRegularTrainer("Jonathan", "Entrenador Guay", "cooltrainer_male"),
    _EmeraldRegularTrainer("Brendan", "Rival", "brendan"),
    _EmeraldRegularTrainer("May", "Rival", "may"),
    _EmeraldRegularTrainer("Maxie", "Líder Magma", "magma_leader_maxie"),
    _EmeraldRegularTrainer("Maxie", "Líder Magma", "magma_leader_maxie"),
    _EmeraldRegularTrainer("Tiana", "Chica", "lass"),
    _EmeraldRegularTrainer("Haley", "Chica", "lass"),
    _EmeraldRegularTrainer("Janice", "Chica", "lass"),
    _EmeraldRegularTrainer("Vivi", "Familia Estratega", "lass"),
    _EmeraldRegularTrainer("Haley", "Chica", "lass"),
    _EmeraldRegularTrainer("Haley", "Chica", "lass"),
    _EmeraldRegularTrainer("Haley", "Chica", "lass"),
    _EmeraldRegularTrainer("Haley", "Chica", "lass"),
    _EmeraldRegularTrainer("Sally", "Chica", "lass"),
    _EmeraldRegularTrainer("Robin", "Chica", "lass"),
    _EmeraldRegularTrainer("Andrea", "Chica", "lass"),
    _EmeraldRegularTrainer("Crissy", "Chica", "lass"),
    _EmeraldRegularTrainer("Rick", "Cazabichos", "bug_catcher"),
    _EmeraldRegularTrainer("Lyle", "Cazabichos", "bug_catcher"),
    _EmeraldRegularTrainer("Jose", "Cazabichos", "bug_catcher"),
    _EmeraldRegularTrainer("Doug", "Cazabichos", "bug_catcher"),
    _EmeraldRegularTrainer("Greg", "Cazabichos", "bug_catcher"),
    _EmeraldRegularTrainer("Kent", "Cazabichos", "bug_catcher"),
    _EmeraldRegularTrainer("James", "Cazabichos", "bug_catcher"),
    _EmeraldRegularTrainer("James", "Cazabichos", "bug_catcher"),
    _EmeraldRegularTrainer("James", "Cazabichos", "bug_catcher"),
    _EmeraldRegularTrainer("James", "Cazabichos", "bug_catcher"),
    _EmeraldRegularTrainer("James", "Cazabichos", "bug_catcher"),
    _EmeraldRegularTrainer("Brice", "Montañero", "hiker"),
    _EmeraldRegularTrainer("Trent", "Montañero", "hiker"),
    _EmeraldRegularTrainer("Lenny", "Montañero", "hiker"),
    _EmeraldRegularTrainer("Lucas", "Montañero", "hiker"),
    _EmeraldRegularTrainer("Alan", "Montañero", "hiker"),
    _EmeraldRegularTrainer("Clark", "Montañero", "hiker"),
    _EmeraldRegularTrainer("Eric", "Montañero", "hiker"),
    _EmeraldRegularTrainer("Lucas", "Montañero", "hiker"),
    _EmeraldRegularTrainer("Mike", "Montañero", "hiker"),
    _EmeraldRegularTrainer("Mike", "Montañero", "hiker"),
    _EmeraldRegularTrainer("Trent", "Montañero", "hiker"),
    _EmeraldRegularTrainer("Trent", "Montañero", "hiker"),
    _EmeraldRegularTrainer("Trent", "Montañero", "hiker"),
    _EmeraldRegularTrainer("Trent", "Montañero", "hiker"),
    _EmeraldRegularTrainer("Dez & Luke", "Pareja Joven", "young_couple"),
    _EmeraldRegularTrainer("Lea & Jed", "Pareja Joven", "young_couple"),
    _EmeraldRegularTrainer("Kira & Dan", "Pareja Joven", "young_couple"),
    _EmeraldRegularTrainer("Kira & Dan", "Pareja Joven", "young_couple"),
    _EmeraldRegularTrainer("Kira & Dan", "Pareja Joven", "young_couple"),
    _EmeraldRegularTrainer("Kira & Dan", "Pareja Joven", "young_couple"),
    _EmeraldRegularTrainer("Kira & Dan", "Pareja Joven", "young_couple"),
    _EmeraldRegularTrainer("Johanna", "Bella", "beauty"),
    _EmeraldRegularTrainer("Gerald", "Entrenador Guay", "cooltrainer_male"),
    _EmeraldRegularTrainer("Vivian", "Luchadora", "battle_girl"),
    _EmeraldRegularTrainer("Danielle", "Luchadora", "battle_girl"),
    _EmeraldRegularTrainer("Hideo", "Niño Ninja", "ninja_boy"),
    _EmeraldRegularTrainer("Keigo", "Niño Ninja", "ninja_boy"),
    _EmeraldRegularTrainer("Riley", "Niño Ninja", "ninja_boy"),
    _EmeraldRegularTrainer("Flint", "Campista", "camper"),
    _EmeraldRegularTrainer("Ashley", "Dominguera", "picnicker"),
    _EmeraldRegularTrainer("Wally", "Rival", "wally"),
    _EmeraldRegularTrainer("Wally", "Rival", "wally"),
    _EmeraldRegularTrainer("Wally", "Rival", "wally"),
    _EmeraldRegularTrainer("Wally", "Rival", "wally"),
    _EmeraldRegularTrainer("Wally", "Rival", "wally"),
    _EmeraldRegularTrainer("Brendan", "Rival", "brendan"),
    _EmeraldRegularTrainer("Brendan", "Rival", "brendan"),
    _EmeraldRegularTrainer("Brendan", "Rival", "brendan"),
    _EmeraldRegularTrainer("May", "Rival", "may"),
    _EmeraldRegularTrainer("May", "Rival", "may"),
    _EmeraldRegularTrainer("May", "Rival", "may"),
    _EmeraldRegularTrainer("Jonah", "Pescador", "fisherman"),
    _EmeraldRegularTrainer("Henry", "Pescador", "fisherman"),
    _EmeraldRegularTrainer("Roger", "Pescador", "fisherman"),
    _EmeraldRegularTrainer("Alexa", "Entrenador Guay", "cooltrainer_female"),
    _EmeraldRegularTrainer("Ruben", "Entrenador Guay", "cooltrainer_male"),
    _EmeraldRegularTrainer("Koji", "Karateka", "black_belt"),
    _EmeraldRegularTrainer("Wayne", "Pescador", "fisherman"),
    _EmeraldRegularTrainer("Aidan", "Ornitólogo", "bird_keeper"),
    _EmeraldRegularTrainer("Reed", "Nadador", "swimmer_male"),
    _EmeraldRegularTrainer("Tisha", "Nadadora", "swimmer_female"),
    _EmeraldRegularTrainer("Tori & Tia", "Gemelas", "twins"),
    _EmeraldRegularTrainer("Kim & Iris", "Senior y Junior", "students"),
    _EmeraldRegularTrainer("Tyra & Ivy", "Senior y Junior", "students"),
    _EmeraldRegularTrainer("Mel & Paul", "Pareja Joven", "young_couple"),
    _EmeraldRegularTrainer("John & Jay", "Pareja Mayor", "old_couple"),
    _EmeraldRegularTrainer("John & Jay", "Pareja Mayor", "old_couple"),
    _EmeraldRegularTrainer("John & Jay", "Pareja Mayor", "old_couple"),
    _EmeraldRegularTrainer("John & Jay", "Pareja Mayor", "old_couple"),
    _EmeraldRegularTrainer("John & Jay", "Pareja Mayor", "old_couple"),
    _EmeraldRegularTrainer("Reli & Ian", "Hermanos", "sis_and_bro"),
    _EmeraldRegularTrainer("Lila & Roy", "Hermanos", "sis_and_bro"),
    _EmeraldRegularTrainer("Lila & Roy", "Hermanos", "sis_and_bro"),
    _EmeraldRegularTrainer("Lila & Roy", "Hermanos", "sis_and_bro"),
    _EmeraldRegularTrainer("Lila & Roy", "Hermanos", "sis_and_bro"),
    _EmeraldRegularTrainer("Lila & Roy", "Hermanos", "sis_and_bro"),
    _EmeraldRegularTrainer("Lisa & Ray", "Hermanos", "sis_and_bro"),
    _EmeraldRegularTrainer("Chris", "Pescador", "fisherman"),
    _EmeraldRegularTrainer("Dawson", "Niño Rico", "rich_boy"),
    _EmeraldRegularTrainer("Sarah", "Dama", "lady"),
    _EmeraldRegularTrainer("Darian", "Pescador", "fisherman"),
    _EmeraldRegularTrainer("Hailey", "Niña Bien", "tuber_female"),
    _EmeraldRegularTrainer("Chandler", "Niño Bien", "tuber_male"),
    _EmeraldRegularTrainer("Kaleb", "Pokéfan", "pokefan_male"),
    _EmeraldRegularTrainer("Joseph", "Guitarrista", "guitarist"),
    _EmeraldRegularTrainer("Alyssa", "Triatleta", "triathlete_cycling_female"),
    _EmeraldRegularTrainer("Marcos", "Guitarrista", "guitarist"),
    _EmeraldRegularTrainer("Rhett", "Karateka", "black_belt"),
    _EmeraldRegularTrainer("Tyron", "Campista", "camper"),
    _EmeraldRegularTrainer("Celina", "Dama Aroma", "aroma_lady"),
    _EmeraldRegularTrainer("Bianca", "Dominguera", "picnicker"),
    _EmeraldRegularTrainer("Hayden", "Prendefuegos", "kindler"),
    _EmeraldRegularTrainer("Sophie", "Dominguera", "picnicker"),
    _EmeraldRegularTrainer("Coby", "Ornitólogo", "bird_keeper"),
    _EmeraldRegularTrainer("Lawrence", "Campista", "camper"),
    _EmeraldRegularTrainer("Wyatt", "Pokémaníaco", "pokemaniac"),
    _EmeraldRegularTrainer("Angelina", "Dominguera", "picnicker"),
    _EmeraldRegularTrainer("Kai", "Pescador", "fisherman"),
    _EmeraldRegularTrainer("Charlotte", "Dominguera", "picnicker"),
    _EmeraldRegularTrainer("Deandre", "Joven", "youngster"),
    _EmeraldRegularTrainer("Grunt", "Recluta Magma", "magma_grunt_m"),
    _EmeraldRegularTrainer("Grunt", "Recluta Magma", "magma_grunt_m"),
    _EmeraldRegularTrainer("Grunt", "Recluta Magma", "magma_grunt_m"),
    _EmeraldRegularTrainer("Grunt", "Recluta Magma", "magma_grunt_m"),
    _EmeraldRegularTrainer("Grunt", "Recluta Magma", "magma_grunt_m"),
    _EmeraldRegularTrainer("Grunt", "Recluta Magma", "magma_grunt_m"),
    _EmeraldRegularTrainer("Grunt", "Recluta Magma", "magma_grunt_m"),
    _EmeraldRegularTrainer("Grunt", "Recluta Magma", "magma_grunt_m"),
    _EmeraldRegularTrainer("Grunt", "Recluta Magma", "magma_grunt_m"),
    _EmeraldRegularTrainer("Grunt", "Recluta Magma", "magma_grunt_m"),
    _EmeraldRegularTrainer("Grunt", "Recluta Magma", "magma_grunt_m"),
    _EmeraldRegularTrainer("Grunt", "Recluta Magma", "magma_grunt_m"),
    _EmeraldRegularTrainer("Grunt", "Recluta Magma", "magma_grunt_m"),
    _EmeraldRegularTrainer("Grunt", "Recluta Magma", "magma_grunt_f"),
    _EmeraldRegularTrainer("Grunt", "Recluta Magma", "magma_grunt_f"),
    _EmeraldRegularTrainer("Grunt", "Recluta Magma", "magma_grunt_f"),
    _EmeraldRegularTrainer("Tabitha", "Comandante Magma", "magma_admin"),
    _EmeraldRegularTrainer("Darcy", "Entrenador Guay", "cooltrainer_female"),
    _EmeraldRegularTrainer("Maxie", "Líder Magma", "magma_leader_maxie"),
    _EmeraldRegularTrainer("Pete", "Nadador", "swimmer_male"),
    _EmeraldRegularTrainer("Isabelle", "Nadadora", "swimmer_female"),
    _EmeraldRegularTrainer("Andres", "Ruinamaníaco", "ruin_maniac"),
    _EmeraldRegularTrainer("Josue", "Ornitólogo", "bird_keeper"),
    _EmeraldRegularTrainer("Camron", "Triatleta", "triathlete_swimming_male"),
    _EmeraldRegularTrainer("Cory", "Marinero", "sailor"),
    _EmeraldRegularTrainer("Carolina", "Entrenador Guay", "cooltrainer_female"),
    _EmeraldRegularTrainer("Elijah", "Ornitólogo", "bird_keeper"),
    _EmeraldRegularTrainer("Celia", "Dominguera", "picnicker"),
    _EmeraldRegularTrainer("Bryan", "Ruinamaníaco", "ruin_maniac"),
    _EmeraldRegularTrainer("Branden", "Campista", "camper"),
    _EmeraldRegularTrainer("Bryant", "Prendefuegos", "kindler"),
    _EmeraldRegularTrainer("Shayla", "Dama Aroma", "aroma_lady"),
    _EmeraldRegularTrainer("Kyra", "Triatleta", "triathlete_running_female"),
    _EmeraldRegularTrainer("Jaiden", "Niño Ninja", "ninja_boy"),
    _EmeraldRegularTrainer("Alix", "Médium", "psychic_female"),
    _EmeraldRegularTrainer("Helene", "Luchadora", "battle_girl"),
    _EmeraldRegularTrainer("Marlene", "Médium", "psychic_female"),
    _EmeraldRegularTrainer("Devan", "Montañero", "hiker"),
    _EmeraldRegularTrainer("Johnson", "Joven", "youngster"),
    _EmeraldRegularTrainer("Melina", "Triatleta", "triathlete_running_female"),
    _EmeraldRegularTrainer("Brandi", "Médium", "psychic_female"),
    _EmeraldRegularTrainer("Aisha", "Luchadora", "battle_girl"),
    _EmeraldRegularTrainer("Makayla", "Experto", "expert_female"),
    _EmeraldRegularTrainer("Fabian", "Guitarrista", "guitarist"),
    _EmeraldRegularTrainer("Dayton", "Prendefuegos", "kindler"),
    _EmeraldRegularTrainer("Rachel", "Dama Sombrilla", "parasol_lady"),
    _EmeraldRegularTrainer("Leonel", "Entrenador Guay", "cooltrainer_male"),
    _EmeraldRegularTrainer("Callie", "Luchadora", "battle_girl"),
    _EmeraldRegularTrainer("Cale", "Bichomaníaco", "bug_maniac"),
    _EmeraldRegularTrainer("Myles", "Criador Pokémon", "pokemon_breeder_male"),
    _EmeraldRegularTrainer("Pat", "Criador Pokémon", "pokemon_breeder_female"),
    _EmeraldRegularTrainer("Cristin", "Entrenador Guay", "cooltrainer_female"),
    _EmeraldRegularTrainer("May", "Rival", "may"),
    _EmeraldRegularTrainer("May", "Rival", "may"),
    _EmeraldRegularTrainer("Roxanne", "Líder", "leader_roxanne"),
    _EmeraldRegularTrainer("Roxanne", "Líder", "leader_roxanne"),
    _EmeraldRegularTrainer("Roxanne", "Líder", "leader_roxanne"),
    _EmeraldRegularTrainer("Roxanne", "Líder", "leader_roxanne"),
    _EmeraldRegularTrainer("Brawly", "Líder", "leader_brawly"),
    _EmeraldRegularTrainer("Brawly", "Líder", "leader_brawly"),
    _EmeraldRegularTrainer("Brawly", "Líder", "leader_brawly"),
    _EmeraldRegularTrainer("Brawly", "Líder", "leader_brawly"),
    _EmeraldRegularTrainer("Wattson", "Líder", "leader_wattson"),
    _EmeraldRegularTrainer("Wattson", "Líder", "leader_wattson"),
    _EmeraldRegularTrainer("Wattson", "Líder", "leader_wattson"),
    _EmeraldRegularTrainer("Wattson", "Líder", "leader_wattson"),
    _EmeraldRegularTrainer("Flannery", "Líder", "leader_flannery"),
    _EmeraldRegularTrainer("Flannery", "Líder", "leader_flannery"),
    _EmeraldRegularTrainer("Flannery", "Líder", "leader_flannery"),
    _EmeraldRegularTrainer("Flannery", "Líder", "leader_flannery"),
    _EmeraldRegularTrainer("Norman", "Líder", "leader_norman"),
    _EmeraldRegularTrainer("Norman", "Líder", "leader_norman"),
    _EmeraldRegularTrainer("Norman", "Líder", "leader_norman"),
    _EmeraldRegularTrainer("Norman", "Líder", "leader_norman"),
    _EmeraldRegularTrainer("Winona", "Líder", "leader_winona"),
    _EmeraldRegularTrainer("Winona", "Líder", "leader_winona"),
    _EmeraldRegularTrainer("Winona", "Líder", "leader_winona"),
    _EmeraldRegularTrainer("Winona", "Líder", "leader_winona"),
    _EmeraldRegularTrainer("Tate&liza", "Líder", "leader_tate_and_liza"),
    _EmeraldRegularTrainer("Tate&liza", "Líder", "leader_tate_and_liza"),
    _EmeraldRegularTrainer("Tate&liza", "Líder", "leader_tate_and_liza"),
    _EmeraldRegularTrainer("Tate&liza", "Líder", "leader_tate_and_liza"),
    _EmeraldRegularTrainer("Juan", "Líder", "leader_juan"),
    _EmeraldRegularTrainer("Juan", "Líder", "leader_juan"),
    _EmeraldRegularTrainer("Juan", "Líder", "leader_juan"),
    _EmeraldRegularTrainer("Juan", "Líder", "leader_juan"),
    _EmeraldRegularTrainer("Angelo", "Bichomaníaco", "bug_maniac"),
    _EmeraldRegularTrainer("Darius", "Ornitólogo", "bird_keeper"),
    _EmeraldRegularTrainer("Steven", "Rival", "steven"),
    _EmeraldRegularTrainer("Anabel", "Dama Torre", "salon_maiden_anabel"),
    _EmeraldRegularTrainer("Tucker", "As Cúpula", "dome_ace_tucker"),
    _EmeraldRegularTrainer("Spenser", "Maestro Palacio", "palace_maven_spenser"),
    _EmeraldRegularTrainer("Greta", "Magnate Arena", "arena_tycoon_greta"),
    _EmeraldRegularTrainer("Noland", "Jefe Fábrica", "factory_head_noland"),
    _EmeraldRegularTrainer("Lucy", "Reina Sierpe", "pike_queen_lucy"),
    _EmeraldRegularTrainer("Brandon", "Rey Pirámide", "pyramid_king_brandon"),
    _EmeraldRegularTrainer("Andres", "Ruinamaníaco", "ruin_maniac"),
    _EmeraldRegularTrainer("Andres", "Ruinamaníaco", "ruin_maniac"),
    _EmeraldRegularTrainer("Andres", "Ruinamaníaco", "ruin_maniac"),
    _EmeraldRegularTrainer("Andres", "Ruinamaníaco", "ruin_maniac"),
    _EmeraldRegularTrainer("Cory", "Marinero", "sailor"),
    _EmeraldRegularTrainer("Cory", "Marinero", "sailor"),
    _EmeraldRegularTrainer("Cory", "Marinero", "sailor"),
    _EmeraldRegularTrainer("Cory", "Marinero", "sailor"),
    _EmeraldRegularTrainer("Pablo", "Triatleta", "triathlete_swimming_male"),
    _EmeraldRegularTrainer("Pablo", "Triatleta", "triathlete_swimming_male"),
    _EmeraldRegularTrainer("Pablo", "Triatleta", "triathlete_swimming_male"),
    _EmeraldRegularTrainer("Pablo", "Triatleta", "triathlete_swimming_male"),
    _EmeraldRegularTrainer("Koji", "Karateka", "black_belt"),
    _EmeraldRegularTrainer("Koji", "Karateka", "black_belt"),
    _EmeraldRegularTrainer("Koji", "Karateka", "black_belt"),
    _EmeraldRegularTrainer("Koji", "Karateka", "black_belt"),
    _EmeraldRegularTrainer("Cristin", "Entrenador Guay", "cooltrainer_female"),
    _EmeraldRegularTrainer("Cristin", "Entrenador Guay", "cooltrainer_female"),
    _EmeraldRegularTrainer("Cristin", "Entrenador Guay", "cooltrainer_female"),
    _EmeraldRegularTrainer("Cristin", "Entrenador Guay", "cooltrainer_female"),
    _EmeraldRegularTrainer("Fernando", "Guitarrista", "guitarist"),
    _EmeraldRegularTrainer("Fernando", "Guitarrista", "guitarist"),
    _EmeraldRegularTrainer("Fernando", "Guitarrista", "guitarist"),
    _EmeraldRegularTrainer("Fernando", "Guitarrista", "guitarist"),
    _EmeraldRegularTrainer("Sawyer", "Montañero", "hiker"),
    _EmeraldRegularTrainer("Sawyer", "Montañero", "hiker"),
    _EmeraldRegularTrainer("Sawyer", "Montañero", "hiker"),
    _EmeraldRegularTrainer("Sawyer", "Montañero", "hiker"),
    _EmeraldRegularTrainer("Gabrielle", "Criador Pokémon", "pokemon_breeder_female"),
    _EmeraldRegularTrainer("Gabrielle", "Criador Pokémon", "pokemon_breeder_female"),
    _EmeraldRegularTrainer("Gabrielle", "Criador Pokémon", "pokemon_breeder_female"),
    _EmeraldRegularTrainer("Gabrielle", "Criador Pokémon", "pokemon_breeder_female"),
    _EmeraldRegularTrainer("Thalia", "Bella", "beauty"),
    _EmeraldRegularTrainer("Thalia", "Bella", "beauty"),
    _EmeraldRegularTrainer("Thalia", "Bella", "beauty"),
    _EmeraldRegularTrainer("Thalia", "Bella", "beauty"),
    _EmeraldRegularTrainer("Mariela", "Médium", "psychic_female"),
    _EmeraldRegularTrainer("Alvaro", "Médium", "psychic_male"),
    _EmeraldRegularTrainer("Everett", "Caballero", "gentleman"),
    _EmeraldRegularTrainer("Red", "Rival", "red"),
    _EmeraldRegularTrainer("Leaf", "Rival", "leaf"),
    _EmeraldRegularTrainer("Brendan", "Entrenador Pokémon", "rs_brendan"),
    _EmeraldRegularTrainer("May", "Entrenador Pokémon", "rs_may"),
  ];

  static const Set<int> _brendanIds = <int>{
    520, 521, 522, 523, 524, 525, 526, 527, 528,
    592, 593, 599, 661, 662, 663, 853,
  };
  static const Set<int> _mayIds = <int>{
    529, 530, 531, 532, 533, 534, 535, 536, 537,
    600, 664, 665, 666, 768, 769, 854,
  };
  static const Set<int> _wallyIds = <int>{519, 656, 657, 658, 659, 660};

  static const Map<int, EmeraldTrainerInfo> _special =
      <int, EmeraldTrainerInfo>{
    261: EmeraldTrainerInfo(
      'Sidney',
      EmeraldTrainerKind.eliteFour,
      'assets/sprites/characters/elite_four/gba/Hoenn/sidney_hoenn.png',
    ),
    262: EmeraldTrainerInfo(
      'Phoebe',
      EmeraldTrainerKind.eliteFour,
      'assets/sprites/characters/elite_four/gba/Hoenn/phoebe_hoenn.png',
    ),
    263: EmeraldTrainerInfo(
      'Glacia',
      EmeraldTrainerKind.eliteFour,
      'assets/sprites/characters/elite_four/gba/Hoenn/glacia_hoenn.png',
    ),
    264: EmeraldTrainerInfo(
      'Drake',
      EmeraldTrainerKind.eliteFour,
      'assets/sprites/characters/elite_four/gba/Hoenn/drake_hoenn.png',
    ),
    265: EmeraldTrainerInfo(
      'Roxanne',
      EmeraldTrainerKind.gymLeader,
      'assets/sprites/characters/gym_leaders/gba/Hoenn/roxanne_hoenn.png',
    ),
    266: EmeraldTrainerInfo(
      'Brawly',
      EmeraldTrainerKind.gymLeader,
      'assets/sprites/characters/gym_leaders/gba/Hoenn/brawly_hoenn.png',
    ),
    267: EmeraldTrainerInfo(
      'Wattson',
      EmeraldTrainerKind.gymLeader,
      'assets/sprites/characters/gym_leaders/gba/Hoenn/wattson_hoenn.png',
    ),
    268: EmeraldTrainerInfo(
      'Flannery',
      EmeraldTrainerKind.gymLeader,
      'assets/sprites/characters/gym_leaders/gba/Hoenn/flannery_hoenn.png',
    ),
    269: EmeraldTrainerInfo(
      'Norman',
      EmeraldTrainerKind.gymLeader,
      'assets/sprites/characters/gym_leaders/gba/Hoenn/norman_hoenn.png',
    ),
    270: EmeraldTrainerInfo(
      'Winona',
      EmeraldTrainerKind.gymLeader,
      'assets/sprites/characters/gym_leaders/gba/Hoenn/winona_hoenn.png',
    ),
    271: EmeraldTrainerInfo(
      'Tate y Liza',
      EmeraldTrainerKind.gymLeader,
      'assets/sprites/characters/gym_leaders/gba/Hoenn/tate_liza_hoenn.png',
    ),
    272: EmeraldTrainerInfo(
      'Juan',
      EmeraldTrainerKind.gymLeader,
      'assets/sprites/characters/gym_leaders/gba/Hoenn/juan_hoenn.png',
    ),
    335: EmeraldTrainerInfo(
      'Wallace',
      EmeraldTrainerKind.champion,
      'assets/sprites/characters/champions/wallace_hoenn.png',
    ),
    804: EmeraldTrainerInfo(
      'Steven',
      EmeraldTrainerKind.specialTrainer,
      'assets/sprites/characters/champions/steven_hoenn.png',
    ),
    805: EmeraldTrainerInfo(
      'Anabel',
      EmeraldTrainerKind.frontierBrain,
      'assets/sprites/characters/special_trainers/battle_frontier/emerald/salon_maiden_anabel.png',
    ),
    806: EmeraldTrainerInfo(
      'Tucker',
      EmeraldTrainerKind.frontierBrain,
      'assets/sprites/characters/special_trainers/battle_frontier/emerald/dome_ace_tucker.png',
    ),
    807: EmeraldTrainerInfo(
      'Spenser',
      EmeraldTrainerKind.frontierBrain,
      'assets/sprites/characters/special_trainers/battle_frontier/emerald/palace_maven_spenser.png',
    ),
    808: EmeraldTrainerInfo(
      'Greta',
      EmeraldTrainerKind.frontierBrain,
      'assets/sprites/characters/special_trainers/battle_frontier/emerald/arena_tycoon_greta.png',
    ),
    809: EmeraldTrainerInfo(
      'Noland',
      EmeraldTrainerKind.frontierBrain,
      'assets/sprites/characters/special_trainers/battle_frontier/emerald/factory_head_noland.png',
    ),
    810: EmeraldTrainerInfo(
      'Lucy',
      EmeraldTrainerKind.frontierBrain,
      'assets/sprites/characters/special_trainers/battle_frontier/emerald/pike_queen_lucy.png',
    ),
    811: EmeraldTrainerInfo(
      'Brandon',
      EmeraldTrainerKind.frontierBrain,
      'assets/sprites/characters/special_trainers/battle_frontier/emerald/pyramid_king_brandon.png',
    ),
  };
}

final class _EmeraldRegularTrainer {
  final String name;
  final String className;
  final String spriteName;

  const _EmeraldRegularTrainer(this.name, this.className, this.spriteName);
}
