// GENERADO AUTOMÁTICAMENTE por tools/pokemon_locations/generate_locations.py
// No editar a mano: los cambios se pierden al regenerar.
// Fuente de nombres: sources/pokecrystal_map_names.txt (catálogo pret)
// Fuente de IDs:     sources/map_constants.txt (solo IDs confirmados)

import '../../../models/pokemon_location.dart';

const Map<int, PokemonLocation> generatedCrystalLocations = <int, PokemonLocation>{
  0x0101: PokemonLocation('Olivine Pokecenter 1F (sin traducir)', PokemonLocationKind.other),
  0x0102: PokemonLocation('Olivine Gym (sin traducir)', PokemonLocationKind.gym),
  0x0103: PokemonLocation('Olivine Tims House (sin traducir)', PokemonLocationKind.other),
  0x0104: PokemonLocation('Olivine House Beta (sin traducir)', PokemonLocationKind.other),
  0x0105: PokemonLocation('Olivine Punishment Speech House (sin traducir)', PokemonLocationKind.other),
  0x0106: PokemonLocation('Olivine Good Rod House (sin traducir)', PokemonLocationKind.other),
  0x0107: PokemonLocation('Olivine Cafe (sin traducir)', PokemonLocationKind.other),
  0x0108: PokemonLocation('Olivine Mart (sin traducir)', PokemonLocationKind.other),
  0x0109: PokemonLocation('Route 38 Ecruteak Gate (sin traducir)', PokemonLocationKind.route),
  0x010A: PokemonLocation('Route 39 Barn (sin traducir)', PokemonLocationKind.route),
  0x010B: PokemonLocation('Route 39 Farmhouse (sin traducir)', PokemonLocationKind.route),
  0x010C: PokemonLocation('Route 38 (sin traducir)', PokemonLocationKind.route),
  0x010D: PokemonLocation('Route 39 (sin traducir)', PokemonLocationKind.route),
  0x010E: PokemonLocation('Ciudad Olivo', PokemonLocationKind.city),
  0x0201: PokemonLocation('Mahogany Red Gyarados Speech House (sin traducir)', PokemonLocationKind.other),
  0x0202: PokemonLocation('Mahogany Gym (sin traducir)', PokemonLocationKind.gym),
  0x0203: PokemonLocation('Mahogany Pokecenter 1F (sin traducir)', PokemonLocationKind.other),
  0x0204: PokemonLocation('Route 42 Ecruteak Gate (sin traducir)', PokemonLocationKind.route),
  0x0205: PokemonLocation('Route 42 (sin traducir)', PokemonLocationKind.route),
  0x0206: PokemonLocation('Route 44 (sin traducir)', PokemonLocationKind.route),
  0x0207: PokemonLocation('Pueblo Caoba', PokemonLocationKind.city),
  0x0301: PokemonLocation('Torre Bellsprout (1F)', PokemonLocationKind.other),
  0x0302: PokemonLocation('Torre Bellsprout (2F)', PokemonLocationKind.other),
  0x0303: PokemonLocation('Torre Bellsprout (3F)', PokemonLocationKind.other),
  0x0304: PokemonLocation('Torre Hojalata', PokemonLocationKind.other),
  0x0305: PokemonLocation('Tin Tower 2F (sin traducir)', PokemonLocationKind.other),
  0x0306: PokemonLocation('Tin Tower 3F (sin traducir)', PokemonLocationKind.other),
  0x0307: PokemonLocation('Tin Tower 4F (sin traducir)', PokemonLocationKind.other),
  0x0308: PokemonLocation('Tin Tower 5F (sin traducir)', PokemonLocationKind.other),
  0x0309: PokemonLocation('Tin Tower 6F (sin traducir)', PokemonLocationKind.other),
  0x030A: PokemonLocation('Tin Tower 7F (sin traducir)', PokemonLocationKind.other),
  0x030B: PokemonLocation('Tin Tower 8F (sin traducir)', PokemonLocationKind.other),
  0x030C: PokemonLocation('Tin Tower 9F (sin traducir)', PokemonLocationKind.other),
  0x030D: PokemonLocation('Torre Quemada', PokemonLocationKind.other),
  0x030E: PokemonLocation('Burned Tower B1F (sin traducir)', PokemonLocationKind.other),
  0x030F: PokemonLocation('Parque Nacional', PokemonLocationKind.other),
  0x0310: PokemonLocation('National Park Bug Contest (sin traducir)', PokemonLocationKind.other),
  0x0311: PokemonLocation('Torre Radio', PokemonLocationKind.other),
  0x0312: PokemonLocation('Radio Tower 2F (sin traducir)', PokemonLocationKind.other),
  0x0313: PokemonLocation('Radio Tower 3F (sin traducir)', PokemonLocationKind.other),
  0x0314: PokemonLocation('Radio Tower 4F (sin traducir)', PokemonLocationKind.other),
  0x0315: PokemonLocation('Radio Tower 5F (sin traducir)', PokemonLocationKind.other),
  0x0316: PokemonLocation('Ruinas de Alph', PokemonLocationKind.other),
  0x0317: PokemonLocation('Ruins Of Alph Ho Oh Chamber (sin traducir)', PokemonLocationKind.other),
  0x0318: PokemonLocation('Ruins Of Alph Kabuto Chamber (sin traducir)', PokemonLocationKind.other),
  0x0319: PokemonLocation('Ruins Of Alph Omanyte Chamber (sin traducir)', PokemonLocationKind.other),
  0x031A: PokemonLocation('Ruins Of Alph Aerodactyl Chamber (sin traducir)', PokemonLocationKind.other),
  0x031B: PokemonLocation('Ruins Of Alph Inner Chamber (sin traducir)', PokemonLocationKind.other),
  0x031C: PokemonLocation('Ruins Of Alph Research Center (sin traducir)', PokemonLocationKind.other),
  0x031D: PokemonLocation('Ruins Of Alph Ho Oh Item Room (sin traducir)', PokemonLocationKind.other),
  0x031E: PokemonLocation('Ruins Of Alph Kabuto Item Room (sin traducir)', PokemonLocationKind.other),
  0x031F: PokemonLocation('Ruins Of Alph Omanyte Item Room (sin traducir)', PokemonLocationKind.other),
  0x0320: PokemonLocation('Ruins Of Alph Aerodactyl Item Room (sin traducir)', PokemonLocationKind.other),
  0x0321: PokemonLocation('Ruins Of Alph Ho Oh Word Room (sin traducir)', PokemonLocationKind.other),
  0x0322: PokemonLocation('Ruins Of Alph Kabuto Word Room (sin traducir)', PokemonLocationKind.other),
  0x0323: PokemonLocation('Ruins Of Alph Omanyte Word Room (sin traducir)', PokemonLocationKind.other),
  0x0324: PokemonLocation('Ruins Of Alph Aerodactyl Word Room (sin traducir)', PokemonLocationKind.other),
  0x0325: PokemonLocation('Cueva Unión (1F)', PokemonLocationKind.other),
  0x0326: PokemonLocation('Union Cave B1F (sin traducir)', PokemonLocationKind.other),
  0x0327: PokemonLocation('Union Cave B2F (sin traducir)', PokemonLocationKind.other),
  0x0328: PokemonLocation('Slowpoke Well B1F (sin traducir)', PokemonLocationKind.other),
  0x0329: PokemonLocation('Slowpoke Well B2F (sin traducir)', PokemonLocationKind.other),
  0x032A: PokemonLocation('Olivine Lighthouse 1F (sin traducir)', PokemonLocationKind.other),
  0x032B: PokemonLocation('Olivine Lighthouse 2F (sin traducir)', PokemonLocationKind.other),
  0x032C: PokemonLocation('Olivine Lighthouse 3F (sin traducir)', PokemonLocationKind.other),
  0x032D: PokemonLocation('Olivine Lighthouse 4F (sin traducir)', PokemonLocationKind.other),
  0x032E: PokemonLocation('Olivine Lighthouse 5F (sin traducir)', PokemonLocationKind.other),
  0x032F: PokemonLocation('Olivine Lighthouse 6F (sin traducir)', PokemonLocationKind.other),
  0x0330: PokemonLocation('Mahogany Mart 1F (sin traducir)', PokemonLocationKind.other),
  0x0331: PokemonLocation('Team Rocket Base B1F (sin traducir)', PokemonLocationKind.other),
  0x0332: PokemonLocation('Team Rocket Base B2F (sin traducir)', PokemonLocationKind.other),
  0x0333: PokemonLocation('Team Rocket Base B3F (sin traducir)', PokemonLocationKind.other),
  0x0334: PokemonLocation('Bosque Azalea', PokemonLocationKind.other),
  0x0335: PokemonLocation('Goldenrod Underground (sin traducir)', PokemonLocationKind.other),
  0x0336: PokemonLocation('Goldenrod Underground Switch Room Entrances (sin traducir)', PokemonLocationKind.other),
  0x0337: PokemonLocation('Goldenrod Dept Store B1F (sin traducir)', PokemonLocationKind.other),
  0x0338: PokemonLocation('Goldenrod Underground Warehouse (sin traducir)', PokemonLocationKind.other),
  0x0339: PokemonLocation('Mount Mortar 1F Outside (sin traducir)', PokemonLocationKind.other),
  0x033A: PokemonLocation('Mount Mortar 1F Inside (sin traducir)', PokemonLocationKind.other),
  0x033B: PokemonLocation('Mount Mortar 2F Inside (sin traducir)', PokemonLocationKind.other),
  0x033C: PokemonLocation('Mount Mortar B1F (sin traducir)', PokemonLocationKind.other),
  0x033D: PokemonLocation('Camino Helado', PokemonLocationKind.other),
  0x033E: PokemonLocation('Ice Path B1F (sin traducir)', PokemonLocationKind.other),
  0x033F: PokemonLocation('Ice Path B2F Mahogany Side (sin traducir)', PokemonLocationKind.other),
  0x0340: PokemonLocation('Ice Path B2F Blackthorn Side (sin traducir)', PokemonLocationKind.other),
  0x0341: PokemonLocation('Ice Path B3F (sin traducir)', PokemonLocationKind.other),
  0x0342: PokemonLocation('Islas Remolino', PokemonLocationKind.other),
  0x0343: PokemonLocation('Whirl Island Ne (sin traducir)', PokemonLocationKind.other),
  0x0344: PokemonLocation('Whirl Island Sw (sin traducir)', PokemonLocationKind.other),
  0x0345: PokemonLocation('Whirl Island Cave (sin traducir)', PokemonLocationKind.other),
  0x0346: PokemonLocation('Whirl Island Se (sin traducir)', PokemonLocationKind.other),
  0x0347: PokemonLocation('Whirl Island B1F (sin traducir)', PokemonLocationKind.other),
  0x0348: PokemonLocation('Whirl Island B2F (sin traducir)', PokemonLocationKind.other),
  0x0349: PokemonLocation('Whirl Island Lugia Chamber (sin traducir)', PokemonLocationKind.other),
  0x034A: PokemonLocation('Silver Cave Room 1 (sin traducir)', PokemonLocationKind.other),
  0x034B: PokemonLocation('Silver Cave Room 2 (sin traducir)', PokemonLocationKind.other),
  0x034C: PokemonLocation('Silver Cave Room 3 (sin traducir)', PokemonLocationKind.other),
  0x034D: PokemonLocation('Silver Cave Item Rooms (sin traducir)', PokemonLocationKind.other),
  0x034E: PokemonLocation('Cueva Oscura (entrada Malva)', PokemonLocationKind.other),
  0x034F: PokemonLocation('Cueva Oscura (entrada Endrino)', PokemonLocationKind.other),
  0x0350: PokemonLocation('Guarida Dragón', PokemonLocationKind.other),
  0x0351: PokemonLocation('Dragons Den B1F (sin traducir)', PokemonLocationKind.other),
  0x0352: PokemonLocation('Dragon Shrine (sin traducir)', PokemonLocationKind.other),
  0x0353: PokemonLocation('Tohjo Falls (sin traducir)', PokemonLocationKind.other),
  0x0354: PokemonLocation('Digletts Cave (sin traducir)', PokemonLocationKind.other),
  0x0355: PokemonLocation('Mount Moon (sin traducir)', PokemonLocationKind.other),
  0x0356: PokemonLocation('Underground Path (sin traducir)', PokemonLocationKind.other),
  0x0357: PokemonLocation('Rock Tunnel 1F (sin traducir)', PokemonLocationKind.other),
  0x0358: PokemonLocation('Rock Tunnel B1F (sin traducir)', PokemonLocationKind.other),
  0x0359: PokemonLocation('Safari Zone Fuchsia Gate Beta (sin traducir)', PokemonLocationKind.other),
  0x035A: PokemonLocation('Safari Zone Beta (sin traducir)', PokemonLocationKind.other),
  0x035B: PokemonLocation('Victory Road (sin traducir)', PokemonLocationKind.league),
  0x0401: PokemonLocation('Ecruteak Tin Tower Entrance (sin traducir)', PokemonLocationKind.other),
  0x0402: PokemonLocation('Wise Trios Room (sin traducir)', PokemonLocationKind.other),
  0x0403: PokemonLocation('Ecruteak Pokecenter 1F (sin traducir)', PokemonLocationKind.other),
  0x0404: PokemonLocation('Ecruteak Lugia Speech House (sin traducir)', PokemonLocationKind.other),
  0x0405: PokemonLocation('Dance Theater (sin traducir)', PokemonLocationKind.other),
  0x0406: PokemonLocation('Ecruteak Mart (sin traducir)', PokemonLocationKind.other),
  0x0407: PokemonLocation('Ecruteak Gym (sin traducir)', PokemonLocationKind.gym),
  0x0408: PokemonLocation('Ecruteak Itemfinder House (sin traducir)', PokemonLocationKind.other),
  0x0409: PokemonLocation('Ciudad Iris', PokemonLocationKind.city),
  0x0501: PokemonLocation('Blackthorn Gym 1F (sin traducir)', PokemonLocationKind.gym),
  0x0502: PokemonLocation('Blackthorn Gym 2F (sin traducir)', PokemonLocationKind.gym),
  0x0503: PokemonLocation('Blackthorn Dragon Speech House (sin traducir)', PokemonLocationKind.other),
  0x0504: PokemonLocation('Blackthorn Emys House (sin traducir)', PokemonLocationKind.other),
  0x0505: PokemonLocation('Blackthorn Mart (sin traducir)', PokemonLocationKind.other),
  0x0506: PokemonLocation('Blackthorn Pokecenter 1F (sin traducir)', PokemonLocationKind.other),
  0x0507: PokemonLocation('Move Deleters House (sin traducir)', PokemonLocationKind.other),
  0x0508: PokemonLocation('Route 45 (sin traducir)', PokemonLocationKind.route),
  0x0509: PokemonLocation('Route 46 (sin traducir)', PokemonLocationKind.route),
  0x050A: PokemonLocation('Ciudad Endrino', PokemonLocationKind.city),
  0x0601: PokemonLocation('Cinnabar Pokecenter 1F (sin traducir)', PokemonLocationKind.other),
  0x0602: PokemonLocation('Cinnabar Pokecenter 2F Beta (sin traducir)', PokemonLocationKind.other),
  0x0603: PokemonLocation('Route 19 Fuchsia Gate (sin traducir)', PokemonLocationKind.route),
  0x0604: PokemonLocation('Seafoam Gym (sin traducir)', PokemonLocationKind.gym),
  0x0605: PokemonLocation('Route 19 (sin traducir)', PokemonLocationKind.route),
  0x0606: PokemonLocation('Route 20 (sin traducir)', PokemonLocationKind.route),
  0x0607: PokemonLocation('Route 21 (sin traducir)', PokemonLocationKind.route),
  0x0608: PokemonLocation('Isla Canela', PokemonLocationKind.other),
  0x0701: PokemonLocation('Cerulean Gym Badge Speech House (sin traducir)', PokemonLocationKind.gym),
  0x0702: PokemonLocation('Cerulean Police Station (sin traducir)', PokemonLocationKind.other),
  0x0703: PokemonLocation('Cerulean Trade Speech House (sin traducir)', PokemonLocationKind.other),
  0x0704: PokemonLocation('Cerulean Pokecenter 1F (sin traducir)', PokemonLocationKind.other),
  0x0705: PokemonLocation('Cerulean Pokecenter 2F Beta (sin traducir)', PokemonLocationKind.other),
  0x0706: PokemonLocation('Cerulean Gym (sin traducir)', PokemonLocationKind.gym),
  0x0707: PokemonLocation('Cerulean Mart (sin traducir)', PokemonLocationKind.other),
  0x0708: PokemonLocation('Route 10 Pokecenter 1F (sin traducir)', PokemonLocationKind.route),
  0x0709: PokemonLocation('Route 10 Pokecenter 2F Beta (sin traducir)', PokemonLocationKind.route),
  0x070A: PokemonLocation('Power Plant (sin traducir)', PokemonLocationKind.other),
  0x070B: PokemonLocation('Bills House (sin traducir)', PokemonLocationKind.other),
  0x070C: PokemonLocation('Route 4 (sin traducir)', PokemonLocationKind.route),
  0x070D: PokemonLocation('Route 9 (sin traducir)', PokemonLocationKind.route),
  0x070E: PokemonLocation('Route 10 North (sin traducir)', PokemonLocationKind.route),
  0x070F: PokemonLocation('Route 24 (sin traducir)', PokemonLocationKind.route),
  0x0710: PokemonLocation('Route 25 (sin traducir)', PokemonLocationKind.route),
  0x0711: PokemonLocation('Ciudad Celeste', PokemonLocationKind.city),
  0x0801: PokemonLocation('Azalea Pokecenter 1F (sin traducir)', PokemonLocationKind.other),
  0x0802: PokemonLocation('Charcoal Kiln (sin traducir)', PokemonLocationKind.other),
  0x0803: PokemonLocation('Azalea Mart (sin traducir)', PokemonLocationKind.other),
  0x0804: PokemonLocation('Kurts House (sin traducir)', PokemonLocationKind.other),
  0x0805: PokemonLocation('Azalea Gym (sin traducir)', PokemonLocationKind.gym),
  0x0806: PokemonLocation('Route 33 (sin traducir)', PokemonLocationKind.route),
  0x0807: PokemonLocation('Pueblo Azalea', PokemonLocationKind.city),
  0x0901: PokemonLocation('Lake Of Rage Hidden Power House (sin traducir)', PokemonLocationKind.other),
  0x0902: PokemonLocation('Lake Of Rage Magikarp House (sin traducir)', PokemonLocationKind.other),
  0x0903: PokemonLocation('Route 43 Mahogany Gate (sin traducir)', PokemonLocationKind.route),
  0x0904: PokemonLocation('Route 43 Gate (sin traducir)', PokemonLocationKind.route),
  0x0905: PokemonLocation('Route 43 (sin traducir)', PokemonLocationKind.route),
  0x0906: PokemonLocation('Lago Furia', PokemonLocationKind.other),
  0x0A01: PokemonLocation('Route 32 (sin traducir)', PokemonLocationKind.route),
  0x0A02: PokemonLocation('Route 35 (sin traducir)', PokemonLocationKind.route),
  0x0A03: PokemonLocation('Route 36 (sin traducir)', PokemonLocationKind.route),
  0x0A04: PokemonLocation('Route 37 (sin traducir)', PokemonLocationKind.route),
  0x0A05: PokemonLocation('Ciudad Malva', PokemonLocationKind.city),
  0x0A06: PokemonLocation('Violet Mart (sin traducir)', PokemonLocationKind.other),
  0x0A07: PokemonLocation('Violet Gym (sin traducir)', PokemonLocationKind.gym),
  0x0A08: PokemonLocation('Earls Pokemon Academy (sin traducir)', PokemonLocationKind.other),
  0x0A09: PokemonLocation('Violet Nickname Speech House (sin traducir)', PokemonLocationKind.other),
  0x0A0A: PokemonLocation('Violet Pokecenter 1F (sin traducir)', PokemonLocationKind.other),
  0x0A0B: PokemonLocation('Violet Kyles House (sin traducir)', PokemonLocationKind.other),
  0x0A0C: PokemonLocation('Route 32 Ruins Of Alph Gate (sin traducir)', PokemonLocationKind.route),
  0x0A0D: PokemonLocation('Route 32 Pokecenter 1F (sin traducir)', PokemonLocationKind.route),
  0x0A0E: PokemonLocation('Route 35 Goldenrod Gate (sin traducir)', PokemonLocationKind.route),
  0x0A0F: PokemonLocation('Route 35 National Park Gate (sin traducir)', PokemonLocationKind.route),
  0x0A10: PokemonLocation('Route 36 Ruins Of Alph Gate (sin traducir)', PokemonLocationKind.route),
  0x0A11: PokemonLocation('Route 36 National Park Gate (sin traducir)', PokemonLocationKind.route),
  0x0B01: PokemonLocation('Route 34 (sin traducir)', PokemonLocationKind.route),
  0x0B02: PokemonLocation('Ciudad Trigal', PokemonLocationKind.city),
  0x0B03: PokemonLocation('Goldenrod Gym (sin traducir)', PokemonLocationKind.gym),
  0x0B04: PokemonLocation('Goldenrod Bike Shop (sin traducir)', PokemonLocationKind.other),
  0x0B05: PokemonLocation('Goldenrod Happiness Rater (sin traducir)', PokemonLocationKind.other),
  0x0B06: PokemonLocation('Bills Familys House (sin traducir)', PokemonLocationKind.other),
  0x0B07: PokemonLocation('Goldenrod Magnet Train Station (sin traducir)', PokemonLocationKind.other),
  0x0B08: PokemonLocation('Goldenrod Flower Shop (sin traducir)', PokemonLocationKind.other),
  0x0B09: PokemonLocation('Goldenrod Pp Speech House (sin traducir)', PokemonLocationKind.other),
  0x0B0A: PokemonLocation('Goldenrod Name Rater (sin traducir)', PokemonLocationKind.other),
  0x0B0B: PokemonLocation('Goldenrod Dept Store 1F (sin traducir)', PokemonLocationKind.other),
  0x0B0C: PokemonLocation('Goldenrod Dept Store 2F (sin traducir)', PokemonLocationKind.other),
  0x0B0D: PokemonLocation('Goldenrod Dept Store 3F (sin traducir)', PokemonLocationKind.other),
  0x0B0E: PokemonLocation('Goldenrod Dept Store 4F (sin traducir)', PokemonLocationKind.other),
  0x0B0F: PokemonLocation('Goldenrod Dept Store 5F (sin traducir)', PokemonLocationKind.other),
  0x0B10: PokemonLocation('Goldenrod Dept Store 6F (sin traducir)', PokemonLocationKind.other),
  0x0B11: PokemonLocation('Goldenrod Dept Store Elevator (sin traducir)', PokemonLocationKind.other),
  0x0B12: PokemonLocation('Goldenrod Dept Store Roof (sin traducir)', PokemonLocationKind.other),
  0x0B13: PokemonLocation('Goldenrod Game Corner (sin traducir)', PokemonLocationKind.other),
  0x0B14: PokemonLocation('Goldenrod Pokecenter 1F (sin traducir)', PokemonLocationKind.other),
  0x0B15: PokemonLocation('Pokecom Center Admin Office Mobile (sin traducir)', PokemonLocationKind.other),
  0x0B16: PokemonLocation('Ilex Forest Azalea Gate (sin traducir)', PokemonLocationKind.other),
  0x0B17: PokemonLocation('Route 34 Ilex Forest Gate (sin traducir)', PokemonLocationKind.route),
  0x0B18: PokemonLocation('Day Care (sin traducir)', PokemonLocationKind.other),
  0x0C01: PokemonLocation('Route 6 (sin traducir)', PokemonLocationKind.route),
  0x0C02: PokemonLocation('Route 11 (sin traducir)', PokemonLocationKind.route),
  0x0C03: PokemonLocation('Ciudad Carmín', PokemonLocationKind.city),
  0x0C04: PokemonLocation('Vermilion Fishing Speech House (sin traducir)', PokemonLocationKind.other),
  0x0C05: PokemonLocation('Vermilion Pokecenter 1F (sin traducir)', PokemonLocationKind.other),
  0x0C06: PokemonLocation('Vermilion Pokecenter 2F Beta (sin traducir)', PokemonLocationKind.other),
  0x0C07: PokemonLocation('Pokemon Fan Club (sin traducir)', PokemonLocationKind.other),
  0x0C08: PokemonLocation('Vermilion Magnet Train Speech House (sin traducir)', PokemonLocationKind.other),
  0x0C09: PokemonLocation('Vermilion Mart (sin traducir)', PokemonLocationKind.other),
  0x0C0A: PokemonLocation('Vermilion Digletts Cave Speech House (sin traducir)', PokemonLocationKind.other),
  0x0C0B: PokemonLocation('Vermilion Gym (sin traducir)', PokemonLocationKind.gym),
  0x0C0C: PokemonLocation('Route 6 Saffron Gate (sin traducir)', PokemonLocationKind.route),
  0x0C0D: PokemonLocation('Route 6 Underground Path Entrance (sin traducir)', PokemonLocationKind.route),
  0x0D01: PokemonLocation('Route 1 (sin traducir)', PokemonLocationKind.route),
  0x0D02: PokemonLocation('Pueblo Paleta', PokemonLocationKind.city),
  0x0D03: PokemonLocation('Reds House 1F (sin traducir)', PokemonLocationKind.other),
  0x0D04: PokemonLocation('Reds House 2F (sin traducir)', PokemonLocationKind.other),
  0x0D05: PokemonLocation('Blues House (sin traducir)', PokemonLocationKind.other),
  0x0D06: PokemonLocation('Oaks Lab (sin traducir)', PokemonLocationKind.other),
  0x0E01: PokemonLocation('Route 3 (sin traducir)', PokemonLocationKind.route),
  0x0E02: PokemonLocation('Ciudad Plateada', PokemonLocationKind.city),
  0x0E03: PokemonLocation('Pewter Nidoran Speech House (sin traducir)', PokemonLocationKind.other),
  0x0E04: PokemonLocation('Pewter Gym (sin traducir)', PokemonLocationKind.gym),
  0x0E05: PokemonLocation('Pewter Mart (sin traducir)', PokemonLocationKind.other),
  0x0E06: PokemonLocation('Pewter Pokecenter 1F (sin traducir)', PokemonLocationKind.other),
  0x0E07: PokemonLocation('Pewter Pokecenter 2F Beta (sin traducir)', PokemonLocationKind.other),
  0x0E08: PokemonLocation('Pewter Snooze Speech House (sin traducir)', PokemonLocationKind.other),
  0x0F01: PokemonLocation('Puerto de Ciudad Olivo', PokemonLocationKind.other),
  0x0F02: PokemonLocation('Vermilion Port (sin traducir)', PokemonLocationKind.other),
  0x0F03: PokemonLocation('Fast Ship 1F (sin traducir)', PokemonLocationKind.other),
  0x0F04: PokemonLocation('Fast Ship Cabins Nnw Nne Ne (sin traducir)', PokemonLocationKind.other),
  0x0F05: PokemonLocation('Fast Ship Cabins Sw Ssw Nw (sin traducir)', PokemonLocationKind.other),
  0x0F06: PokemonLocation('Fast Ship Cabins Se Sse Captains Cabin (sin traducir)', PokemonLocationKind.other),
  0x0F07: PokemonLocation('Fast Ship B1F (sin traducir)', PokemonLocationKind.other),
  0x0F08: PokemonLocation('Olivine Port Passage (sin traducir)', PokemonLocationKind.other),
  0x0F09: PokemonLocation('Vermilion Port Passage (sin traducir)', PokemonLocationKind.other),
  0x0F0A: PokemonLocation('Mount Moon Square (sin traducir)', PokemonLocationKind.other),
  0x0F0B: PokemonLocation('Mount Moon Gift Shop (sin traducir)', PokemonLocationKind.other),
  0x0F0C: PokemonLocation('Tin Tower Roof (sin traducir)', PokemonLocationKind.other),
  0x1001: PokemonLocation('Route 23 (sin traducir)', PokemonLocationKind.route),
  0x1002: PokemonLocation('Indigo Plateau Pokecenter 1F (sin traducir)', PokemonLocationKind.league),
  0x1003: PokemonLocation('Wills Room (sin traducir)', PokemonLocationKind.other),
  0x1004: PokemonLocation('Kogas Room (sin traducir)', PokemonLocationKind.other),
  0x1005: PokemonLocation('Brunos Room (sin traducir)', PokemonLocationKind.other),
  0x1006: PokemonLocation('Karens Room (sin traducir)', PokemonLocationKind.other),
  0x1007: PokemonLocation('Lances Room (sin traducir)', PokemonLocationKind.other),
  0x1008: PokemonLocation('Hall Of Fame (sin traducir)', PokemonLocationKind.other),
  0x1101: PokemonLocation('Route 13 (sin traducir)', PokemonLocationKind.route),
  0x1102: PokemonLocation('Route 14 (sin traducir)', PokemonLocationKind.route),
  0x1103: PokemonLocation('Route 15 (sin traducir)', PokemonLocationKind.route),
  0x1104: PokemonLocation('Route 18 (sin traducir)', PokemonLocationKind.route),
  0x1105: PokemonLocation('Ciudad Fucsia', PokemonLocationKind.city),
  0x1106: PokemonLocation('Fuchsia Mart (sin traducir)', PokemonLocationKind.other),
  0x1107: PokemonLocation('Safari Zone Main Office (sin traducir)', PokemonLocationKind.other),
  0x1108: PokemonLocation('Fuchsia Gym (sin traducir)', PokemonLocationKind.gym),
  0x1109: PokemonLocation('Bills Older Sisters House (sin traducir)', PokemonLocationKind.other),
  0x110A: PokemonLocation('Fuchsia Pokecenter 1F (sin traducir)', PokemonLocationKind.other),
  0x110B: PokemonLocation('Fuchsia Pokecenter 2F Beta (sin traducir)', PokemonLocationKind.other),
  0x110C: PokemonLocation('Safari Zone Wardens Home (sin traducir)', PokemonLocationKind.other),
  0x110D: PokemonLocation('Route 15 Fuchsia Gate (sin traducir)', PokemonLocationKind.route),
  0x1201: PokemonLocation('Route 8 (sin traducir)', PokemonLocationKind.route),
  0x1202: PokemonLocation('Route 12 (sin traducir)', PokemonLocationKind.route),
  0x1203: PokemonLocation('Route 10 South (sin traducir)', PokemonLocationKind.route),
  0x1204: PokemonLocation('Pueblo Lavanda', PokemonLocationKind.city),
  0x1205: PokemonLocation('Lavender Pokecenter 1F (sin traducir)', PokemonLocationKind.other),
  0x1206: PokemonLocation('Lavender Pokecenter 2F Beta (sin traducir)', PokemonLocationKind.other),
  0x1207: PokemonLocation('Mr Fujis House (sin traducir)', PokemonLocationKind.other),
  0x1208: PokemonLocation('Lavender Speech House (sin traducir)', PokemonLocationKind.other),
  0x1209: PokemonLocation('Lavender Name Rater (sin traducir)', PokemonLocationKind.other),
  0x120A: PokemonLocation('Lavender Mart (sin traducir)', PokemonLocationKind.other),
  0x120B: PokemonLocation('Soul House (sin traducir)', PokemonLocationKind.other),
  0x120C: PokemonLocation('Lav Radio Tower 1F (sin traducir)', PokemonLocationKind.other),
  0x120D: PokemonLocation('Route 8 Saffron Gate (sin traducir)', PokemonLocationKind.route),
  0x120E: PokemonLocation('Route 12 Super Rod House (sin traducir)', PokemonLocationKind.route),
  0x1301: PokemonLocation('Route 28 (sin traducir)', PokemonLocationKind.route),
  0x1302: PokemonLocation('Cueva Plateada', PokemonLocationKind.other),
  0x1303: PokemonLocation('Silver Cave Pokecenter 1F (sin traducir)', PokemonLocationKind.other),
  0x1304: PokemonLocation('Route 28 Steel Wing House (sin traducir)', PokemonLocationKind.route),
  0x1401: PokemonLocation('Pokecenter 2F (sin traducir)', PokemonLocationKind.other),
  0x1402: PokemonLocation('Trade Center (sin traducir)', PokemonLocationKind.other),
  0x1403: PokemonLocation('Colosseum (sin traducir)', PokemonLocationKind.other),
  0x1404: PokemonLocation('Time Capsule (sin traducir)', PokemonLocationKind.other),
  0x1405: PokemonLocation('Mobile Trade Room (sin traducir)', PokemonLocationKind.other),
  0x1406: PokemonLocation('Mobile Battle Room (sin traducir)', PokemonLocationKind.other),
  0x1501: PokemonLocation('Route 7 (sin traducir)', PokemonLocationKind.route),
  0x1502: PokemonLocation('Route 16 (sin traducir)', PokemonLocationKind.route),
  0x1503: PokemonLocation('Route 17 (sin traducir)', PokemonLocationKind.route),
  0x1504: PokemonLocation('Ciudad Azulona', PokemonLocationKind.city),
  0x1505: PokemonLocation('Celadon Dept Store 1F (sin traducir)', PokemonLocationKind.other),
  0x1506: PokemonLocation('Celadon Dept Store 2F (sin traducir)', PokemonLocationKind.other),
  0x1507: PokemonLocation('Celadon Dept Store 3F (sin traducir)', PokemonLocationKind.other),
  0x1508: PokemonLocation('Celadon Dept Store 4F (sin traducir)', PokemonLocationKind.other),
  0x1509: PokemonLocation('Celadon Dept Store 5F (sin traducir)', PokemonLocationKind.other),
  0x150A: PokemonLocation('Celadon Dept Store 6F (sin traducir)', PokemonLocationKind.other),
  0x150B: PokemonLocation('Celadon Dept Store Elevator (sin traducir)', PokemonLocationKind.other),
  0x150C: PokemonLocation('Celadon Mansion 1F (sin traducir)', PokemonLocationKind.other),
  0x150D: PokemonLocation('Celadon Mansion 2F (sin traducir)', PokemonLocationKind.other),
  0x150E: PokemonLocation('Celadon Mansion 3F (sin traducir)', PokemonLocationKind.other),
  0x150F: PokemonLocation('Celadon Mansion Roof (sin traducir)', PokemonLocationKind.other),
  0x1510: PokemonLocation('Celadon Mansion Roof House (sin traducir)', PokemonLocationKind.other),
  0x1511: PokemonLocation('Celadon Pokecenter 1F (sin traducir)', PokemonLocationKind.other),
  0x1512: PokemonLocation('Celadon Pokecenter 2F Beta (sin traducir)', PokemonLocationKind.other),
  0x1513: PokemonLocation('Celadon Game Corner (sin traducir)', PokemonLocationKind.other),
  0x1514: PokemonLocation('Celadon Game Corner Prize Room (sin traducir)', PokemonLocationKind.other),
  0x1515: PokemonLocation('Celadon Gym (sin traducir)', PokemonLocationKind.gym),
  0x1516: PokemonLocation('Celadon Cafe (sin traducir)', PokemonLocationKind.other),
  0x1517: PokemonLocation('Route 16 Fuchsia Speech House (sin traducir)', PokemonLocationKind.route),
  0x1518: PokemonLocation('Route 16 Gate (sin traducir)', PokemonLocationKind.route),
  0x1519: PokemonLocation('Route 7 Saffron Gate (sin traducir)', PokemonLocationKind.route),
  0x151A: PokemonLocation('Route 17 Route 18 Gate (sin traducir)', PokemonLocationKind.route),
  0x1601: PokemonLocation('Route 40 (sin traducir)', PokemonLocationKind.route),
  0x1602: PokemonLocation('Route 41 (sin traducir)', PokemonLocationKind.route),
  0x1603: PokemonLocation('Ciudad Orquídea', PokemonLocationKind.city),
  0x1604: PokemonLocation('Manias House (sin traducir)', PokemonLocationKind.other),
  0x1605: PokemonLocation('Cianwood Gym (sin traducir)', PokemonLocationKind.gym),
  0x1606: PokemonLocation('Cianwood Pokecenter 1F (sin traducir)', PokemonLocationKind.other),
  0x1607: PokemonLocation('Cianwood Pharmacy (sin traducir)', PokemonLocationKind.other),
  0x1608: PokemonLocation('Cianwood Photo Studio (sin traducir)', PokemonLocationKind.other),
  0x1609: PokemonLocation('Cianwood Lugia Speech House (sin traducir)', PokemonLocationKind.other),
  0x160A: PokemonLocation('Poke Seers House (sin traducir)', PokemonLocationKind.other),
  0x160B: PokemonLocation('Battle Tower 1F (sin traducir)', PokemonLocationKind.other),
  0x160C: PokemonLocation('Battle Tower Battle Room (sin traducir)', PokemonLocationKind.other),
  0x160D: PokemonLocation('Battle Tower Elevator (sin traducir)', PokemonLocationKind.other),
  0x160E: PokemonLocation('Battle Tower Hallway (sin traducir)', PokemonLocationKind.other),
  0x160F: PokemonLocation('Route 40 Battle Tower Gate (sin traducir)', PokemonLocationKind.route),
  0x1610: PokemonLocation('Battle Tower Outside (sin traducir)', PokemonLocationKind.other),
  0x1701: PokemonLocation('Route 2 (sin traducir)', PokemonLocationKind.route),
  0x1702: PokemonLocation('Route 22 (sin traducir)', PokemonLocationKind.route),
  0x1703: PokemonLocation('Ciudad Verde', PokemonLocationKind.city),
  0x1704: PokemonLocation('Viridian Gym (sin traducir)', PokemonLocationKind.gym),
  0x1705: PokemonLocation('Viridian Nickname Speech House (sin traducir)', PokemonLocationKind.other),
  0x1706: PokemonLocation('Trainer House 1F (sin traducir)', PokemonLocationKind.other),
  0x1707: PokemonLocation('Trainer House B1F (sin traducir)', PokemonLocationKind.other),
  0x1708: PokemonLocation('Viridian Mart (sin traducir)', PokemonLocationKind.other),
  0x1709: PokemonLocation('Viridian Pokecenter 1F (sin traducir)', PokemonLocationKind.other),
  0x170A: PokemonLocation('Viridian Pokecenter 2F Beta (sin traducir)', PokemonLocationKind.other),
  0x170B: PokemonLocation('Route 2 Nugget House (sin traducir)', PokemonLocationKind.route),
  0x170C: PokemonLocation('Route 2 Gate (sin traducir)', PokemonLocationKind.route),
  0x170D: PokemonLocation('Calle Victoria', PokemonLocationKind.league),
  0x1801: PokemonLocation('Route 26 (sin traducir)', PokemonLocationKind.route),
  0x1802: PokemonLocation('Route 27 (sin traducir)', PokemonLocationKind.route),
  0x1803: PokemonLocation('Route 29 (sin traducir)', PokemonLocationKind.route),
  0x1804: PokemonLocation('Pueblo Primavera', PokemonLocationKind.city),
  0x1805: PokemonLocation('Elms Lab (sin traducir)', PokemonLocationKind.other),
  0x1806: PokemonLocation('Players House 1F (sin traducir)', PokemonLocationKind.other),
  0x1807: PokemonLocation('Players House 2F (sin traducir)', PokemonLocationKind.other),
  0x1808: PokemonLocation('Players Neighbors House (sin traducir)', PokemonLocationKind.other),
  0x1809: PokemonLocation('Elms House (sin traducir)', PokemonLocationKind.other),
  0x180A: PokemonLocation('Route 26 Heal House (sin traducir)', PokemonLocationKind.route),
  0x180B: PokemonLocation('Day Of Week Siblings House (sin traducir)', PokemonLocationKind.other),
  0x180C: PokemonLocation('Route 27 Sandstorm House (sin traducir)', PokemonLocationKind.route),
  0x180D: PokemonLocation('Route 29 Route 46 Gate (sin traducir)', PokemonLocationKind.route),
  0x1901: PokemonLocation('Route 5 (sin traducir)', PokemonLocationKind.route),
  0x1902: PokemonLocation('Ciudad Azafrán', PokemonLocationKind.city),
  0x1903: PokemonLocation('Fighting Dojo (sin traducir)', PokemonLocationKind.other),
  0x1904: PokemonLocation('Saffron Gym (sin traducir)', PokemonLocationKind.gym),
  0x1905: PokemonLocation('Saffron Mart (sin traducir)', PokemonLocationKind.other),
  0x1906: PokemonLocation('Saffron Pokecenter 1F (sin traducir)', PokemonLocationKind.other),
  0x1907: PokemonLocation('Saffron Pokecenter 2F Beta (sin traducir)', PokemonLocationKind.other),
  0x1908: PokemonLocation('Mr Psychics House (sin traducir)', PokemonLocationKind.other),
  0x1909: PokemonLocation('Saffron Magnet Train Station (sin traducir)', PokemonLocationKind.other),
  0x190A: PokemonLocation('Silph Co 1F (sin traducir)', PokemonLocationKind.other),
  0x190B: PokemonLocation('Copycats House 1F (sin traducir)', PokemonLocationKind.other),
  0x190C: PokemonLocation('Copycats House 2F (sin traducir)', PokemonLocationKind.other),
  0x190D: PokemonLocation('Route 5 Underground Path Entrance (sin traducir)', PokemonLocationKind.route),
  0x190E: PokemonLocation('Route 5 Saffron Gate (sin traducir)', PokemonLocationKind.route),
  0x190F: PokemonLocation('Route 5 Cleanse Tag House (sin traducir)', PokemonLocationKind.route),
  0x1A01: PokemonLocation('Route 30 (sin traducir)', PokemonLocationKind.route),
  0x1A02: PokemonLocation('Route 31 (sin traducir)', PokemonLocationKind.route),
  0x1A03: PokemonLocation('Ciudad Cerezo', PokemonLocationKind.city),
  0x1A04: PokemonLocation('Cherrygrove Mart (sin traducir)', PokemonLocationKind.other),
  0x1A05: PokemonLocation('Cherrygrove Pokecenter 1F (sin traducir)', PokemonLocationKind.other),
  0x1A06: PokemonLocation('Cherrygrove Gym Speech House (sin traducir)', PokemonLocationKind.gym),
  0x1A07: PokemonLocation('Guide Gents House (sin traducir)', PokemonLocationKind.other),
  0x1A08: PokemonLocation('Cherrygrove Evolution Speech House (sin traducir)', PokemonLocationKind.other),
  0x1A09: PokemonLocation('Route 30 Berry House (sin traducir)', PokemonLocationKind.route),
  0x1A0A: PokemonLocation('Mr Pokemons House (sin traducir)', PokemonLocationKind.other),
  0x1A0B: PokemonLocation('Route 31 Violet Gate (sin traducir)', PokemonLocationKind.route),
};
