import '../../../models/pokemon_location.dart';

/// Ubicaciones de Pokémon Esmeralda.
///
/// Las claves usan `grupo << 8 | número` y siguen el orden de
/// `data/maps/map_groups.json` de pret/pokeemerald.
const Map<int, PokemonLocation> emeraldLocations =
    <int, PokemonLocation>{
  0x0000: PokemonLocation('Ciudad Petalia', PokemonLocationKind.city),
  0x0001: PokemonLocation('Ciudad Portual', PokemonLocationKind.city),
  0x0002: PokemonLocation('Ciudad Malvalona', PokemonLocationKind.city),
  0x0003: PokemonLocation('Ciudad Férrica', PokemonLocationKind.city),
  0x0004: PokemonLocation('Ciudad Arborada', PokemonLocationKind.city),
  0x0005: PokemonLocation('Ciudad Calagua', PokemonLocationKind.city),
  0x0006: PokemonLocation('Ciudad Algaria', PokemonLocationKind.city),
  0x0007: PokemonLocation('Arrecípolis', PokemonLocationKind.city),
  0x0008: PokemonLocation('Ciudad Colosalia', PokemonLocationKind.league),
  0x0009: PokemonLocation('Villa Raíz', PokemonLocationKind.city),
  0x000A: PokemonLocation('Pueblo Escaso', PokemonLocationKind.city),
  0x000B: PokemonLocation('Pueblo Azuliza', PokemonLocationKind.city),
  0x000C: PokemonLocation('Pueblo Lavacalda', PokemonLocationKind.city),
  0x000D: PokemonLocation('Pueblo Pardal', PokemonLocationKind.city),
  0x000E: PokemonLocation('Pueblo Verdegal', PokemonLocationKind.city),
  0x000F: PokemonLocation('Pueblo Oromar', PokemonLocationKind.city),
  0x0010: PokemonLocation('Ruta 101', PokemonLocationKind.route),
  0x0011: PokemonLocation('Ruta 102', PokemonLocationKind.route),
  0x0012: PokemonLocation('Ruta 103', PokemonLocationKind.route),
  0x0013: PokemonLocation('Ruta 104', PokemonLocationKind.route),
  0x0014: PokemonLocation('Ruta 105', PokemonLocationKind.route),
  0x0015: PokemonLocation('Ruta 106', PokemonLocationKind.route),
  0x0016: PokemonLocation('Ruta 107', PokemonLocationKind.route),
  0x0017: PokemonLocation('Ruta 108', PokemonLocationKind.route),
  0x0018: PokemonLocation('Ruta 109', PokemonLocationKind.route),
  0x0019: PokemonLocation('Ruta 110', PokemonLocationKind.route),
  0x001A: PokemonLocation('Ruta 111', PokemonLocationKind.route),
  0x001B: PokemonLocation('Ruta 112', PokemonLocationKind.route),
  0x001C: PokemonLocation('Ruta 113', PokemonLocationKind.route),
  0x001D: PokemonLocation('Ruta 114', PokemonLocationKind.route),
  0x001E: PokemonLocation('Ruta 115', PokemonLocationKind.route),
  0x001F: PokemonLocation('Ruta 116', PokemonLocationKind.route),
  0x0020: PokemonLocation('Ruta 117', PokemonLocationKind.route),
  0x0021: PokemonLocation('Ruta 118', PokemonLocationKind.route),
  0x0022: PokemonLocation('Ruta 119', PokemonLocationKind.route),
  0x0023: PokemonLocation('Ruta 120', PokemonLocationKind.route),
  0x0024: PokemonLocation('Ruta 121', PokemonLocationKind.route),
  0x0025: PokemonLocation('Ruta 122', PokemonLocationKind.route),
  0x0026: PokemonLocation('Ruta 123', PokemonLocationKind.route),
  0x0027: PokemonLocation('Ruta 124', PokemonLocationKind.route),
  0x0028: PokemonLocation('Ruta 125', PokemonLocationKind.route),
  0x0029: PokemonLocation('Ruta 126', PokemonLocationKind.route),
  0x002A: PokemonLocation('Ruta 127', PokemonLocationKind.route),
  0x002B: PokemonLocation('Ruta 128', PokemonLocationKind.route),
  0x002C: PokemonLocation('Ruta 129', PokemonLocationKind.route),
  0x002D: PokemonLocation('Ruta 130', PokemonLocationKind.route),
  0x002E: PokemonLocation('Ruta 131', PokemonLocationKind.route),
  0x002F: PokemonLocation('Ruta 132', PokemonLocationKind.route),
  0x0030: PokemonLocation('Ruta 133', PokemonLocationKind.route),
  0x0031: PokemonLocation('Ruta 134', PokemonLocationKind.route),
  0x0032: PokemonLocation('Bajo el agua (Ruta 124)', PokemonLocationKind.other),
  0x0033: PokemonLocation('Bajo el agua (Ruta 126)', PokemonLocationKind.other),
  0x0034: PokemonLocation('Bajo el agua (Ruta 127)', PokemonLocationKind.other),
  0x0035: PokemonLocation('Bajo el agua (Ruta 128)', PokemonLocationKind.other),
  0x0036: PokemonLocation('Bajo el agua (Ruta 129)', PokemonLocationKind.other),
  0x0037: PokemonLocation('Bajo el agua (Ruta 105)', PokemonLocationKind.other),
  0x0038: PokemonLocation('Bajo el agua (Ruta 125)', PokemonLocationKind.other),
  0x0100: PokemonLocation('Casa de Bruno (planta baja)', PokemonLocationKind.other),
  0x0101: PokemonLocation('Casa de Bruno (planta alta)', PokemonLocationKind.other),
  0x0102: PokemonLocation('Casa de Aura (planta baja)', PokemonLocationKind.other),
  0x0103: PokemonLocation('Casa de Aura (planta alta)', PokemonLocationKind.other),
  0x0104: PokemonLocation(
    'Laboratorio del Profesor Abedul',
    PokemonLocationKind.other,
  ),
};
