import '../../../models/pokemon_location.dart';

/// Ubicaciones exteriores de Pokémon Rojo Fuego y Verde Hoja.
///
/// Las claves usan `grupo << 8 | número`. El grupo 3 corresponde a
/// `gMapGroup_TownsAndRoutes` en pret/pokefirered y es común a ambas ediciones.
const Map<int, PokemonLocation> fireRedLeafGreenLocations =
    <int, PokemonLocation>{
      0x0300: PokemonLocation('Pueblo Paleta', PokemonLocationKind.city),
      0x0301: PokemonLocation('Ciudad Verde', PokemonLocationKind.city),
      0x0302: PokemonLocation('Ciudad Plateada', PokemonLocationKind.city),
      0x0303: PokemonLocation('Ciudad Celeste', PokemonLocationKind.city),
      0x0304: PokemonLocation('Pueblo Lavanda', PokemonLocationKind.city),
      0x0305: PokemonLocation('Ciudad Carmín', PokemonLocationKind.city),
      0x0306: PokemonLocation('Ciudad Azulona', PokemonLocationKind.city),
      0x0307: PokemonLocation('Ciudad Fucsia', PokemonLocationKind.city),
      0x0308: PokemonLocation('Isla Canela', PokemonLocationKind.city),
      0x0309: PokemonLocation('Meseta Añil', PokemonLocationKind.league),
      0x030A: PokemonLocation('Ciudad Azafrán', PokemonLocationKind.city),
      0x030B: PokemonLocation('Acceso a Ciudad Azafrán', PokemonLocationKind.other),
      0x030C: PokemonLocation('Isla Prima', PokemonLocationKind.city),
      0x030D: PokemonLocation('Isla Secunda', PokemonLocationKind.city),
      0x030E: PokemonLocation('Isla Tera', PokemonLocationKind.city),
      0x030F: PokemonLocation('Isla Quarta', PokemonLocationKind.city),
      0x0310: PokemonLocation('Isla Inta', PokemonLocationKind.city),
      0x0311: PokemonLocation('Isla Sétima', PokemonLocationKind.city),
      0x0312: PokemonLocation('Isla Exta', PokemonLocationKind.city),
      0x0313: PokemonLocation('Ruta 1', PokemonLocationKind.route),
      0x0314: PokemonLocation('Ruta 2', PokemonLocationKind.route),
      0x0315: PokemonLocation('Ruta 3', PokemonLocationKind.route),
      0x0316: PokemonLocation('Ruta 4', PokemonLocationKind.route),
      0x0317: PokemonLocation('Ruta 5', PokemonLocationKind.route),
      0x0318: PokemonLocation('Ruta 6', PokemonLocationKind.route),
      0x0319: PokemonLocation('Ruta 7', PokemonLocationKind.route),
      0x031A: PokemonLocation('Ruta 8', PokemonLocationKind.route),
      0x031B: PokemonLocation('Ruta 9', PokemonLocationKind.route),
      0x031C: PokemonLocation('Ruta 10', PokemonLocationKind.route),
      0x031D: PokemonLocation('Ruta 11', PokemonLocationKind.route),
      0x031E: PokemonLocation('Ruta 12', PokemonLocationKind.route),
      0x031F: PokemonLocation('Ruta 13', PokemonLocationKind.route),
      0x0320: PokemonLocation('Ruta 14', PokemonLocationKind.route),
      0x0321: PokemonLocation('Ruta 15', PokemonLocationKind.route),
      0x0322: PokemonLocation('Ruta 16', PokemonLocationKind.route),
      0x0323: PokemonLocation('Ruta 17', PokemonLocationKind.route),
      0x0324: PokemonLocation('Ruta 18', PokemonLocationKind.route),
      0x0325: PokemonLocation('Ruta 19', PokemonLocationKind.route),
      0x0326: PokemonLocation('Ruta 20', PokemonLocationKind.route),
      0x0327: PokemonLocation('Ruta 21 (norte)', PokemonLocationKind.route),
      0x0328: PokemonLocation('Ruta 21 (sur)', PokemonLocationKind.route),
      0x0329: PokemonLocation('Ruta 22', PokemonLocationKind.route),
      0x032A: PokemonLocation('Ruta 23', PokemonLocationKind.route),
      0x032B: PokemonLocation('Ruta 24', PokemonLocationKind.route),
      0x032C: PokemonLocation('Ruta 25', PokemonLocationKind.route),
      0x032D: PokemonLocation('Camino Candente', PokemonLocationKind.route),
      0x032E: PokemonLocation('Playa Tesoro', PokemonLocationKind.other),
      0x032F: PokemonLocation('Cabo Extremo', PokemonLocationKind.other),
      0x0330: PokemonLocation('Puente Unión', PokemonLocationKind.route),
      0x0331: PokemonLocation('Puerto de Isla Tera', PokemonLocationKind.other),
      0x0336: PokemonLocation('Residuo Resort', PokemonLocationKind.other),
      0x0337: PokemonLocation('Laberinto Acuático', PokemonLocationKind.other),
      0x0338: PokemonLocation('Prado de Isla Inta', PokemonLocationKind.other),
      0x0339: PokemonLocation('Pilar Recuerdo', PokemonLocationKind.other),
      0x033A: PokemonLocation('Isla Inta', PokemonLocationKind.other),
      0x033B: PokemonLocation('Vía Verde', PokemonLocationKind.route),
      0x033C: PokemonLocation('Vía Acuática', PokemonLocationKind.route),
      0x033D: PokemonLocation('Valle Ruinas', PokemonLocationKind.other),
      0x033E: PokemonLocation('Torre Desafío', PokemonLocationKind.other),
      0x033F: PokemonLocation('Entrada del Cañón Sétano', PokemonLocationKind.other),
      0x0340: PokemonLocation('Cañón Sétano', PokemonLocationKind.other),
      0x0341: PokemonLocation('Ruinas Sete', PokemonLocationKind.other),
    };
